### PR TITLE
History group undo

### LINKED ISSUE #24488: [Bug]: Browser crashes
Galaxy A52 (Android 12)
Precondition:
1. The browser is installed and running
2. Any URL has been copied to the buffer in advance.

Steps:
1. Click the browser icon "Mozilla FireFox"
2. Touch and hold the address bar area until the context menu appears.
3. Touch the "paste" item in the context menu.

Expected Result:
Pasted URL is displayed in the address bar

Actual result:
Browser crashes.

A comment:
If the keyboard opens during step 2, close it otherwise the bug will not reproduce.

Screen record:
https://drive.google.com/file/d/1SoQVlM0lfOct1KXl9RbB1BDQaD8GxFup/view?usp=sharing

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19983)

### LINKED ISSUE #24513: Undo snackbar for history groups
Part of this [jira](https://mozilla-hub.atlassian.net/browse/FNXV2-18111?focusedCommentId=466569) ticket.

Implement undo mechanism on history group screen to reduce accidental removals and make it consistent with the History Screen.

### PR DESCRIPTION
**Pull request by mavduevskiy**
Closes #24513

### CODE REVIEW

**Comment by mavduevskiy** [comment]
Added delayed removal and an Undo snackbar to history group screen.

Added complexity came from the need to appropriately update the group item count or hide it completely inside the history screen: item deleted inside history group screen -> user backs to history screen -> the group item should consider items pending for removal –> Undo action should updated the group item again.

Adding `pendingDeletionHistoryItems` to `AppState` allows to hide the history items, pending for removal, anywhere in the app. Communication between history group screen and history screen happen through it. Things like recently visited could use the same mechanism.

I was considering removing items from `pendingDeletionHistoryItems` after actual removal, but decided against it. Only pressing Undo button actually affects that set. The thought process was items inside the set should be hidden from the UI no matter if removal has happened.

But removing items from `pendingDeletionHistoryItems` after actual deletion had happened would require tracking if it had been an undo action and in that case we could keep the same data set, but update visibility of the item, or an actual removal, in which case data should be updated to get the list without the deleted item. 
In case of pagination scrolling it might lead to visual glitches when items would be shown again and then hidden, because we already don't have rules to hide the item locally but data set hasn't been updated yet.
Having one source of truth for hiding elements seems more reasonable.

Large data sets with a few dozens deleted items didn't have visual impact on scrolling performance. 

Added `onEmptyStateChanged` to Adapters, that changes the empty state of the history and history group screens. As we manually hide the items, that are about to be removed,  the most reliable way to determine if the list is empty or not, it to actually allow it to be drawn (changes visible/invisible) and if there is a single visible item, change state to notEmpty, and if we have reached the end of the list and there is still zero visible items, we report empty state.

File: app/src/main/java/org/mozilla/fenix/library/bookmarks/BookmarkFragment.kt [hunk 1]
```diff
@@ -330,8 +311,9 @@ class BookmarkFragment : LibraryPageFragment<BookmarkNode>(), UserInteractionHan
             }
         }
 
-        viewLifecycleOwner.lifecycleScope.allowUndo(
-            requireView(), message,
+        MainScope().allowUndo(
+            requireActivity().getRootView()!!,
```
Comment (Amejia481) [inline app/src/main/java/org/mozilla/fenix/library/bookmarks/BookmarkFragment.kt:315]: I think we should avoid `!!` as it could cause crashes, maybe let? :)

File: app/src/main/java/org/mozilla/fenix/library/bookmarks/BookmarkFragment.kt [hunk 2]
```diff
@@ -330,8 +311,9 @@ class BookmarkFragment : LibraryPageFragment<BookmarkNode>(), UserInteractionHan
             }
         }
 
-        viewLifecycleOwner.lifecycleScope.allowUndo(
-            requireView(), message,
+        MainScope().allowUndo(
```
Comment (Amejia481) [inline app/src/main/java/org/mozilla/fenix/library/bookmarks/BookmarkFragment.kt:314]: Is there any specific reason why we switched to `viewLifecycleOwner.lifecycleScope` ?

Comment (Amejia481) [reply app/src/main/java/org/mozilla/fenix/library/bookmarks/BookmarkFragment.kt:314]: I guess it's for keeping the undo after the fragment is gone?

File: app/src/main/java/org/mozilla/fenix/library/downloads/DownloadFragment.kt [hunk 3]
```diff
@@ -41,9 +42,6 @@ class DownloadFragment : LibraryPageFragment<DownloadItem>(), UserInteractionHan
     private lateinit var downloadStore: DownloadFragmentStore
     private lateinit var downloadView: DownloadView
     private lateinit var downloadInteractor: DownloadInteractor
-    private var undoScope: CoroutineScope? = null
-    private var pendingDownloadDeletionJob: (suspend () -> Unit)? = null
-    private lateinit var downloadsUseCases: DownloadsUseCases
```
Comment (Amejia481) [inline app/src/main/java/org/mozilla/fenix/library/downloads/DownloadFragment.kt:46]: Should this part of another ticket, as it's not part of the history group?

File: app/src/main/java/org/mozilla/fenix/library/history/HistoryAdapter.kt [hunk 4]
```diff
@@ -16,13 +16,17 @@ import org.mozilla.fenix.library.history.viewholders.HistoryListItemViewHolder
...
+    private val onEmptyStateChanged: (Boolean) -> Unit,
 ) : PagingDataAdapter<History, HistoryListItemViewHolder>(historyDiffCallback),
     SelectionHolder<History> {
 
     private var mode: HistoryFragmentState.Mode = HistoryFragmentState.Mode.Normal
-    override val selectedItems get() = mode.selectedItems
-    var pendingDeletionIds = emptySet<Long>()
+    private var pendingDeletionItems = emptySet<PendingDeletionHistory>()
     private val itemsWithHeaders: MutableMap<HistoryItemTimeGroup, Int> = mutableMapOf()
+    private var isEmpty = true
```
Comment (Amejia481) [inline app/src/main/java/org/mozilla/fenix/library/history/HistoryAdapter.kt:26]: `isEmpty` is a bit generic,  should we add a more descriptive name or add some comments to indicate why we are using it? WDY? :)

File: app/src/main/java/org/mozilla/fenix/library/history/HistoryAdapter.kt [hunk 5]
```diff
@@ -60,11 +99,31 @@ class HistoryAdapter(
...
+            position == 0,
+            mode,
+            isPendingDeletion,
+            groupPendingDeletionCount
+        )
     }
 
-    fun updatePendingDeletionIds(pendingDeletionIds: Set<Long>) {
-        this.pendingDeletionIds = pendingDeletionIds
+    @Suppress("UndocumentedPublicFunction")
```
Comment (Amejia481) [inline app/src/main/java/org/mozilla/fenix/library/history/HistoryAdapter.kt:124]: Is there any specific reason why we are suppressing ? :)

File: app/src/main/java/org/mozilla/fenix/components/appstate/AppAction.kt [hunk 6]
```diff
@@ -17,12 +17,14 @@ import org.mozilla.fenix.home.recentbookmarks.RecentBookmark
...
 import org.mozilla.fenix.home.recenttabs.RecentTab
 import org.mozilla.fenix.home.recentvisits.RecentlyVisitedItem
+import org.mozilla.fenix.library.history.PendingDeletionHistory
 import org.mozilla.fenix.gleanplumb.Message
 import org.mozilla.fenix.gleanplumb.MessagingState
 
 /**
  * [Action] implementation related to [AppStore].
  */
+@Suppress("UndocumentedPublicClass")
```
Comment (rocketsroger) [inline app/src/main/java/org/mozilla/fenix/components/appstate/AppAction.kt:27]: nit: the convention here is to add new classes to `detekt-baseline.xml`

**Comment by gabrielluong** [comment]
Can we split up the 2 commits for 2 different issues into their own individual PR? Is there any reason we need to have them both in one PR?

File: app/src/main/java/org/mozilla/fenix/library/history/HistoryController.kt [hunk 7]
```diff
@@ -95,7 +108,39 @@ class DefaultHistoryController(
...
+        val pendingDeletionItems = items.map { it.toPendingDeletionHistory() }.toSet()
+        appStore.dispatch(AppAction.UndoPendingDeletionSet(pendingDeletionItems))
+    }
+
+    private fun delete(items: Set<History>): suspend (context: Context) -> Unit {
+        return { context ->
+            CoroutineScope(Dispatchers.IO).launch {
+                store.dispatch(HistoryFragmentAction.EnterDeletionMode)
+                for (item in items) {
+                    GleanHistory.removed.record(NoExtras())
```
Comment (Amejia481) [inline app/src/main/java/org/mozilla/fenix/library/history/HistoryController.kt:126]: Should this part of `GleanMetricsService` and use the `metrics` to report ?  And following the same patter as on 
 `metrics.track(Event.HistorySearchTermGroupTapped)`

File: app/src/main/java/org/mozilla/fenix/library/history/HistoryFragmentStore.kt [hunk 8]
```diff
@@ -131,7 +136,8 @@ sealed class HistoryFragmentAction : Action {
 data class HistoryFragmentState(
     val items: List<History>,
     val mode: Mode,
-    val pendingDeletionIds: Set<Long>,
+    val pendingDeletionItems: Set<PendingDeletionHistory>,
+    val isEmpty: Boolean,
```
Comment (Amejia481) [inline app/src/main/java/org/mozilla/fenix/library/history/HistoryFragmentStore.kt:140]: Could we determine the if is empty from the `items`?

**Review by gabrielluong — CHANGES_REQUESTED** [review]
Adding a request change to have this PR split up. I think the commit with allowing undo to work globally is probably the easier review out of the 2.

File: app/src/main/java/org/mozilla/fenix/library/bookmarks/BookmarkFragment.kt (hunk 1 above)
Comment (mavduevskiy) [reply app/src/main/java/org/mozilla/fenix/library/bookmarks/BookmarkFragment.kt:315]: Hm, that's a good question! 

I don't think getRootView could actually fail after requireActivity was called successfully. The code goes like this:
`asActivity()?.window?.decorView?.findViewById<View>(android.R.id.content) as? ViewGroup`
So, `window` is there after the activity has been created and never set to null again. `decorView` is not null, and there is always a `android.R.id.content` in the decor view.

We actually have `getRootView()!!` [already](https://searchfox.org/mozilla-mobile/source/fenix/app/src/main/java/org/mozilla/fenix/library/bookmarks/edit/EditBookmarkFragment.kt#220) used with a FenixSnackbar, and I couldn't find any crashes related to that!

Going with let would not execute the removal in case there is no proper view provided by `rootView`. Hm, may be we could provide an alternative, like a fragment view? Like `requireActivity().getRootView() ?: requiteView()`
But in that case having no access to the fragment view will also have the same affect.

I think, relying on `activity.window` on the main thread is a as safe bet as it gets. But I don't have a strong opinion on that, want to here your feedback.

File: app/src/main/java/org/mozilla/fenix/library/bookmarks/BookmarkFragment.kt (hunk 2 above)
Comment (mavduevskiy) [reply app/src/main/java/org/mozilla/fenix/library/bookmarks/BookmarkFragment.kt:314]: Yes, it's not to hold a reference to `viewLifecycleOwner.lifecycleScope` in case the user leaves the fragment

File: app/src/main/java/org/mozilla/fenix/library/downloads/DownloadFragment.kt (hunk 3 above)
Comment (mavduevskiy) [reply app/src/main/java/org/mozilla/fenix/library/downloads/DownloadFragment.kt:46]: Yes! It is actually part of a [Working undo](https://github.com/mozilla-mobile/fenix/pull/24398) ticket

File: app/src/main/java/org/mozilla/fenix/library/history/HistoryAdapter.kt (hunk 4 above)
Comment (mavduevskiy) [reply app/src/main/java/org/mozilla/fenix/library/history/HistoryAdapter.kt:26]: The only alternative that comes to my mind is `hasItems`, which I find to be even worse :))
Added explanation.

File: app/src/main/java/org/mozilla/fenix/library/history/HistoryAdapter.kt (hunk 5 above)
Comment (mavduevskiy) [reply app/src/main/java/org/mozilla/fenix/library/history/HistoryAdapter.kt:124]: It looks like Documentation should add something meaningful, which is not immediately obvious from the code. I can't come up with anything about a
```
fun updatePendingDeletionItems(pendingDeletionItems: Set<PendingDeletionHistory>) {
        this.pendingDeletionItems = pendingDeletionItems
    }
```
really :(

File: app/src/main/java/org/mozilla/fenix/components/appstate/AppAction.kt (hunk 6 above)
Comment (mavduevskiy) [reply app/src/main/java/org/mozilla/fenix/components/appstate/AppAction.kt:27]: I am a bit confused, what should I write about?
```
data class AddPendingDeletionSet(val historyItems: Set<PendingDeletionHistory>) : AppAction()
    data class UndoPendingDeletionSet(val historyItems: Set<PendingDeletionHistory>) : AppAction()
```
The name of the class tells what it does already. `pendingDeletionHistoryItems` are already documented inside the `AppState`.

This new lint rule is a bit too demanding.

File: app/src/main/java/org/mozilla/fenix/library/history/HistoryController.kt (hunk 7 above)
Comment (mavduevskiy) [reply app/src/main/java/org/mozilla/fenix/library/history/HistoryController.kt:126]: I think it was done during working on `[this](https://github.com/mozilla-mobile/fenix/issues/24498)` issue.
I just brought that code from the fragment into the controller.

File: app/src/main/java/org/mozilla/fenix/library/history/HistoryFragmentStore.kt (hunk 8 above)
Comment (mavduevskiy) [reply app/src/main/java/org/mozilla/fenix/library/history/HistoryFragmentStore.kt:140]: Sadly, nope. Items inside the `HistoryFragmentState` are empty. Adapter is being fed data directly, avoiding the state:
```
lifecycleScope.launch {
            history.collect {
                historyView.historyAdapter.submitData(it)
            }
        }
```

**Comment by mavduevskiy** [comment]
@gabrielluong 
It is actually the second PR, linked to [this one](https://github.com/mozilla-mobile/fenix/pull/24398)

File: app/src/main/java/org/mozilla/fenix/library/bookmarks/BookmarkFragment.kt (hunk 1 above)
Comment (Amejia481) [reply app/src/main/java/org/mozilla/fenix/library/bookmarks/BookmarkFragment.kt:315]: Ok, that make sense. As we don't have a better alternative, let's keep it!

File: app/src/main/java/org/mozilla/fenix/library/bookmarks/BookmarkFragment.kt (hunk 2 above)
Comment (mavduevskiy) [reply app/src/main/java/org/mozilla/fenix/library/bookmarks/BookmarkFragment.kt:314]: It's actually was causing [a leak](https://github.com/mozilla-mobile/fenix/pull/24398#issuecomment-1103255859)

File: app/src/main/java/org/mozilla/fenix/library/history/HistoryAdapter.kt (hunk 5 above)
Comment (mavduevskiy) [reply app/src/main/java/org/mozilla/fenix/library/history/HistoryAdapter.kt]: added documentation

File: app/src/main/java/org/mozilla/fenix/components/appstate/AppAction.kt (hunk 6 above)
Comment (mavduevskiy) [reply app/src/main/java/org/mozilla/fenix/components/appstate/AppAction.kt]: added documentation

File: app/src/main/java/org/mozilla/fenix/library/history/HistoryAdapter.kt (hunk 4 above)
Comment (Amejia481) [reply app/src/main/java/org/mozilla/fenix/library/history/HistoryAdapter.kt:30]: 👍🏽

File: app/src/main/java/org/mozilla/fenix/library/history/HistoryFragment.kt [hunk 9]
```diff
@@ -165,10 +179,13 @@ class HistoryFragment : LibraryPageFragment<History>(), UserInteractionHandler {
             historyView.update(it)
         }
 
-        userHasHistory.observe(
-            viewLifecycleOwner,
-            historyView::updateEmptyState
-        )
+        requireContext().components.appStore.flowScoped(viewLifecycleOwner) { flow ->
```
Comment (Amejia481) [inline app/src/main/java/org/mozilla/fenix/library/history/HistoryFragment.kt:182]: nit: Maybe we could pass the `appStore` to `HistoryFragment` allow easier testing in the future

File: app/src/main/java/org/mozilla/fenix/library/history/HistoryFragmentStore.kt [hunk 10]
```diff
@@ -168,13 +180,9 @@ private fun historyStateReducer(
...
-                pendingDeletionIds = state.pendingDeletionIds + action.itemIds
-            )
-        is HistoryFragmentAction.UndoPendingDeletionSet ->
-            state.copy(
-                pendingDeletionIds = state.pendingDeletionIds - action.itemIds
-            )
+        is HistoryFragmentAction.ChangeEmptyState -> state.copy(isEmpty = action.isEmpty)
+        is HistoryFragmentAction.UpdatePendingDeletionItems -> state.copy(
+            pendingDeletionItems = action.pendingDeletionItems
+        )
```
Comment (Amejia481) [inline app/src/main/java/org/mozilla/fenix/library/history/HistoryFragmentStore.kt:186]: Maybe we could tests these section without much effort :)

File: app/src/main/java/org/mozilla/fenix/library/history/PendingDeletionHistory.kt [hunk 11]
```diff
@@ -0,0 +1,58 @@
...
+
+package org.mozilla.fenix.library.history
+
+import mozilla.components.concept.storage.HistoryMetadataKey
+
+/**
+ * Wrapper for the data of the history item that have been marked for removal. Undo snackbar delays
+ * the actual removal, while this class is used to match History items that should be hidden in the
+ * UI.
+ */
```
Comment (Amejia481) [inline app/src/main/java/org/mozilla/fenix/library/history/PendingDeletionHistory.kt:13]: 👏🏽

File: app/src/main/java/org/mozilla/fenix/library/historymetadata/HistoryMetadataGroupFragmentStore.kt [hunk 12]
```diff
@@ -91,5 +104,10 @@ private fun historyStateReducer(
         }
         is HistoryMetadataGroupFragmentAction.DeleteAll ->
             state.copy(items = emptyList())
+        is HistoryMetadataGroupFragmentAction.UpdatePendingDeletionItems ->
+            state.copy(pendingDeletionItems = action.pendingDeletionItems)
+        is HistoryMetadataGroupFragmentAction.ChangeEmptyState -> state.copy(
+            isEmpty = action.isEmpty
```
Comment (Amejia481) [inline app/src/main/java/org/mozilla/fenix/library/historymetadata/HistoryMetadataGroupFragmentStore.kt:110]: Maybe we could easily add tests for these sections :)

File: app/src/main/java/org/mozilla/fenix/library/historymetadata/view/HistoryMetadataGroupAdapter.kt [hunk 13]
```diff
@@ -34,16 +38,55 @@ class HistoryMetadataGroupAdapter(
...
+    }
+
     override fun onBindViewHolder(holder: HistoryMetadataGroupItemViewHolder, position: Int) {
-        holder.bind(getItem(position))
+        val current = getItem(position) ?: return
+        if (position == 0) {
+            isEmpty = true
+        }
+
+        val isPendingDeletion = pendingDeletionItems.find {
```
Comment (Amejia481) [inline app/src/main/java/org/mozilla/fenix/library/historymetadata/view/HistoryMetadataGroupAdapter.kt:51]: nit: Maybe any `any` :)

**Review by Amejia481 — APPROVED** [review]
LGTM!

File: app/src/test/java/org/mozilla/fenix/library/history/HistoryFragmentStoreTest.kt [hunk 14]
```diff
@@ -72,6 +73,34 @@ class HistoryFragmentStoreTest {
...
     }
 
+    @Test
+    fun changeEmptyState() = runBlocking {
+        val initialState = emptyDefaultState()
+        val store = HistoryFragmentStore(initialState)
+
+        store.dispatch(HistoryFragmentAction.ChangeEmptyState(true)).join()
+        assertNotSame(initialState, store.state)
+        assertEquals(true, store.state.isEmpty)
```
Comment (Amejia481) [inline app/src/test/java/org/mozilla/fenix/library/history/HistoryFragmentStoreTest.kt:83]: nit: `assertTrue`

File: app/src/test/java/org/mozilla/fenix/library/history/HistoryFragmentStoreTest.kt [hunk 15]
```diff
@@ -72,6 +73,34 @@ class HistoryFragmentStoreTest {
...
+
+        store.dispatch(HistoryFragmentAction.ChangeEmptyState(false)).join()
+        assertNotSame(initialState, store.state)
+        assertEquals(false, store.state.isEmpty)
```
Comment (Amejia481) [inline app/src/test/java/org/mozilla/fenix/library/history/HistoryFragmentStoreTest.kt:87]: nit: `assertFalse`
