### PR TITLE
Integrate activity for showing past crashes.

### LINKED ISSUE #8769: [Bug] "about:crashes" page not doing its job
## Steps to reproduce

I am going to assume that Firefox Preview 3 or Nightly has crashed at least once on your system. Preferably, it has automatically sent a crash report. Open the about:crashes page in the address bar.

### Expected behavior

Judging by the name of the page, you should see a list crashes and/or of (un-) submitted crash reports.

### Actual behavior

You will only see the text "No crash reports have been submitted".

### Device information

* Android device: Nokia 5 (model TA-1024), Android 9.
* Fenix version: all of them, it seems; both Nightly and Preview 3.

### PR DESCRIPTION
**Pull request by pocmo**
The `lib-crash` component now saves information about past crashes to disk and comes with a bit of UI to show this list of crashes. It can directly link to crash reports on Socorro and Sentry which hopefully will make it easier to figure out why the app has crashed and to report crashes.

There are two ways to access the crash list, via "settings > about" and by just typing "about:crashes" into the URL bar (like desktop/Fennec).

Closes #8769, #3552, #2295

### CODE REVIEW

File: app/src/main/java/org/mozilla/fenix/search/SearchController.kt [hunk 1]
```diff
@@ -52,6 +54,14 @@ class DefaultSearchController(
 ) : SearchController {
 
     override fun handleUrlCommitted(url: String) {
+        if (url == "about:crashes") {
+            // The list of past crashes can be accessed via "settings > about", but desktop and
```
Comment (mcarare) [inline app/src/main/java/org/mozilla/fenix/search/SearchController.kt:58]: There is also the possibility of pasting "about:crashes" with "fill link from clipboard". Do you think we should intercept that also?

Comment (pocmo) [reply app/src/main/java/org/mozilla/fenix/search/SearchController.kt:58]: Good point!

I don't think it is worth the effort at this point. Even this here is something I didn't really intented to do and was just more for convenience.
