### PR TITLE
For #4094 - Fix screenshots tests on API 21 devices

### LINKED ISSUE #4094: [Bug] Failing UI test - settingsAfterScrollMenusTest
The settingsAfterScrollMenusTest (UI test) is failing in Firebase on API 21.
Click on link to Firebase dashboard:
https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8610891157502804039
Drill down on failing API and click on tabs or "Test Results" button on upper right to view raw logs in GCP.
```
07-16 12:51:51.696: I/TestRunner(25691): ----- begin exception -----
07-16 12:51:51.698: I/TestRunner(25691): androidx.test.espresso.NoMatchingViewException: No views in hierarchy found matching: with id: org.mozilla.fenix.debug:id/switch_widget
```

### PR DESCRIPTION
**Pull request by isabelrios**
### Pull Request checklist

- [x] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/fenix/blob/master/CHANGELOG.md) or does not need one

This PR fixes #4094

### CODE REVIEW

**Comment by isabelrios** [comment]
@rpappalax with this PR screenshots tests will be fixed. 
It is not necessary to have these screeenshots tests running as part of regular builds. I'm wondering the best way to do that. I have thought about adding the ui tests we want to run in a package and select it for running the tests as part of the CI. So instead of running all tests in `org.mozilla.fenix.ui` only run the tests in `org.mozilla.fenix.ui.uiTests` (or whatever pckg name) But not sure if that works for you and all the CI implementation...let's see what's the best option...Thanks!

File: app/src/androidTest/java/org/mozilla/fenix/ui/screenshots/ThreeDotMenuScreenShotTest.kt [hunk 1]
```diff
@@ -78,49 +77,20 @@ class ThreeDotMenuScreenShotTest : ScreenshotTest() {
         }.openThreeDotMenu {
         }
         settingsButton2()
+        onView(withId(R.id.recycler_view)).perform(swipeUp())
```
Comment (jhugman) [inline app/src/androidTest/java/org/mozilla/fenix/ui/screenshots/ThreeDotMenuScreenShotTest.kt]: These two lines might better be put in the `Robot` for this screen.

Comment (rpappalax) [reply app/src/androidTest/java/org/mozilla/fenix/ui/screenshots/ThreeDotMenuScreenShotTest.kt]: > These two lines might better be put in the `Robot` for this screen.

I spoke with @isabelrios this morning.  She's going to go ahead and land this for now since she's waiting for updates on the robot to stick this in.

**Comment by isabelrios** [comment]
> Good to see code being deleted!
> 
> Any actions should likely end up in the Robot class for each screen.
> 
> Please land once you've done that! Thank you.

There were two issues here why I did not use the Robots. One is that other people in the team were working on that and they were not ready when the screenshtos tests were created, kind in a hurry to have the screenshots to share with localizers.

The other is that there are not ids for most of the elements and robots are using, for example to access to Settings menu: `onView(allOf(withText("Settings")))` I would need this to be changed to something like: ` onView(allOf(withText(R.string.settings)))` so that the tests work (otherwise they are going to work only in English)

That said, I agree we have to write these tests better and use the robots, I will use the ones that are already implemented. But I need to check with @rpappalax if that change in the robots to get to the elements or checking them is fine with them. 
Thanks!
