### PR TITLE
Closes #13217: fixed UI test for main menu items

### LINKED ISSUE #13217: Intermittent UI test failure - SmokeTest.verifyPageMainMenuItemsListInPortraitNormalModeTest & verifyPageMainMenuItemsListInPortraitPrivateModeTest
### Firebase Test Run:
-- verifyPageMainMenuItemsListInPortraitNormalModeTest:
https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7335205555748744405/executions/bs.8d7763ca904873c8/testcases/2/test-cases

https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8312248502354333158/executions/bs.a33b318b86783b71/testcases/2/test-cases

-- verifyPageMainMenuItemsListInPortraitPrivateModeTest:
https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8312248502354333158/executions/bs.67f587fcbf4d9ea5/testcases/2/test-cases
https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7335205555748744405/executions/bs.f80400e7f8bdc4db/testcases/2/test-cases

### Stacktrace:
`androidx.test.espresso.NoMatchingViewException: No views in hierarchy found matching: with res-name that is "sync_tabs_status"`
### Build: 8/1

cc: @TejaswiKarasani

### PR DESCRIPTION
**Pull request by sv-ohorvath**
Ran the test on Firebase 20 times and has passed all.

### CODE REVIEW

File: app/src/androidTest/java/org/mozilla/fenix/ui/SmokeTest.kt [hunk 1]
```diff
@@ -234,13 +146,6 @@ class SmokeTest {
             }.enterURLAndEnterToBrowser(defaultWebPage.url) {
                 verifyEnhancedTrackingProtectionPanelNotVisible()
             }.openThreeDotMenu {
-            }.clickAddOnsReportSiteIssue {
```
Comment (isabelrios) [inline app/src/androidTest/java/org/mozilla/fenix/ui/SmokeTest.kt:237]: Not sure if this test should be enabled after the changes you did...or even though you removed part of it it is still failing...

Comment (sv-ohorvath) [reply app/src/androidTest/java/org/mozilla/fenix/ui/SmokeTest.kt:237]: I removed that part because the Report site issue was removed from the menu and had to update it everywhere.

**Review by isabelrios — APPROVED** [review]
LGTM! Thanks for working on the Smoketest!
