### PR TITLE
For #24219 - Refactor Favicon to fix previews

### LINKED ISSUE #24219: Fix @Previews for SyncedTabs after adding favicons
After https://github.com/mozilla-mobile/fenix/pull/24176, the `@previews` broke because the `Favicon` composable uses the `components` Object, which does not work in the `@Preview` build chain. The `Favicon` composable should be refactored to allow for local previews.

### PR DESCRIPTION
**Pull request by MozillaNoah**
Closes #24219 

### Pull Request checklist

- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

File: app/src/main/java/org/mozilla/fenix/compose/ComposeUtil.kt [hunk 1]
```diff
@@ -0,0 +1,15 @@
+/* This Source Code Form is subject to the terms of the Mozilla Public
```
Comment (gabrielluong) [inline app/src/main/java/org/mozilla/fenix/compose/ComposeUtil.kt:1]: Let's rename this file to `ComposeUtils` to be consistent with most of our `Utils` naming

File: app/src/main/java/org/mozilla/fenix/compose/Favicon.kt [hunk 2]
```diff
@@ -38,32 +41,55 @@ fun Favicon(
...
+    if (inComposePreview) {
+        Placeholder(size = size)
+    } else {
+        components.core.icons.Loader(
+            url = url,
+            isPrivate = isPrivate,
+            size = size.toIconRequestSize()
+        ) {
+            Placeholder {
+                Placeholder(size = size)
```
Comment (gabrielluong) [inline app/src/main/java/org/mozilla/fenix/compose/Favicon.kt:53]:
```suggestion
                FaviconPlaceholder(size = size)
```

Let's add a prefix for this. Having a Placeholder inside of a Placeholder is kinda disguised 🥸.

**Review by gabrielluong — APPROVED** [review]
