### PR TITLE
Closes #1644 - Correct progress bar gravity

### LINKED ISSUE #1644: FNX3-15708 ⁃ [Bug] regression: progress bar is below the toolbar again
### Steps to reproduce
1. load a website

### Expected behavior
The progress bar is above the toolbar.

### Actual behavior
The progress bar is below the toolbar again.

I can't provide a screenshot because Fenix loads the websites too fast. But I guess that's a good sign. :sweat_smile:

### Device information
* Android device: HTC U11 / Android 8.0
* Fenix version: Fenix revision 658f6dcf23a086090da9cd24d5a28d900bfb2bfc

### PR DESCRIPTION
**Pull request by ekager**
### Pull Request checklist

- [X] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [X] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [X] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/fenix/blob/master/CHANGELOG.md) or does not need one
- [X] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### CODE REVIEW

File: app/src/main/java/org/mozilla/fenix/components/toolbar/ToolbarUIView.kt [hunk 1]
```diff
@@ -173,6 +172,8 @@ class ToolbarUIView(
     }
 
     companion object {
+        private const val PROGRESS_BOTTOM = 0
```
Comment (boek) [inline app/src/main/java/org/mozilla/fenix/components/toolbar/ToolbarUIView.kt]: Does 0 / 1 map to the Gravity constants?

Comment (ekager) [reply app/src/main/java/org/mozilla/fenix/components/toolbar/ToolbarUIView.kt]: Yep!

Comment (ekager) [reply app/src/main/java/org/mozilla/fenix/components/toolbar/ToolbarUIView.kt]: AC customs gravity progress constants
