### PR TITLE
For #21694 - Fix the layout in the Recent Searches

### LINKED ISSUE #21694: Fix the layout in the Recent Searches
- We are currently only NOT showing the divider line for the last item in a column in Recent Searches. So, this means you will see a divider line even if there's only 1 item in Recent Searches. We should show a divider in between items only.
Screen Shot 2021-10-04 at 4 04 13 PM

- Remove clip(RoundedCornerShape(8.dp) around the Column in Recent Searches. This causes the click gestures to round for the first and last items, which doesn't seem like what we want. https://searchfox.org/mozilla-mobile/source/fenix/app/src/main/java/org/mozilla/fenix/historymetadata/view/RecentlyVisited.kt#8.
This is the green clip for illustration.
Screen Shot 2021-10-04 at 4 09 33 PM

### PR DESCRIPTION
**Pull request by gabrielluong**
Fixes #21694

### Pull Request checklist

- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

File: app/src/main/java/org/mozilla/fenix/historymetadata/view/RecentlyVisited.kt [hunk 1]
```diff
@@ -118,8 +117,7 @@ private fun RecentVisitItem(
                 onClick = { onRecentVisitClick(recentVisit) },
                 onLongClick = { menuExpanded = true }
             )
-            .size(268.dp, 56.dp)
-            .background(color = FirefoxTheme.colors.surface),
```
Comment (gabrielluong) [inline app/src/main/java/org/mozilla/fenix/historymetadata/view/RecentlyVisited.kt:122]: This removes a reductant background modifier since it's already defined in the parent Card.

**Review by MozillaNoah — APPROVED** [review]
