### PR TITLE
For #11342 - Fixes missing space for the FAB

### LINKED ISSUE #11342: FNX-12255 ⁃ [Bug] FAB covers last tab in tab tray

### PR DESCRIPTION
**Pull request by boek**
Fixes #11342

image

Also fixes top offset in landscape

image

### CODE REVIEW

File: app/src/main/java/org/mozilla/fenix/tabtray/TabTrayDialogFragment.kt [hunk 1]
```diff
@@ -57,6 +57,9 @@ class TabTrayDialogFragment : AppCompatDialogFragment(), TabTrayInteractor {
     override fun onConfigurationChanged(newConfig: Configuration) {
         super.onConfigurationChanged(newConfig)
 
+        val isLandscape = newConfig.orientation == Configuration.ORIENTATION_LANDSCAPE
```
Comment (ekager) [inline app/src/main/java/org/mozilla/fenix/tabtray/TabTrayDialogFragment.kt:60]: could we combine this with the next check?

Comment (boek) [reply app/src/main/java/org/mozilla/fenix/tabtray/TabTrayDialogFragment.kt:60]: doh, I meant to do that! Good catch!
