### PR TITLE
Closes #1062 & Closes #1121: Restyles crash reporter view

### LINKED ISSUE #1121: FNX-4813 ⁃ Restyle crash reporting to match new UX
[New UX found here](https://github.com/mozilla-mobile/fenix/issues/1102#issuecomment-475060831)

### PR DESCRIPTION
**Pull request by sblatz**
Blocked on [getting this asset](https://github.com/mozilla-mobile/fenix/issues/1102#issuecomment-475301887)

### CODE REVIEW

File: app/src/main/java/org/mozilla/fenix/crashes/CrashReporterFragment.kt [hunk 1]
```diff
@@ -8,12 +8,15 @@ import android.os.Bundle
 import android.view.LayoutInflater
 import android.view.View
 import android.view.ViewGroup
+import android.widget.TextView
 import androidx.fragment.app.Fragment
 import androidx.navigation.Navigation
 import kotlinx.android.synthetic.main.fragment_crash_reporter.*
 import mozilla.components.lib.crash.Crash
+import org.jetbrains.anko.find
```
Comment (colintheshots) [inline app/src/main/java/org/mozilla/fenix/crashes/CrashReporterFragment.kt]: We're using anko for A/B testing layouts. It may be reasonable to use anko here, too. However, the Android framework finally became smart enough to auto-cast findViewById() calls in the past couple years. The convenience here is probably a wash and not really worth it anymore.

Comment (sblatz) [reply app/src/main/java/org/mozilla/fenix/crashes/CrashReporterFragment.kt]: Whoops! Meant to use `findViewById` here :)
