### PR TITLE
Closes #12954 - Remove all ConstraintLayout casts in SearchEngineList…

### LINKED ISSUE #12954: [Bug]Crash Code Report(Always Crash)
## Steps to reproduce
Click **Settings** and click **Search**, then select a search engine that is different from the default search engine.

### Expected behavior
Select successfully.

### Actual behavior
Crash.

### Device information
* Android device: Xiaomi Redmi Note 8 Pro
* Fenix version: Nightly 200726 10:10
* Android Version: 10 (MIUI 12, latest patch)
* SoC: MediaTek Helio G90T (ARM64, ARMv8.2-A)

### PR DESCRIPTION
**Pull request by ekager**
…Preference

### Pull Request checklist

- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### After merge
- [ ] **Milestone**: Make sure issues finished by this pull request are added to the [milestone](https://github.com/mozilla-mobile/fenix/milestones) of the version currently in development.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

File: app/src/main/java/org/mozilla/fenix/settings/search/SearchEngineListPreference.kt [hunk 1]
```diff
@@ -147,7 +151,8 @@ abstract class SearchEngineListPreference @JvmOverloads constructor(
 
     override fun onCheckedChanged(buttonView: CompoundButton, isChecked: Boolean) {
         searchEngineList.list.forEach { engine ->
-            val wrapper: ConstraintLayout = searchEngineGroup?.findViewWithTag(engine.identifier) ?: return
+            val wrapper: LinearLayout =
```
Comment (ekager) [inline app/src/main/java/org/mozilla/fenix/settings/search/SearchEngineListPreference.kt:154]: This is the only change, the rest is just formatting
