### PR TITLE
For #23138 - Close recently visited menu on orientation change

### LINKED ISSUE #23138: [Bug]: "Recently visited section" - Switching between portrait and landscape mode, the Remove menu is overlapping the URL bar
### Steps to reproduce

1. Enable Portrait mode from your device
2. Open some sites
2. Navigate to the Homepage -> Recently visited section
3. Long tap on a tab from Recently visited section
4. Switch from portrait to landscape mode 

### Expected behaviour

The Remove menu must not overlap the URL bar when switching between portrait and landscape mode.

### Actual behaviour

The Remove menu is overlapping the URL bar when switching between portrait and landscape mode. For more details 
 please see the video attached.

https://user-images.githubusercontent.com/96047134/148762056-c9eb6c65-a02c-4be0-9340-5372ac100f5f.mp4

### Device name

Samsung S10E

### Android version

Android 10

### Firefox release type

Firefox Nightly

### Firefox version

97.0a1

### Device logs

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by sarah541**
Fixes #23138 

### Pull Request checklist

- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

File: app/src/main/java/org/mozilla/fenix/home/recentvisits/view/RecentlyVisited.kt [hunk 1]
```diff
@@ -31,13 +31,10 @@ import androidx.compose.material.Divider
 import androidx.compose.material.DropdownMenu
 import androidx.compose.material.DropdownMenuItem
 import androidx.compose.material.Text
-import androidx.compose.runtime.Composable
-import androidx.compose.runtime.getValue
-import androidx.compose.runtime.mutableStateOf
-import androidx.compose.runtime.remember
-import androidx.compose.runtime.setValue
+import androidx.compose.runtime.*
```
Comment (gabrielluong) [inline app/src/main/java/org/mozilla/fenix/home/recentvisits/view/RecentlyVisited.kt:34]: nit: Don't use * imports. Also, check if you are running the project's style configurations https://github.com/mozilla-mobile/android-components#style.

**Comment by gabrielluong** [comment]
Note, I moved the milestone over to the issue.

File: app/src/main/java/org/mozilla/fenix/home/recentvisits/view/RecentlyVisited.kt [hunk 2]
```diff
@@ -38,6 +38,8 @@ import androidx.compose.runtime.remember
 import androidx.compose.runtime.setValue
 import androidx.compose.ui.Alignment
 import androidx.compose.ui.Modifier
+import androidx.compose.ui.platform.LocalConfiguration
+import androidx.compose.runtime.DisposableEffect
```
Comment (gabrielluong) [inline app/src/main/java/org/mozilla/fenix/home/recentvisits/view/RecentlyVisited.kt:42]: Might also want to run a format code. Usually the imports are ordered alphabetically I think.

**Review by gabrielluong — APPROVED** [review]
