### PR TITLE
Fixes #1186: Add accessibility actions and semantics to quick actions sheet handle

### LINKED ISSUE #1186: FNX-4856 ⁃ A11y action for the Quick action bar handle
## Steps to reproduce
1. Turn talkBack on.
1. Open a webpage in Fenix, swipe to reach the quick action bar handle.
    1. Expected behavior
The handle button name is read and on double tap, it expands/collapses the q.a.b.
    1. Actual behavior
The quick action sheet handle is read but it doesn't have the function to collapse/expand the bar.
    1. Device information

* Android device: Pixel (Android 9), Galaxy Tab (Android 8)
* Fenix version: 3/22 build.

### PR DESCRIPTION
**Pull request by eeejay**
No need for a changelog. The QuickActionsSheet does not have any tests, but when it does we should add some!

### Pull Request checklist

- [x] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/fenix/blob/master/CHANGELOG.md) or does not need one
- [x] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### CODE REVIEW

File: app/src/main/java/org/mozilla/fenix/quickactionsheet/QuickActionSheet.kt [hunk 1]
```diff
@@ -39,25 +40,28 @@ class QuickActionSheet @JvmOverloads constructor(
...
-            linearLayout.setOnClickListener {
-                quickActionSheetBehavior.state = when (quickActionSheetBehavior.state) {
-                    BottomSheetBehavior.STATE_EXPANDED -> BottomSheetBehavior.STATE_COLLAPSED
-                    else -> BottomSheetBehavior.STATE_EXPANDED
-                }
-            }
-            return
-        }
 
-        handle.increaseTapArea(grabHandleIncreasedTapArea)
```
Comment (colintheshots) [inline app/src/main/java/org/mozilla/fenix/quickactionsheet/QuickActionSheet.kt]: Will the tap radius still be large enough on removing the touch delegate?

**Comment by eeejay** [comment]
> @eeejay: I tested this and it all looks really good to me! Thanks for the fix.
> 
> I noticed that the quick action sheet is still "visible" to screen readers when behind the browser toolbar, yet this patch removes the ability to tap it to expand the sheet. Do you think this will be confusing to users?

Oops! Yes. That is what the third patch in the set does. I forgot to update importantForAccessibility on setup, so initially you "saw" that sheet. I'll followup to fix that.

**Comment by boek** [comment]
@sblatz want to double check this and land it? :grin:
