### PR TITLE
For #28510 - Keep experimental messages in the correct order

### LINKED ISSUE #28510: [Experiment] [Viewpoint Survey (2023 Jan, Android)] The Viewpoint survey message is replaced by the "Set as default" message and vice versa each time Firefox is reopened from the background
### Steps to reproduce

[Prerequisites]:
- Have the device’s language set to any of the following: 'de', 'en', 'es', 'fr', 'ja', 'pl', 'pt', 'ru', 'zh'.
- Have the Firefox 109 Release build installed on a device.

[Steps to reproduce]:
1. Open the 109 Release build from the prerequisites.
2. Navigate to the Firefox "Settings" menu.
3. Scroll down to the bottom of the list and tap the "About Firefox" option.
4. Tap the "Firefox Browser" logo 5 times and go back to the "Settings" menu.
5. Scroll down to the bottom of the list and tap the "Secret Settings" option.
6. Enable the “Use Nimbus Preview Collection” option and restart the browser.
7. Enable the Secret Settings menu again.
8. Scroll down to the bottom of the list and tap the "Nimbus Experiments" option.
9. Tap the "Viewpoint Survey (2022 Dec, Android)" experiment.
10. Tap the “treatment” branch and restart the browser.
11. Observe the message displayed in the top part of the screen.
12. Send the Firefox app to the background then reopen it.
13. Observe the message displayed in the top part of the screen.

### Expected behaviour

Step 11 & Step 13: The same message is displayed.

### Actual behaviour

Step 11: A message that asks the user to complete a survey is displayed on the Homepage.
Step 13: The "Set as default browser" message is displayed.

### Device name

Samsuns S9, Samsung Galaxy S8, Google Pixel 2XL

### Android version

Android 11, Android 10, Android 9

### Firefox release type

Firefox

### Firefox version

Firefox 109 Release, Firefox Beta 109, Firefox Nightly 110

### Device logs

_No response_

### Additional information

- Each time the Firefox browser is sent to the background and reopened the two messages are switched.
- The issue is also reproducible when the device screen is turned off while the Firefox app is focused and then is turned on.
- The issue is NOT reproducible when the app is fully closed and reopened.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22266)

### PR DESCRIPTION
**Pull request by sarah541**
### Pull Request checklist

- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### QA

- [x] **QA Needed**

### To download an APK when reviewing a PR (after all CI tasks finished running):
1. Click on `Checks` at the top of the PR page.
2. Click on the `firefoxci-taskcluster` group on the left to expand all tasks.
3. Click on the `build-debug` task.
4. Click on `View task in Taskcluster` in the new `DETAILS` section.
5. The APK links should be on the right side of the screen, named for each CPU architecture.

### GitHub Automation
Fixes #28510

### CODE REVIEW

**Review by Amejia481 — APPROVED** [review]
Looks good to me, there is a test failure that we have to address before landing.

As @t-p-white and @jhugman having working lately on this code path, I think it will be good they have a look too :)

File: app/src/main/java/org/mozilla/fenix/gleanplumb/state/MessagingMiddleware.kt [hunk 1]
```diff
@@ -144,6 +144,9 @@ class MessagingMiddleware(
         if (actualMessageToShow?.id == oldMessage.id) {
             context.dispatch(UpdateMessageToShow(updatedMessage))
         }
-        return removeMessage(context, oldMessage) + updatedMessage
+        val oldMessageIndex = context.state.messaging.messages.indexOfFirst { it.id == updatedMessage.id }
```
Comment (jonalmeida) [inline app/src/main/java/org/mozilla/fenix/gleanplumb/state/MessagingMiddleware.kt:147]:
```suggestion
        val oldMessageIndex = context.state.messaging.messages.indexOfFirst { it.id == oldMessage.id }
```

The ID is the same regardless of the two messages, but since the binding is `oldMessageIndex`, did you mean to use `oldMessage`?

File: app/src/test/java/org/mozilla/fenix/gleanplumb/state/MessagingMiddlewareTest.kt [hunk 2]
```diff
@@ -245,42 +245,63 @@ class MessagingMiddlewareTest {
     }
 
     @Test
-    fun `WHEN updateMessage THEN update available messages`() = runTestOnMain {
+    fun `WHEN updateMessage THEN update available messages in same order`() = runTestOnMain {
         val oldMessage = Message(
             "oldMessage",
-            MessageData(),
+            MessageData(surface = MessageSurfaceId.HOMESCREEN),
```
Comment (jonalmeida) [inline app/src/test/java/org/mozilla/fenix/gleanplumb/state/MessagingMiddlewareTest.kt:251]: This SurfaceId depends on the generated class based on surface IDs that can change. Maybe we shouldn't use this value?

Same for the `surface` attribute.

File: app/src/test/java/org/mozilla/fenix/gleanplumb/state/MessagingMiddlewareTest.kt [hunk 3]
```diff
@@ -245,42 +245,63 @@ class MessagingMiddlewareTest {
...
+            listOf("trigger"),
+            Message.Metadata("different-id", pressed = true),
+        )
+
         val spiedMiddleware = spyk(middleware)
 
         val appState: AppState = mockk(relaxed = true)
         val messagingState: MessagingState = mockk(relaxed = true)
 
+        every { messagingState.messages } returns listOf(oldMessage, secondOldMessage)
```
Comment (jonalmeida) [inline app/src/test/java/org/mozilla/fenix/gleanplumb/state/MessagingMiddlewareTest.kt:290]: I realize you didn't write this test, but it doesn't actually test anything since we're returning the data we are asserting.

Let's write a separate test instead that uses a real store so we can test that the middleware is not changing the message position. We should also file an issue to refactor these tests to use a real store and not a mock.

**Review by jonalmeida — CHANGES_REQUESTED** [review]
The fix looks good! Let's write a separate test instead of modifying this one since there is some baggage with this that might be outside the scope of your change.

File: app/src/main/java/org/mozilla/fenix/gleanplumb/state/MessagingMiddleware.kt (hunk 1 above)
Comment (sarah541) [reply app/src/main/java/org/mozilla/fenix/gleanplumb/state/MessagingMiddleware.kt:147]: No, actually we want to check if the id of the `updatedMessage` matches to the id of any item of the `messages` list. This item is actually the `oldMessage` which will always be present in the list.

**Review by jonalmeida — APPROVED** [review]
The change looks good! Let's wait to land this after the weekend. :)

**Comment by jonalmeida** [comment]
Offline, @sarah541 and I spoke about refactoring the MessagingMiddlewareTest, so we filed BZ-1813252 to track this work.

**Comment by t-p-white** [comment]
> As @t-p-white and @jhugman having working lately on this code path, I think it will be good they have a look too :)

Thanks for highlighting this @Amejia481 👍 Can confirm there are no conflicts with our changes
