### PR TITLE
For #26227 - Remove search term tab groups from Jump Back In

### LINKED ISSUE #26227: [Bug]: "Jump back in" section displays tab groups but tabs tray no longer supports them
### Steps to reproduce

1. Trigger a search
2. Open a few search results in tabs
3. Go to home screen

### Expected behaviour

Jump back in should display last tab, but no tab group

### Actual behaviour

Jump back in shows tab group. Tapping on it opens the tabs tray which no longer supports groups and therefore doesn't highlight the group. It also may, depending on the previously selected tab, highlight an unrelated tab.

### Device name

Pixel 6a

### Android version

Android 12

### Firefox release type

Firefox Nightly

### Firefox version

105.0a1

### Device logs

_No response_

### Additional information

Tab groups were removed as part of https://github.com/mozilla-mobile/fenix/issues/21898 in https://github.com/mozilla-mobile/fenix/commit/7e59a644d5890c1ce083b9435e27acd58d04fb1f. However, the "Jump back in" section wasn't addressed as part of this work, leaving this in an inconsistent state.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21139)

### PR DESCRIPTION
**Pull request by MozillaNoah**
### Pull Request checklist

- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### QA

- [x] **QA Needed**

### To download an APK when reviewing a PR (after all CI tasks finished running):
1. Click on `Checks` at the top of the PR page.
2. Click on the `firefoxci-taskcluster` group on the left to expand all tasks.
3. Click on the `build-debug` task.
4. Click on `View task in Taskcluster` in the new `DETAILS` section.
5. The APK links should be on the right side of the screen, named for each CPU architecture.

### GitHub Automation
Fixes #26227

### CODE REVIEW

File: app/src/main/java/org/mozilla/fenix/components/appstate/AppStoreReducer.kt [hunk 1]
```diff
@@ -44,12 +42,7 @@ internal object AppStoreReducer {
             topSites = action.topSites,
             recentBookmarks = action.recentBookmarks,
             recentTabs = action.recentTabs,
-            recentHistory = if (action.recentHistory.isNotEmpty() && action.recentTabs.isNotEmpty()) {
-                val recentSearchGroup = action.recentTabs.find { it is RecentTab.SearchGroup } as RecentTab.SearchGroup?
-                action.recentHistory.filterOut(recentSearchGroup?.searchTerm)
-            } else {
-                action.recentHistory
-            }
```
[the remark this answers is not in the document]
Comment (MozillaNoah) [reply app/src/main/java/org/mozilla/fenix/components/appstate/AppStoreReducer.kt:52]: don't worry, it's confusing to me too lol. `recent tabs` is anything to do with `jump back in` and tracking the tabs to show in that content section on the homepage. `Recently visited tabs` is anything to do with the history and search history content section on the homepage. 

so this edit here is just removing the filter, since groups in `recent tabs` will no longer be a thing, so we don't need to account for it in history. that's my understanding of it, anyway.

File: app/src/main/java/org/mozilla/fenix/tabstray/viewholders/NormalBrowserPageViewHolder.kt [hunk 2]
```diff
@@ -79,15 +78,13 @@ class NormalBrowserPageViewHolder(
         layoutManager: RecyclerView.LayoutManager
     ) {
         val concatAdapter = adapter as ConcatAdapter
-        val browserAdapter = concatAdapter.browserAdapter
         val inactiveTabAdapter = concatAdapter.inactiveTabsAdapter
         val inactiveTabsAreEnabled = containerView.context.settings().inactiveTabsAreEnabled
 
         val selectedTab = browserStore.state.selectedNormalTab ?: return
         // It's safe to read the state directly (i.e. won't cause bugs because of the store actions
```
Comment (rocketsroger) [inline app/src/main/java/org/mozilla/fenix/tabstray/viewholders/NormalBrowserPageViewHolder.kt:85]: This comment seems to be out of place.  Do we know where this comment should be attached to?

**Review by rocketsroger — COMMENTED** [review]
Looks good.  Tested it and didn't see any issue.  Small comments.

File: app/src/main/java/org/mozilla/fenix/tabstray/viewholders/NormalBrowserPageViewHolder.kt (hunk 2 above)
Comment (MozillaNoah) [reply app/src/main/java/org/mozilla/fenix/tabstray/viewholders/NormalBrowserPageViewHolder.kt:85]: It probably belonged to `focusGroupTabId`, so I'll remove it since that's gone now. Good catch

File: app/src/main/java/org/mozilla/fenix/ext/BrowserState.kt [hunk 3]
```diff
@@ -29,26 +25,13 @@ const val DEFAULT_ACTIVE_DAYS = 14L
...
 /**
- * Get the last opened normal tab, last tab with in progress media and last search term group, if available.
+ * Get the last opened normal tab or last tab with in progress media.
  *
- * @return A list of the last opened tab not part of the last active search group and
- * the last active search group if these are available or an empty list.
+ * @return A list of the last opened tab or an empty list.
  */
 fun BrowserState.asRecentTabs(): List<RecentTab> {
     return mutableListOf<RecentTab>().apply {
```
[the remark this answers is not in the document]
Comment (MozillaNoah) [reply app/src/main/java/org/mozilla/fenix/ext/BrowserState.kt:33]: sure that makes sense to me

File: app/src/main/java/org/mozilla/fenix/tabstray/viewholders/NormalBrowserPageViewHolder.kt [hunk 4]
```diff
@@ -106,23 +100,6 @@ class NormalBrowserPageViewHolder(
...
-                    if (trayTab.id == selectedTab.id) {
-                        // Index is based on tabs above (inactive) with our calculated index.
-                        val indexToScrollTo = inactiveTabAdapter.itemCount + tabIndex
-
-                        containerView.post { layoutManager.scrollToPosition(indexToScrollTo) }
-
-                        return@observeFirstInsert
-                    }
-                }
-            }
```
Comment (MozillaNoah) [inline app/src/main/java/org/mozilla/fenix/tabstray/viewholders/NormalBrowserPageViewHolder.kt:124]: Realized while addressing @rocketsroger's feedback that this should be added back in, as it controls the scroll-to logic for active tabs. Moved it to an `else` after the selected tab id logic block for inactive tabs.

**Review by rocketsroger — APPROVED** [review]
🚢 Looks good, thanks
