### PR TITLE
For #11291 - Provide New Tab button when accessibility enabled

### LINKED ISSUE #11291: FNX-12196 ⁃ [Bug] Tab Tray A11y:  FAB isn't focusable by TalkBack when Tab Tray is Extended
## Steps to reproduce
1. Turn on talkback
1. Open the tab tray to extended mode
1. Try to tap the FAB -- doesn't get selected
1. Gesture right until you get to the close button of the last tab -- FAB doesn't get selected

### Expected behavior
FAB should get selected when tray is in extended mode

### Actual behavior
FAB DOES NOT get selected when tray is in extended mode

### Device information
* Android device: Pixel 4
* Fenix version: Current master

### PR DESCRIPTION
**Pull request by darkwing**
Fixes #11291. 

This provides an "Add tab" button at the header of the tab tray so that users with accessibility features enabled can more easily add a tab instead of the FAB.  Even better is that the user wouldn't need to scroll through all tabs to get to the "New tab" FAB -- it would be the third control available!

Screenshot_20200610-124510

To test:
1.  Open the tab tray with talkback off
2. View FAB, don't view "add tab" button in header
3.  Turn on Talkback
4.  Open the tab tray
5.  View "add tab" button, don't view FAB

### CODE REVIEW

File: app/src/main/java/org/mozilla/fenix/tabtray/TabTrayView.kt [hunk 1]
```diff
@@ -142,8 +143,30 @@ class TabTrayView(
                 }
         }
 
-        fabView.new_tab_button.setOnClickListener {
-            interactor.onNewTabTapped(isPrivateModeSelected)
+        val accessibilityManager =
+            view.context.applicationContext.getSystemService(Context.ACCESSIBILITY_SERVICE) as? AccessibilityManager
+        val hasAccessibilityEnabled = accessibilityManager?.isEnabled ?: false
```
Comment (darkwing) [inline app/src/main/java/org/mozilla/fenix/tabtray/TabTrayView.kt:148]: @sblatz Is this block sufficient to know if the user is using talkback or another a11y service?  Anything more I should do or check?

**Comment by darkwing** [comment]
> I don't have TalkBack enabled but see the +- icon next to the 3-dot menu

Ohhh, the FAB still shows when in expanded mode.  OK, I'll fix that!

File: app/src/main/java/org/mozilla/fenix/tabtray/TabTrayView.kt (hunk 1 above)
Comment (sblatz) [reply app/src/main/java/org/mozilla/fenix/tabtray/TabTrayView.kt:148]: You should check against the settings param: `accessibilityServicesEnabled` it checks for both switch services and touch exploration services :)

File: app/src/main/java/org/mozilla/fenix/tabtray/TabTrayView.kt [hunk 2]
```diff
@@ -142,8 +147,26 @@ class TabTrayView(
                 }
         }
 
-        fabView.new_tab_button.setOnClickListener {
-            interactor.onNewTabTapped(isPrivateModeSelected)
+        view.tab_tray_new_tab.apply {
+            visibility = if (hasAccessibilityEnabled) {
```
Comment (boek) [inline app/src/main/java/org/mozilla/fenix/tabtray/TabTrayView.kt:151]: Nit: use isVisivible

File: app/src/main/java/org/mozilla/fenix/tabtray/TabTrayView.kt [hunk 3]
```diff
@@ -142,8 +147,26 @@ class TabTrayView(
...
+            } else {
+                View.GONE
+            }
+            setOnClickListener {
+                interactor.onNewTabTapped(isPrivateModeSelected)
+            }
+        }
+
+        fabView.new_tab_button.apply {
+            visibility = if (hasAccessibilityEnabled) {
```
Comment (boek) [inline app/src/main/java/org/mozilla/fenix/tabtray/TabTrayView.kt:162]: Same as above
