### PR TITLE
Closes #19182: Close Tabs Tray when sharing completes

### LINKED ISSUE #19182: [Bug]No snackbar is displayed when sharing tabs from Tabs Tray
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
1. Open 2-3 tabs.
2. Open Tabs Tray.
3. Open the 3dot menu -> Share all tabs/ or Select Tabs.
4. Send the tabs to the connected devices.

### Expected behavior
A snackbar is displayed informing the user that the tabs were sent.

### Actual behavior
Nothing is displayed.

### Device information
* Device vendor / model and Android version: Huawei MediaPad M2	(Android 5.1.1), LG G7 Fit (Android 8.1).
* Firefox for Android version: ? (go to Settings -> About Firefox), Nightly 4/22, 89.0.0-beta.1

### PR DESCRIPTION
**Pull request by rocketsroger**
### Pull Request checklist

- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

**Comment by rocketsroger** [comment]
This requires https://github.com/mozilla-mobile/fenix/pull/19958 before merging.
Also I'm open on ways to test this.  So far I spent about 3 hours and have not find a good test for this change.

File: app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayFragment.kt [hunk 1]
```diff
@@ -263,6 +265,10 @@ class TabsTrayFragment : AppCompatDialogFragment() {
             owner = this,
             view = view
         )
+
+        setFragmentResultListener(ShareFragment.RESULT_KEY) { _, _ ->
```
Comment (jonalmeida) [inline app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayFragment.kt:269]: Nice!

**Review by jonalmeida — APPROVED** [review]
Looks good! If possible, let's add a test?
