### PR TITLE
For #28069 fix disabled openPocketStoryItemTest UI test

### LINKED ISSUE #28069: Intermittent UI test failure - openPocketStoryItemTest
### Firebase Test Run:
Failed 2x and blocks AC updates:
https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7391334427647248198/executions/bs.770e51240f7d101d/videos
### Stacktrace:
`
java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:87)
at org.junit.Assert.assertTrue(Assert.java:42)
at org.junit.Assert.assertTrue(Assert.java:53)
at org.mozilla.fenix.ui.robots.BrowserRobot.verifyUrl(BrowserRobot.kt:72)
at org.mozilla.fenix.ui.HomeScreenTest$openPocketStoryItemTest$4.invoke(HomeScreenTest.kt:276)
at org.mozilla.fenix.ui.HomeScreenTest$openPocketStoryItemTest$4.invoke(HomeScreenTest.kt:275)
at org.mozilla.fenix.ui.robots.HomeScreenRobot$Transition.clickPocketStoryItem(HomeScreenRobot.kt:700)
at org.mozilla.fenix.ui.HomeScreenTest.openPocketStoryItemTest(HomeScreenTest.kt:275)`
### Build: 
12/5/2022

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22092)

### PR DESCRIPTION
**Pull request by AndiAJ**
For #28069 fix disabled `openPocketStoryItemTest` UI test ✅ successfully passed 100x on Firebase.

### Pull Request checklist

- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### QA

- [ ] **QA Needed**

### To download an APK when reviewing a PR (after all CI tasks finished running):
1. Click on `Checks` at the top of the PR page.
2. Click on the `firefoxci-taskcluster` group on the left to expand all tasks.
3. Click on the `build-debug` task.
4. Click on `View task in Taskcluster` in the new `DETAILS` section.
5. The APK links should be on the right side of the screen, named for each CPU architecture.

### GitHub Automation
Fixes #28069

### CODE REVIEW

File: app/src/androidTest/java/org/mozilla/fenix/helpers/Constants.kt [hunk 1]
```diff
@@ -18,6 +18,7 @@ object Constants {
     }
 
     const val SPEECH_RECOGNITION = "android.speech.action.RECOGNIZE_SPEECH"
+    const val POCKET_STORIES_UTM_VALUE = "pocket-newtab-android"
```
Comment (AaronMT) [inline app/src/androidTest/java/org/mozilla/fenix/helpers/Constants.kt:21]: @MozillaNoah Hey Noah, is this likely ever to change? The test below verifies on click of a pocket story item that the URL is that value

**Review by AaronMT — APPROVED** [review]

File: app/src/androidTest/java/org/mozilla/fenix/helpers/Constants.kt (hunk 1 above)
Comment (AndiAJ) [reply app/src/androidTest/java/org/mozilla/fenix/helpers/Constants.kt:21]: @Mugurell, I know you were heavily involved in the "Pocket" implementation, could you please share your thoughts ? ☺️

Comment (Mugurell) [reply app/src/androidTest/java/org/mozilla/fenix/helpers/Constants.kt:21]: I understand the test was failing because it is indeed not guaranteed that the url will contain the publisher's name.
As a workaround to still test some data about the clicked recommended story Andi added a verification of the utm parameter. 
The utm parameter is part of the contract with Pocket and allows them to easily identify and attribute visits - https://github.com/mozilla-mobile/fenix/issues/21599 and so it's important to ensure that is has the right value and is always correctly added by the app.
A small improvement can be made in the proposed change: test the value as an uri parameter: 
- either by converting the string url to an Uri instance and then use something like `url.queryParameter("utm_source").equals("pocket-newtab-android")` 
- either by just concatenating the expected string - `?utm_source=pocket-newtab-android` and then checking if the url contains that.

**Comment by AndiAJ** [comment]
Thanks @Mugurell for the suggestions, made the changes and successfully passed 50x on Firebase.
