### PR TITLE
Close #25919: Move UpdateFirstFrameDrawn to RecyclerView.onLayoutCompleted

### LINKED ISSUE #25919: 533-1279ms regression + bimodal reintroduced for cold main start up (6/28)
We see a regression of 533ms from the 6/27 nightly to the 6/28 nightly:

image

That increases if we look at 6/27 to 6/29 to 1279ms. We also see a regression on the A51 (but it is still a WIP) so we can probably reproduce this on devices that aren't just the Moto G5.

Bimodal behavior also appears starting in 6/28. **The fast case appears to not have regression but the slow case is where we see the regression.**  Here's 6/27 (before):
image

And 6/28:
image

6/29 for completeness:
image

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20930)

### PR DESCRIPTION
**Pull request by jonalmeida**
The longer investigation that led to this patch can be found 
here: https://github.com/mozilla-mobile/fenix/issues/25919#issuecomment-1226151432

As part of a preventitive measure for home page regression loading, we
fixed the UpdateFirstFrameDrawn call to happen after the first layout in
the main RecyclerView is completed. In addition, we also make pocket
aware of this flag so that it renders itself after the first layout.

This helps prioritize current & future features that are visible first
to render before those that are off screen.

Co-authored-by: Arturo Mejia

### Pull Request checklist

- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [x] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### QA

- [x] **QA Needed**

### To download an APK when reviewing a PR (after all CI tasks finished running):
1. Click on `Checks` at the top of the PR page.
2. Click on the `firefoxci-taskcluster` group on the left to expand all tasks.
3. Click on the `build-debug` task.
4. Click on `View task in Taskcluster` in the new `DETAILS` section.
5. The APK links should be on the right side of the screen, named for each CPU architecture.

### GitHub Automation
Fixes #25919

### CODE REVIEW

File: app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlView.kt [hunk 1]
```diff
@@ -40,7 +41,8 @@ internal fun normalModeAdapterItems(
     showRecentTab: Boolean,
     showRecentSyncedTab: Boolean,
     recentVisits: List<RecentlyVisitedItem>,
-    pocketStories: List<PocketStory>
+    pocketStories: List<PocketStory>,
+    firstFrameDrawn: Boolean = false,
```
Comment (MozillaNoah) [inline app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlView.kt:45]: outside of the updated test, is there ever a scenario where `firstFrameDrawn` is passed-in as `true`?

File: app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlView.kt [hunk 2]
```diff
@@ -85,7 +87,11 @@ internal fun normalModeAdapterItems(
         showCollections(collections, expandedCollections, items)
     }
 
-    if (settings.showPocketRecommendationsFeature && pocketStories.isNotEmpty()) {
+    // When Pocket is enabled and the initial layout of the app is done, then we can add these items
+    // to render to the home screen.
+    // This is only useful while we have a RecyclerView + Compose implementation. We can remove this
+    // when we switch to a Compose-only home screen.
```
Comment (MozillaNoah) [inline app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlView.kt:93]: love comments like these

File: app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlView.kt (hunk 1 above)
Comment (jonalmeida) [reply app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlView.kt:45]: Yeah, below in the `LinearLayoutManager.onLayoutCompleted` call is when we want this flag to be flipped.

Comment (MozillaNoah) [reply app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlView.kt:45]: I saw that's where the flag is being updated, I just wasn't sure if that flag flip then triggered something in `SessionControlView` or if `SessionControlView` was ever re-initialized with `firstFrameDrawn` as true.

Comment (jonalmeida) [reply app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlView.kt:45]: Ah, I think I understand your comment now. In the `HomeFragment`, we observe the entire `AppState` for changes [here](https://github.com/mozilla-mobile/fenix/blob/f8f8b4f8132366e5b40ef1687d696e4d5a025776/app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt#L452-L455) and calls the `sessionControlView.update` method on any state changes which in return re-evaluates the `normalModeAdapterItems` and therefore the `firstFrameDrawn` flag.

**Comment by jonalmeida** [comment]
Added the do not land label for now so we can land this on Monday.

**Review by csadilek — APPROVED** [review]
Thanks for walking me through and all your work investigating this tricky issue @jonalmeida @Amejia481 @MatthewTighe.

I think differentiating primary and secondary content on the home screen and not rendering everything at once, especially the parts that are likely below the fold, seems really good to me. We can always make this more flexible later!
