### PR TITLE
For #26759 - Crash fix for UnsupportedOperationException

### LINKED ISSUE #26759: [Bug]: Firefox Nightly crashes when opening a new tab after accessing about:config
### Steps to reproduce

1. Open the Firefox Nightly browser
2. Type "about:config" in the address bar
3. Press "Enter"
4. Open a new tab
5. Observe the behaviour

### Expected behaviour

New tab is opened.

### Actual behaviour

The browser crashes.

### Device name

ONEPLUS A6000

### Android version

OxygenOS version 11.1.2.2

### Firefox release type

Firefox Nightly

### Firefox version

106.0a1-20220831093258

### Device logs

4a9be630-bb09-44dd-808c-af4183081797
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
----
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:641)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
	... 1 more
Caused by: mozilla.components.lib.state.StoreException: Exception while reducing state
	at mozilla.components.lib.state.Store$exceptionHandler$1$1.run(Store.kt:1)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:233)
	at android.app.ActivityThread.main(ActivityThread.java:8068)
	... 3 more
Caused by: java.lang.UnsupportedOperationException: This isn't a hierarchical URI.
	at android.net.Uri.getQueryParameterNames(Uri.java:1605)
	at org.mozilla.fenix.ext.UriKt.containsQueryParameters(Uri.kt:4)
	at org.mozilla.fenix.home.blocklist.BlocklistHandler.filterContileRecentTab(BlocklistHandler.kt:8)
	at org.mozilla.fenix.home.blocklist.BlocklistMiddleware.invoke(BlocklistMiddleware.kt:20)
	at mozilla.components.lib.state.internal.ReducerChainBuilder$build$1$1.invoke(ReducerChainBuilder.kt:3)
	at mozilla.components.lib.state.internal.ReducerChainBuilder$build$threadCheck$1.invoke(ReducerChainBuilder.kt:10)
	at mozilla.components.lib.state.internal.ReducerChainBuilder$build$1$1.invoke(ReducerChainBuilder.kt:3)
	at mozilla.components.lib.state.Store$dispatch$1.invokeSuspend(Store.kt:4)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:4)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)

### Additional information

Notes:
- Video provided: https://gifyu.com/image/SwmMO
- Reproducible regardless of what words are typed as long as it is in the same format (eg. "hello:world" )
- Unable to access the browser until Storage & Cache is cleared

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21444)

### PR DESCRIPTION
**Pull request by sarah541**
Uri#containsQueryParameters() throws an exception
on opaque URIs (e.g. [about:config](url)).

> "A URI is opaque if, and only if, it is absolute and its scheme-specific part does not begin with a slash character ('/'). An opaque URI has a scheme, a scheme-specific part, and possibly a fragment; all other components are undefined."

### Pull Request checklist

- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### QA

- [x] **QA Needed**

### To download an APK when reviewing a PR (after all CI tasks finished running):
1. Click on `Checks` at the top of the PR page.
2. Click on the `firefoxci-taskcluster` group on the left to expand all tasks.
3. Click on the `build-debug` task.
4. Click on `View task in Taskcluster` in the new `DETAILS` section.
5. The APK links should be on the right side of the screen, named for each CPU architecture.

### GitHub Automation
Fixes #26759

### CODE REVIEW

File: app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt [hunk 1]
```diff
@@ -435,7 +435,8 @@ class HomeFragment : Fragment() {
             totalSites = settings.topSitesMaxLimit,
             frecencyConfig = TopSitesFrecencyConfig(
                 FrecencyThresholdOption.SKIP_ONE_TIME_PAGES
-            ) { !Uri.parse(it.url).containsQueryParameters(settings.frecencyFilterQuery) },
+            ) { !Uri.parse(it.url).isOpaque &&
+                    !Uri.parse(it.url).containsQueryParameters(settings.frecencyFilterQuery) },
```
Comment (MozillaNoah) [inline app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt:439]: alternatively, you could add the check to the `containsQueryParameters` extension function

> fun Uri.containsQueryParameters(searchParameters: String): Boolean {
    if (searchParameters.isBlank() || !this.isOpaque) {
        return false
    }

**Review by MozillaNoah — APPROVED** [review]
LGTM. Let's also add a small test to `UriTest` that covers a couple opaque URLs, like `about:config`.

**Comment by mcarare** [comment]
@mergify backport releases_v105.0.0
