### PR TITLE
Fixes #25545: wait to draw Pocket until after first frame

### LINKED ISSUE #25545: Task continuity: ~800ms regression on 50% of COLD MAIN first frame start ups (5/28 regression with bimodal behavior)
_see https://github.com/mozilla-mobile/fenix/issues/22144 for bimodal results in COLD VIEW, which is very likely unrelated_

For our COLD MAIN first frame start up test, our replicates are usually scattered evenly (I verified this behavior on the Nighlies 4/29, 5/15, 5/17, 5/18, 5/19, 5/21, and 5/25-5/27). For example, here is the Nightly 5/27 performance test:
Figure_1

However, Nightly 5/28 introduces bimodal results:
Figure_12png

I verified:
- this bimodal behavior continues on 5/29.
- From 5/30-6/1, we don't see bimodal behavior. Instead, we see a major regression such that all replicates are much longer
- We return to bimodal behavior from 6/2-6/5, where our test results end

**Bimodal results are undesirable** because:
- users are experiencing fast start ups roughly half the time and slower start ups the other half. Why not figure out how to get users the fast start up all the time?
- it can cause false positive regressions making it difficult to identify true regressions (because if we get each of a low result and a high result roughly 50% of the time like in this bug, the performance test result will jump between each regularly since we use the median)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20662)

### PR DESCRIPTION
**Pull request by MatthewTighe**
This PR resolves this perf regression in two ways:

- Pocket content was rendering too early, regularly increasing the time to layout the home screen. This forces pocket content to wait until after the initial render pass
- Additionally, pocket content would often load first. Since the content is focusable, the home screen RecyclerView would automatically scroll the content to the center. This was mostly unrelated, but the perf fix caused this behavior to become consistent.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

File: app/src/main/java/org/mozilla/fenix/home/pocket/PocketCategoriesViewHolder.kt [hunk 1]
```diff
@@ -49,11 +49,17 @@ class PocketCategoriesViewHolder(
...
+            .observeAsComposableState { state -> state.firstFrameDrawn }.value ?: false
+
         val categories = components.appStore
             .observeAsComposableState { state -> state.pocketStoriesCategories }.value
         val categoriesSelections = components.appStore
             .observeAsComposableState { state -> state.pocketStoriesCategoriesSelections }.value
 
+        // Perceived performance can be improved by waiting to draw pocket content until after the
+        // first frame is drawn. See https://github.com/mozilla-mobile/fenix/issues/25545 for details.
+        if (!homeScreenReady) return
```
Comment (MozillaNoah) [inline app/src/main/java/org/mozilla/fenix/home/pocket/PocketCategoriesViewHolder.kt:62]: why not instead just wrap the `Column` with this `if`?

File: app/src/main/java/org/mozilla/fenix/home/pocket/PocketStoriesViewHolder.kt [hunk 2]
```diff
@@ -52,9 +52,15 @@ class PocketStoriesViewHolder(
...
 
+        val homeScreenReady = components.appStore
+            .observeAsComposableState { state -> state.firstFrameDrawn }.value ?: false
+
         val stories = components.appStore
             .observeAsComposableState { state -> state.pocketStories }.value
 
+        // Perceived performance can be improved by waiting to draw pocket content until after the
+        // first frame is drawn. See https://github.com/mozilla-mobile/fenix/issues/25545 for details.
+        if (!homeScreenReady) return
```
Comment (MozillaNoah) [inline app/src/main/java/org/mozilla/fenix/home/pocket/PocketStoriesViewHolder.kt:63]: same here

File: app/src/main/res/layout/top_placeholder_item.xml [hunk 3]
```diff
@@ -2,6 +2,10 @@
...
    - License, v. 2.0. If a copy of the MPL was not distributed with this
    - file, You can obtain one at http://mozilla.org/MPL/2.0/. -->
+
+<!-- RecyclerViews will focus the first element that is focusable. This prevents views below
+the top from being scrolled to unintentionally. -->
 <View xmlns:android="http://schemas.android.com/apk/res/android"
     android:layout_width="match_parent"
-    android:layout_height="0dp"/>
+    android:layout_height="0dp"
+    android:focusable="true" />
```
Comment (MozillaNoah) [inline app/src/main/res/layout/top_placeholder_item.xml:11]: would this be a short term stop-gap until the Homepage is all Compose, basically?

Comment (MatthewTighe) [reply app/src/main/res/layout/top_placeholder_item.xml:11]: There was a bit of discussion during this process about how best to handle this in general. One suggestion, for example, was to use an invisible skeleton of roughly the same size as the final content. We could then wait until after first frame to populate the skeleton with content.

I don't know off the top of my head if this issue will reappear when the whole screen is compose. If items in large `LazyList`s are focused automatically we may have to do something similar.

File: app/src/main/java/org/mozilla/fenix/home/pocket/PocketCategoriesViewHolder.kt (hunk 1 above)
Comment (MatthewTighe) [reply app/src/main/java/org/mozilla/fenix/home/pocket/PocketCategoriesViewHolder.kt:62]: Less indentation I guess? I've usually just prefer early returns, stylistically. There's additionally reasoning for the choice in the other comment, and I think it would be good to keep the two in sync if we decide to change it.

File: app/src/main/java/org/mozilla/fenix/home/pocket/PocketStoriesViewHolder.kt (hunk 2 above)
Comment (MatthewTighe) [reply app/src/main/java/org/mozilla/fenix/home/pocket/PocketStoriesViewHolder.kt:63]: Here, there's additional logic that records telemetry when `stories` has a value. There can definitely be cases where `stories` is usable but we are still waiting for the homescreen to be ready. I don't think we want to record that telemetry until the stories are actually show, based on the code and comments.

**Review by Amejia481 — APPROVED** [review]

File: app/src/main/java/org/mozilla/fenix/home/pocket/PocketCategoriesViewHolder.kt [hunk 4]
```diff
@@ -49,11 +49,17 @@ class PocketCategoriesViewHolder(
...
+        val homeScreenReady = components.appStore
+            .observeAsComposableState { state -> state.firstFrameDrawn }.value ?: false
+
         val categories = components.appStore
             .observeAsComposableState { state -> state.pocketStoriesCategories }.value
         val categoriesSelections = components.appStore
             .observeAsComposableState { state -> state.pocketStoriesCategoriesSelections }.value
 
+        // Perceived performance can be improved by waiting to draw pocket content until after the
+        // first frame is drawn. See https://github.com/mozilla-mobile/fenix/issues/25545 for details.
```
Comment (mcomella) [inline app/src/main/java/org/mozilla/fenix/home/pocket/PocketCategoriesViewHolder.kt:61]: non-blocking: I'd prefer if this comment elaborated on why this issue happens and how this solution addresses the issue because:
1. devs won't necessarily go to the issue even if the information would be useful to them
2. if the solution changes they're not likely to update the issue but they'd update the explanation in a comment
3. there is generally a lot of irrelevant context in issues that make digging for the answers to those two questions challenging.

More generally, I prefer making the source code an elaborate source of truth and leaving the issue tracker as a supplement because the source tends to be more accurate & to-the-point.

File: app/src/main/java/org/mozilla/fenix/home/pocket/PocketStoriesViewHolder.kt [hunk 5]
```diff
@@ -52,9 +52,15 @@ class PocketStoriesViewHolder(
...
         val horizontalPadding = dimensionResource(R.dimen.home_item_horizontal_margin)
 
+        val homeScreenReady = components.appStore
+            .observeAsComposableState { state -> state.firstFrameDrawn }.value ?: false
+
         val stories = components.appStore
             .observeAsComposableState { state -> state.pocketStories }.value
 
+        // Perceived performance can be improved by waiting to draw pocket content until after the
+        // first frame is drawn. See https://github.com/mozilla-mobile/fenix/issues/25545 for details.
```
Comment (mcomella) [inline app/src/main/java/org/mozilla/fenix/home/pocket/PocketStoriesViewHolder.kt:62]: non-blocking: if you take my suggestion above to elaborate, I'd prefer if these two comments point to a central elaboration comment rather than these two comments be duplicated and elaborate

**Review by mcomella — COMMENTED** [review]
The fenix team has ownership of keeping the product performant to meet the product's goals so the performance team (or myself) generally does not need to approve changes for performance unless there is something specific you need our expertise for. As such, I'm going to remove my review request but I happened to skim the review and include a drive-by comment too.
