### PR TITLE
Fix #3886 - Change default device name to show the app name.

### LINKED ISSUE #3886: Default device name should show both app and device name
## Steps to reproduce
1. Install Fenix.
2. Sign into an account.

### Expected behavior
1. ~The default name should be '[app name]' or '[app name] on [device]'~
   - ~e.g. "Firefox Preview" or "Firefox Preview on Pixel 2".~

⚠️ **Update:** 
Verified format: `[user]'s [app name] on device`
 e.g. "Jonathan's Firefox Preview on Pixel 2"

### Actual behavior
1. The default name is '[device] [manufacturer]'.

### Device information

* Android device: Android 9
* Fenix version: 03/07/2019

This seems to be a regression from https://github.com/mozilla-mobile/fenix/issues/3317.

cc: @ryanfeeley

### PR DESCRIPTION
**Pull request by bloslo**
### Pull Request checklist

- [ ] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/fenix/blob/master/CHANGELOG.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### CODE REVIEW

File: app/src/main/java/org/mozilla/fenix/components/BackgroundServices.kt [hunk 1]
```diff
@@ -87,7 +88,7 @@ class BackgroundServices(
         emptyList()
     }
 
-    private val defaultDeviceName = Build.MANUFACTURER + " " + Build.MODEL
+    private val defaultDeviceName = context.getString(R.string.app_name) + " on " + Build.MANUFACTURER + " " + Build.MODEL
```
Comment (jonalmeida) [inline app/src/main/java/org/mozilla/fenix/components/BackgroundServices.kt]: Since we're introducing a string here ("on") we need to make sure that it's being localized properly.

It might make more sense to have a string resource that has placeholders for the template we want. [Here's an example](https://github.com/mozilla-mobile/fenix/blob/master/app/src/main/res/values/strings.xml#L613) of the a string resource that has placeholders; we could add three of them:
1. The application name.
2. The manufacturer.
3. The model number.

Could you also add a comment similar to the other strings resources? It's for our localizers to understand the context of where the string is being used so that it can be translated it correctly.

**Comment by jonalmeida** [comment]
@bloslo It looks like the [CI link](https://tools.taskcluster.net/groups/Nt3WGdypQ8OKhdiWoObLcA/tasks/ByDNIlm-Sm2KXKbP-hP7JA/runs/0/logs/public%2Flogs%2Flive.log) below say that the linter is complaining.

> Ruleset: style - 5min debt
>	MaxLineLength - [defaultDeviceName] at /opt/fenix/app/src/main/java/org/mozilla/fenix/components/BackgroundServices.kt:91:5

Almost there! :)

**Comment by ekager** [comment]
This looks great! Could you rebase and resolve the conflicts? Then we are ready to merge :)

**Comment by boek** [comment]
@bloslo  Woohoo! Thanks for your contribution! 

Since we missed string freeze for 1.1 we're going to hold off on landing this! I'll fix the merge conflicts for you and it should land later this week!
