### PR TITLE
Fixes #24188 - Use app_name for InactiveTabAutoClose message

### LINKED ISSUE #24188: [Bug]: Placeholder displayed instead of product name in Inactive Tabs auto-close prompt
## Prerequisites
Have 20+ Inactive tabs

## Steps to reproduce
1. Open the tabs tray
2. Check the Inactive tabs auto-close prompt is displayed

### Expected behavior
The auto-close prompt should display: "**Firefox** can close tabs you haven’t viewed over the past month."

### Actual behavior
The auto-close prompt should display: "%1$s can close tabs you haven’t viewed over the past month."

### Device information

* Android device: OnePlus A3 (Android 6.0.1)
• Firefox Nightly 100.0a1
• Firefox 99.0.0 Beta 1

### Notes
► Screenshot
image

### PR DESCRIPTION
**Pull request by Alexandru2909**
Used `app_name` for inactive tab auto close dialog message instead of placeholder

inactive

### Pull Request checklist!

- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

**Review by gabrielluong — APPROVED** [review]

File: app/src/main/java/org/mozilla/fenix/tabstray/browser/InactiveTabViewHolder.kt [hunk 1]
```diff
@@ -79,6 +79,14 @@ sealed class InactiveTabViewHolder(itemView: View) : RecyclerView.ViewHolder(ite
 
         init {
             binding.root.context.metrics.track(Event.TabsTrayAutoCloseDialogSeen)
+
+            binding.message.text = with(binding.root.context) {
+                this.getString(
```
Comment (MozillaNoah) [inline app/src/main/java/org/mozilla/fenix/tabstray/browser/InactiveTabViewHolder.kt:84]: nit: since it's within the `with` block, are the two `this` necessary?

**Review by MozillaNoah — APPROVED** [review]
