### PR TITLE
Closes #15816 - Attempt to handle 'allowInPrivate..' pref with detached context

### LINKED ISSUE #15816: IllegalStateException: Fragment AddonsManagementFragment{503ecf9} (312b5ca5-3fc3-40a4-af56-fc4e7592a3db)} not attached t...
https://sentry.prod.mozaws.net/operations/firefox-nightly/issues/8940689/?referrer=github_plugin

```
IllegalStateException: Fragment AddonsManagementFragment{503ecf9} (312b5ca5-3fc3-40a4-af56-fc4e7592a3db)} not attached to a context.
    at org.mozilla.fenix.addons.AddonsManagementFragment$showInstallationDialog$dialog$1.invoke(AddonsManagementFragment.kt:3)
...
(10 additional frame(s) were not displayed)

Fragment AddonsManagementFragment{503ecf9} (312b5ca5-3fc3-40a4-af56-fc4e7592a3db)} not attached to a context.
```

### PR DESCRIPTION
**Pull request by grigoryk**
cc @Amejia481 since you care about addons.

@ekager one more of these lifecycle gone awry things.  

### Pull Request checklist

- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

File: app/src/main/java/org/mozilla/fenix/addons/AddonsManagementFragment.kt [hunk 1]
```diff
@@ -189,7 +197,7 @@ class AddonsManagementFragment : Fragment(R.layout.fragment_add_ons_management)
                 ),
                 onConfirmButtonClicked = { _, allowInPrivateBrowsing ->
                     if (allowInPrivateBrowsing) {
-                        requireContext().components.addonManager.setAddonAllowedInPrivateBrowsing(
+                        weakApplicationContext.get()?.components?.addonManager?.setAddonAllowedInPrivateBrowsing(
```
Comment (Amejia481) [inline app/src/main/java/org/mozilla/fenix/addons/AddonsManagementFragment.kt:200]: I would prefer if we could use [runIfFragmentIsAttached](https://github.com/mozilla-mobile/fenix/blob/ea2bb0df75c407e98618838cf39f90ee8bc421d9/app/src/main/java/org/mozilla/fenix/addons/Extensions.kt#L32) extension function as using `requireActivity()` when the fragment is initialized could cause crashes :)

**Review by Amejia481 — CHANGES_REQUESTED** [review]
Thanks for the patch, left a comment :)

**Review by csadilek — APPROVED** [review]
👍

**Review by Amejia481 — APPROVED** [review]
