### PR TITLE
Issue mozilla-mobile#20637 - Fixed bug causing the tabs tray to scroll to the wrong tab when opened

### LINKED ISSUE #20637: [Bug]: Opening the tabs tray scrolls to the wrong position when inactive tabs are present
### Steps to reproduce

1. Have several active tabs
2. Have several inactive tabs
3. Set tab tray in list view
4. For various active tabs, try the following: open the tab, then open the tab tray and look for the focused tab -the one you just closed

### Expected behaviour

the tab tray should open by making focused tab (last open) visible

### Actual behaviour

See various examples in this video: https://photos.app.goo.gl/X9ACpbTxXa64yb8p8 (please be patient, some pages shown in the video are quite long to load!)

often, the tab tray does not display the focused active tab (either the active tabs are shown but not the focused one, or the inactive tabs are shown)

### Device name

Redmi Note 7

### Android version

Android 9

### Firefox release type

Firefox Nightly

### Firefox version

92.0a1

### Device logs

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by MozillaNoah**
Fixes #20637

### Pull Request checklist

- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

File: app/src/main/java/org/mozilla/fenix/tabstray/browser/NormalBrowserTrayList.kt [hunk 1]
```diff
@@ -23,17 +23,17 @@ import java.util.concurrent.TimeUnit
  */
 const val DEFAULT_ACTIVE_DAYS = 4L
 
+/**
+ * The maximum time from when a tab was created or accessed until it is considered "inactive".
+ */
+val maxActiveTime = TimeUnit.DAYS.toMillis(DEFAULT_ACTIVE_DAYS)
```
Comment (MozillaNoah) [inline app/src/main/java/org/mozilla/fenix/tabstray/browser/NormalBrowserTrayList.kt:29]: I just wasn't sure where to refactor/relocate this to

File: app/src/main/java/org/mozilla/fenix/tabstray/TrayPagerAdapter.kt [hunk 2]
```diff
@@ -53,7 +55,7 @@ class TrayPagerAdapter(
                     itemView,
                     store,
                     interactor,
-                    browserStore.state.normalTabs.indexOf(selectedTab)
+                    browserStore.state.normalTabs.filter { it.isNormalTabActive(maxActiveTime) }.indexOf(selectedTab)
```
Comment (jonalmeida) [inline app/src/main/java/org/mozilla/fenix/tabstray/TrayPagerAdapter.kt:58]: Since we have a single RecyclerView with multiple adapters, our "index" calculation is going to be a bit complicated.

From our last meeting, we need to scroll to the selected tab even if it's in the inactive tab section as well.

So we would need to do something like:
1. Iterate through all adapters
2. Find the adapter with a tab of the matching ID and viewholder type.
3. Convert the relative adapter positive to the final adapter position.
4. Tell the RV to scroll to this new position (because we need to say `RecyclerView.scrollToPosition` and there is no `RecyclerView.Adapter.scrollToPosition`).

This will also aid in solving a scrolling regression when we land other adapters like in 21177.

File: app/src/main/java/org/mozilla/fenix/tabstray/browser/NormalBrowserTrayList.kt (hunk 1 above)
Comment (jonalmeida) [reply app/src/main/java/org/mozilla/fenix/tabstray/browser/NormalBrowserTrayList.kt:29]: For now, this is fine. I think we need to eventually move it somewhere else when the next set of settings land.

File: app/src/main/java/org/mozilla/fenix/tabstray/TrayPagerAdapter.kt (hunk 2 above)
Comment (jonalmeida) [reply app/src/main/java/org/mozilla/fenix/tabstray/TrayPagerAdapter.kt:58]: Spoke offline with Noah, we'll land this change for now and fix the scrolling problem when we land 21177 as well.

**Review by jonalmeida — APPROVED** [review]
