### PR TITLE
For #15083 - Add multi select in recently closed tabs

### LINKED ISSUE #15083: Add multi select in Recently closed
## Steps to reproduce
Go to history/recently closed
Try to long press to multi select 

### Expected behavior
Multi select overlay appears
### Actual behavior
Nothing
### Device information

* Android device: Asus Zenfone
* Fenix version: Nightly

### PR DESCRIPTION
**Pull request by ZianeA**
Fixes #15083

https://user-images.githubusercontent.com/14791787/113617821-bd270a80-964e-11eb-9ced-e3203829d71b.mp4

This also fixes a strange behavior in the animation when deleting items. Turns out that this was happening because the Recyclerview's layout_height was set to wrap_content. The bookmarks screen presents the same issue, I'll try to fix it in another PR.

### Pull Request checklist

- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

File: app/src/main/java/org/mozilla/fenix/library/recentlyclosed/RecentlyClosedAdapter.kt [hunk 1]
```diff
@@ -31,6 +36,38 @@ class RecentlyClosedAdapter(
             oldItem.id == newItem.id
 
         override fun areContentsTheSame(oldItem: RecoverableTab, newItem: RecoverableTab) =
-            oldItem.id == newItem.id
+            oldItem == newItem
+    }
+
+    fun updateData(tabs: List<RecoverableTab>, selectedTabs: Set<RecoverableTab>) {
```
Comment (jonalmeida) [inline app/src/main/java/org/mozilla/fenix/library/recentlyclosed/RecentlyClosedAdapter.kt:42]: nit: Let's organize the methods so that private bindings are together, overridden methods are together, and private methods are together.

File: app/src/main/java/org/mozilla/fenix/library/recentlyclosed/RecentlyClosedController.kt [hunk 2]
```diff
@@ -22,30 +22,55 @@ import org.mozilla.fenix.components.FenixSnackbar
...
     private val tabsUseCases: TabsUseCases,
     private val resources: Resources,
     private val snackbar: FenixSnackbar,
     private val clipboardManager: ClipboardManager,
     private val activity: HomeActivity,
     private val openToBrowser: (item: RecoverableTab, mode: BrowsingMode?) -> Unit
 ) : RecentlyClosedController {
-    override fun handleOpen(item: RecoverableTab, mode: BrowsingMode?) {
-        openToBrowser(item, mode)
+    override fun handleOpen(tab: RecoverableTab, mode: BrowsingMode?) = openToBrowser(tab, mode)
```
Comment (jonalmeida) [inline app/src/main/java/org/mozilla/fenix/library/recentlyclosed/RecentlyClosedController.kt:50]: Let's put the brackets back onto this method if even though it's a single line method.

File: app/src/main/java/org/mozilla/fenix/library/recentlyclosed/RecentlyClosedFragment.kt [hunk 3]
```diff
@@ -30,33 +32,63 @@ import org.mozilla.fenix.components.FenixSnackbar
...
         super.onResume()
         showToolbar(getString(R.string.library_recently_closed_tabs))
     }
 
     override fun onCreateOptionsMenu(menu: Menu, inflater: MenuInflater) {
-        inflater.inflate(R.menu.library_menu, menu)
+        if (recentlyClosedFragmentStore.state.selectedTabs.isNotEmpty()) {
+            inflater.inflate(R.menu.history_select_multi, menu)
+            menu.findItem(R.id.delete_history_multi_select)?.title =
+                SpannableString(getString(R.string.bookmark_menu_delete_button)).apply {
```
Comment (jonalmeida) [inline app/src/main/java/org/mozilla/fenix/library/recentlyclosed/RecentlyClosedFragment.kt:58]: We should introduce a separate string for this instead of re-using the bookmarks one.

File: app/src/main/java/org/mozilla/fenix/library/recentlyclosed/RecentlyClosedFragmentStore.kt [hunk 4]
```diff
@@ -41,5 +45,6 @@ private fun recentlyClosedStateReducer(
 ): RecentlyClosedFragmentState {
     return when (action) {
         is RecentlyClosedFragmentAction.Change -> state.copy(items = action.list)
+        is RecentlyClosedFragmentAction.ChangeSelection -> state.copy(selectedTabs = action.tabs)
```
Comment (jonalmeida) [inline app/src/main/java/org/mozilla/fenix/library/recentlyclosed/RecentlyClosedFragmentStore.kt:48]: Like the other implementations of the selection holder, let's add the `Select/Deselect` logic to our store instead of the controller. Consistency should make it easier to refactor if we decide to update the way this logic works.

Have a look at either the Bookmarks/History/Downloads/TabsTray stores for how multi-select was implemented.

File: app/src/main/java/org/mozilla/fenix/library/recentlyclosed/RecentlyClosedAdapter.kt [hunk 5]
```diff
@@ -9,17 +9,22 @@ import android.view.ViewGroup
 import androidx.recyclerview.widget.DiffUtil
 import androidx.recyclerview.widget.ListAdapter
 import mozilla.components.browser.state.state.recover.RecoverableTab
+import org.mozilla.fenix.library.SelectionHolder
```
Comment (jonalmeida) [inline app/src/main/java/org/mozilla/fenix/library/recentlyclosed/RecentlyClosedAdapter.kt:12]: One thing you will realise, is that we've moved the SelectionHolder and SelectionInteractor to a higher package namespace in-order to re-use it in other components like tabs tray. Let's update these references.

**Review by jonalmeida — CHANGES_REQUESTED** [review]
This looks great, brilliant work! I've left some review comments below how we can align the changes here with the selection implementation to our other library items.

File: app/src/main/java/org/mozilla/fenix/library/recentlyclosed/RecentlyClosedAdapter.kt [hunk 6]
```diff
@@ -31,6 +36,38 @@ class RecentlyClosedAdapter(
...
+            }
+        }
+
+        submitList(tabs)
+    }
+
+    override val selectedItems: Set<RecoverableTab>
+        get() = selectedTabs
+
+    private fun toggledMultiSelectMode(
```
[the remark this answers is not in the document]
Comment (ZianeA) [reply app/src/main/java/org/mozilla/fenix/library/recentlyclosed/RecentlyClosedAdapter.kt:61]: I am not sure that inMultiSelectModethe reflects what the function represents. This function is supposed to return true if the selection mode has been switched from on to off or the other way around. In other words, it should return true only if we have just entered or left the selection mode and return false if the selection mode has not changed.

[the remark this answers is not in the document]
Comment (jonalmeida) [reply app/src/main/java/org/mozilla/fenix/library/recentlyclosed/RecentlyClosedAdapter.kt:61]: Hmm.. maybe something changed in your local branch that I can't see?

This method only has this state check which is why I recommended the renaming:
```kotlin
currentlySelectedTabs.isEmpty() && selectedTabs.isNotEmpty() || currentlySelectedTabs.isNotEmpty() && selectedTabs.isEmpty()
```

[the remark this answers is not in the document]
Comment (ZianeA) [reply app/src/main/java/org/mozilla/fenix/library/recentlyclosed/RecentlyClosedAdapter.kt:61]: Checking if we are in multi-selection mode would look like this:
`selectedTabs.isNotEmpty()`

However, the function is doing more:

```
// This checks if we have entered the multi-selection mode
currentlySelectedTabs.isEmpty() && selectedTabs.isNotEmpty()

// This Checks if we have left the multi-selection mode
currentlySelectedTabs.isNotEmpty() && selectedTabs.isEmpty()
```

The parameters names are not great, maybe I should rename them to this:
currentlySelectedTabs -> currentSelection
selectedTabs -> newSelection

Alternatively, I can greatly simplify the logic by updating all the items (there can only be 10 items in total) whenever the selection changes:

```
fun updateData(tabs: List<RecoverableTab>, selectedTabs: Set<RecoverableTab>) {
        this.selectedTabs = selectedTabs
        notifyItemRangeChanged(0, tabs.size)
        submitList(tabs)
 }
```

[the remark this answers is not in the document]
Comment (jonalmeida) [reply app/src/main/java/org/mozilla/fenix/library/recentlyclosed/RecentlyClosedAdapter.kt:61]: Sure, that works too. :)

File: app/src/main/java/org/mozilla/fenix/library/recentlyclosed/RecentlyClosedFragment.kt [hunk 7]
```diff
@@ -30,33 +32,63 @@ import org.mozilla.fenix.components.FenixSnackbar
...
+    private lateinit var recentlyClosedController: RecentlyClosedController
 
     override fun onResume() {
         super.onResume()
         showToolbar(getString(R.string.library_recently_closed_tabs))
     }
 
     override fun onCreateOptionsMenu(menu: Menu, inflater: MenuInflater) {
-        inflater.inflate(R.menu.library_menu, menu)
+        if (recentlyClosedFragmentStore.state.selectedTabs.isNotEmpty()) {
```
Comment (jonalmeida) [inline app/src/main/java/org/mozilla/fenix/library/recentlyclosed/RecentlyClosedFragment.kt:55]: Sorry, I must have missed this in the previous iteration.

I don't think we need to add a menu here since the parent `LibraryPageFragment` handles the overlay that shows up with the menu built in.

In fact, I think we can entirely remove `onCreateOptionsMenu` and `onOptionsItemSelected` since that pattern is inconsistent with our other "library" views.

File: app/src/main/java/org/mozilla/fenix/library/recentlyclosed/RecentlyClosedFragmentView.kt [hunk 8]
```diff
@@ -57,11 +59,11 @@ interface RecentlyClosedInteractor {
...
 
     /**
-     * Deletes one recently closed tab item.
+     * Called when recently closed tab is selected for deletion.
      *
-     * @param tab the recently closed tab item to delete.
+     * @param tab the recently closed tab to delete.
      */
-    fun onDeleteOne(tab: RecoverableTab)
+    fun onDelete(tab: RecoverableTab)
```
Comment (jonalmeida) [inline app/src/main/java/org/mozilla/fenix/library/recentlyclosed/RecentlyClosedFragmentView.kt:66]: Excellent clean up! ✨

File: app/src/main/res/layout/component_recently_closed.xml [hunk 9]
```diff
@@ -18,7 +18,8 @@
     <androidx.recyclerview.widget.RecyclerView
         android:id="@+id/recently_closed_list"
         android:layout_width="match_parent"
-        android:layout_height="wrap_content"
+        android:layout_height="0dp"
+        app:layout_constraintBottom_toBottomOf="parent"
```
Comment (jonalmeida) [inline app/src/main/res/layout/component_recently_closed.xml:22]: I was just wondering if was too much to ask to fix this issue since this PR is already in this area. 😄

**Review by jonalmeida — COMMENTED** [review]
This looks great! I left one comment that I think we can address before we land this.

File: app/src/main/java/org/mozilla/fenix/library/recentlyclosed/RecentlyClosedFragment.kt (hunk 7 above)
Comment (ZianeA) [reply app/src/main/java/org/mozilla/fenix/library/recentlyclosed/RecentlyClosedFragment.kt:55]: I tried to remove the `onCreateOptionsMenu` and `onOptionsItemSelected` methods, but it didn't work. I have checked `LibraryPageFragment`, from what I can see it doesn't seem to handle the options menu. I also looked at `BookmakrFragment`, `DownloadFragment`, `HistoryFragment` and they all override the two aforementioned methods. 

On the other hand, the `LibraryPageView` does handle updating the toolbar color in selection mode.

File: app/src/main/res/layout/component_recently_closed.xml (hunk 9 above)
Comment (ZianeA) [reply app/src/main/res/layout/component_recently_closed.xml:22]: Of course! Are you referring to the weird animation when deleting items in the **bookmark** screen?

File: app/src/main/java/org/mozilla/fenix/library/recentlyclosed/RecentlyClosedFragment.kt (hunk 7 above)
Comment (jonalmeida) [reply app/src/main/java/org/mozilla/fenix/library/recentlyclosed/RecentlyClosedFragment.kt:55]: You're right, it looks like the 'history' view is the one that is inconsistent; that's a separate issue then. 👌

File: app/src/main/res/layout/component_recently_closed.xml (hunk 9 above)
Comment (jonalmeida) [reply app/src/main/res/layout/component_recently_closed.xml:22]: I think this change solves the problem I was seeing with the bottom RecyclerView cutting off the overscroll animation. 🙂 

Thanks!

**Comment by jonalmeida** [comment]
Looks great! If you could squash these commits, I'll run CI on it next. :)

**Comment by jonalmeida** [comment]
In case you have trouble finding the results of the `detekt` failures from CI:

```
981 kotlin files were analyzed.
/home/runner/work/fenix/fenix/app/src/main/java/org/mozilla/fenix/library/recentlyclosed/RecentlyClosedController.kt - 50min debt
	TooManyFunctions - 12/11 - [RecentlyClosedController] at /home/runner/work/fenix/fenix/app/src/main/java/org/mozilla/fenix/library/recentlyclosed/RecentlyClosedController.kt:24:11
	TooManyFunctions - 12/11 - [DefaultRecentlyClosedController] at /home/runner/work/fenix/fenix/app/src/main/java/org/mozilla/fenix/library/recentlyclosed/RecentlyClosedController.kt:39:7
	MozillaNavigateCheck - [handleNavigateToHistory] at /home/runner/work/fenix/fenix/app/src/main/java/org/mozilla/fenix/library/recentlyclosed/RecentlyClosedController.kt:77:23

Overall debt: 50min

MozillaNavigateCheck:
    /home/runner/work/fenix/fenix/app/src/main/java/org/mozilla/fenix/library/recentlyclosed/RecentlyClosedController.kt
    If you named a method `navigate`, please rename it to something a bitmore specific such as `navigateTo...`. However, if you are trying to invoke the Android NavController.navigateplease use `org.mozilla.fenix.ext.NavController.navigateBlockingForAsyncNavGraph`instead. Because using `navigate` directly in the code can lead to the NavGraph not being loadedsince it relies on a blocking call done in `navigateBlockingForAsyncNavGraph`.
```
I think we can suppress the `TooManyFunctions` one since I can't see any quick alternative now that would work for this patch.

File: app/src/main/res/layout/component_recently_closed.xml (hunk 9 above)
Comment (ZianeA) [reply app/src/main/res/layout/component_recently_closed.xml:22]: I hadn't even noticed the over scroll problem. I'm glad this solves it. 

However, I was referring to a different problem. It's very subtle, but notice how the last item disappears and reappears when the second-to-last item is removed. 

https://user-images.githubusercontent.com/14791787/119891857-62fd4400-bf31-11eb-8a38-0e26a35e7868.mp4

This is the expected behavior:

https://user-images.githubusercontent.com/14791787/119891754-44974880-bf31-11eb-9004-923d5fcdd968.mp4

Comment (jonalmeida) [reply app/src/main/res/layout/component_recently_closed.xml:22]: I think this is the cause of `notifyItemRangeChanged`. Using `submitList` should be enough with the `ListAdapter` to know and calculate which items to animate. Nice catch!

**Comment by jonalmeida** [comment]
@ZianeA Just the detekt warnings above that need to be addressed. 👌

File: app/src/main/res/layout/component_recently_closed.xml (hunk 9 above)
Comment (ZianeA) [reply app/src/main/res/layout/component_recently_closed.xml:22]: This problem was actually caused by the fact that the Recyclerview height was set to wrap_content. The bookmark screen also has this problem.

Comment (jonalmeida) [reply app/src/main/res/layout/component_recently_closed.xml:22]: Fair point! Let's remove the extra notify though, it's definitely doing double work there.

From the [`submitList`](https://developer.android.com/reference/androidx/recyclerview/widget/ListAdapter#submitList(java.util.List%3CT%3E)) docs you can see that they do the notifying for you:

> Submits a new list to be diffed, and displayed.
> If a list is already being displayed, a diff will be computed on a background thread, which will dispatch Adapter.notifyItem events on the main thread.

**Comment by jonalmeida** [comment]
@ZianeA 

We're still seeing detekt lint failures. Let me know if you need help with fixing them:

```
 983 kotlin files were analyzed.
/home/runner/work/fenix/fenix/app/src/main/java/org/mozilla/fenix/library/recentlyclosed/RecentlyClosedController.kt - 40min debt
	TooManyFunctions - 12/11 - [RecentlyClosedController] at /home/runner/work/fenix/fenix/app/src/main/java/org/mozilla/fenix/library/recentlyclosed/RecentlyClosedController.kt:24:11
	TooManyFunctions - 12/11 - [DefaultRecentlyClosedController] at /home/runner/work/fenix/fenix/app/src/main/java/org/mozilla/fenix/library/recentlyclosed/RecentlyClosedController.kt:39:7

Overall debt: 40min

```

File: app/src/main/res/layout/component_recently_closed.xml (hunk 9 above)
Comment (ZianeA) [reply app/src/main/res/layout/component_recently_closed.xml:22]: Diff only checks the submitted list of `RecoverableTab`s. It does not, however, check the list of selected tabs for changes. Therefore, notifyItemRangeChanged must be called to update the RecyclerView whenever the selection has changed. 

For this to work with diff, the selection must be integrated into the `RecoverableTab` model, for example by adding an `isSelected` flag.

But, as you mentioned, it's still doing double work.

Comment (jonalmeida) [reply app/src/main/res/layout/component_recently_closed.xml:22]: Hmm yeah, that's a good point. Thank you for clarifying that for me. :)

**Comment by ZianeA** [comment]
@jonalmeida I'm not sure how to fix the detekt lint failures :sweat:

**Comment by jonalmeida** [comment]
No worries! I think you can follow my comment above (https://github.com/mozilla-mobile/fenix/pull/18803#issuecomment-849916887) to just suppress the warning with a patch like this:

```diff
diff --git a/app/src/main/java/org/mozilla/fenix/library/recentlyclosed/RecentlyClosedController.kt b/app/src/main/java/org/mozilla/fenix/library/recentlyclosed/RecentlyClosedController.kt
index 47f1b2935..7cb442567 100644
--- a/app/src/main/java/org/mozilla/fenix/library/recentlyclosed/RecentlyClosedController.kt
+++ b/app/src/main/java/org/mozilla/fenix/library/recentlyclosed/RecentlyClosedController.kt
@@ -21,6 +21,7 @@ import org.mozilla.fenix.browser.browsingmode.BrowsingMode
 import org.mozilla.fenix.components.FenixSnackbar
 import org.mozilla.fenix.ext.navigateBlockingForAsyncNavGraph

+@Suppress("TooManyFunctions")
 interface RecentlyClosedController {
     fun handleOpen(item: RecoverableTab, mode: BrowsingMode? = null)
     fun handleDeleteOne(tab: RecoverableTab)
@@ -30,6 +31,7 @@ interface RecentlyClosedController {
     fun handleRestore(item: RecoverableTab)
 }

+@Suppress("TooManyFunctions")
 class DefaultRecentlyClosedController(
     private val navController: NavController,
     private val store: BrowserStore,

```

**Comment by ZianeA** [comment]
@jonalmeida Thanks for your help! This should work now :crossed_fingers:

**Review by jonalmeida — APPROVED** [review]
Brilliant! ✨
