### PR TITLE
Closes #17530: Update has open tabs metrics when tabs are opened or closed

### LINKED ISSUE #17530: [Bug] open tabs metric remain set to false
Followup to #16832

## Prerequisites
Have a couple of open tabs

## Steps to reproduce
Generate the **`metrics`** ping

### Expected behavior
The following **`boolean`** probes should be properly updated:
```
"metrics": {
        "boolean": {
          ...
          "metrics.has_open_tabs"
         ...
        }
```

### Actual behavior
The above mentioned probes remain set to false

## Notes
This metric is [set on startup](https://github.com/mozilla-mobile/fenix/blob/cf61c10c39be1f7e2037a36408577e1dc57667d8/app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt#L750) for Glean. This metric  should **always reflect the current state of the app**. Currently, we are only evaluating this metric (and others) on startup and this can lead to delayed/incorrect metrics.

### PR DESCRIPTION
**Pull request by rocketsroger**
### Pull Request checklist

- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

File: app/src/test/java/org/mozilla/fenix/TelemetryMiddlewareTest.kt [hunk 1]
```diff
@@ -86,10 +91,13 @@ class TelemetryMiddlewareTest {
                 createTab(id = "2", url = "https://firefox.com"))
             )
         ).joinBlocking()
+        shadowOf(getMainLooper()).idle()
```
Comment (csadilek) [inline app/src/test/java/org/mozilla/fenix/TelemetryMiddlewareTest.kt:94]: nit: Hm why did you need these here? We should probably handle this with a test dispatcher instead?

Comment (rocketsroger) [reply app/src/test/java/org/mozilla/fenix/TelemetryMiddlewareTest.kt:94]: yes, needed to wait till idle.  Should I'll see if I can use a test dispatcher instead.

**Review by csadilek — APPROVED** [review]
