### PR TITLE
For #28265 - Refactor InactiveTabs interactor/controller into TabsTray

### LINKED ISSUE #28265: [Tabs Tray Refactor] Remove `DefaultInactiveTabsInteractor` and `DefaultInactiveTabsController` and relocate the implemented functions to `TabsTrayInteractor` and `TabsTrayController`
Meta issue:
- https://github.com/mozilla-mobile/fenix/issues/25722

All/most/some of this was already done as a part of https://github.com/mozilla-mobile/fenix/pull/25895, but is being split out so it can be more safely landed.

Notes for QA: This is a business logic refactor in the tabs tray, so the existing functionality should remain the same. Please validate that no there have been no regressions involving inactive tabs or the tabs tray.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22171)

### PR DESCRIPTION
**Pull request by MozillaNoah**
PR 6 of 10 for https://github.com/mozilla-mobile/fenix/issues/25722

### Pull Request checklist

- [X] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### QA

- [x] **QA Needed**

### To download an APK when reviewing a PR (after all CI tasks finished running):
1. Click on `Checks` at the top of the PR page.
2. Click on the `firefoxci-taskcluster` group on the left to expand all tasks.
3. Click on the `build-debug` task.
4. Click on `View task in Taskcluster` in the new `DETAILS` section.
5. The APK links should be on the right side of the screen, named for each CPU architecture.

### GitHub Automation
Fixes #28265

### CODE REVIEW

**Comment by MozillaNoah** [comment]
I'm going to move this to draft, as I found out from the UI test that doing this ticket created a circular dependency between `BrowserTrayInteractor` and `TabsTrayInteractor`, so I'll need to do https://github.com/mozilla-mobile/fenix/issues/28266 first.

File: app/src/main/java/org/mozilla/fenix/tabstray/browser/InactiveTabsInteractor.kt [hunk 1]
```diff
@@ -48,61 +46,3 @@ interface InactiveTabsInteractor {
...
-    }
-
-    /**
-     * See [InactiveTabsInteractor.onInactiveTabClicked].
-     */
-    override fun onInactiveTabClicked(tab: TabSessionState) {
-        controller.handleInactiveTabClicked(tab)
-        tabsTrayInteractor.onTabSelected(tab, TrayPagerAdapter.INACTIVE_TABS_FEATURE_NAME)
-    }
-
```
Comment (MatthewTighe) [inline app/src/main/java/org/mozilla/fenix/tabstray/browser/InactiveTabsInteractor.kt:93]: I am so glad this is being untangled 🙏

File: app/src/main/java/org/mozilla/fenix/tabstray/TrayPagerAdapter.kt [hunk 2]
```diff
@@ -42,7 +40,7 @@ class TrayPagerAdapter(
             InactiveTabsAdapter(
                 lifecycleOwner = lifecycleOwner,
                 tabsTrayStore = tabsTrayStore,
-                inactiveTabsInteractor = inactiveTabsInteractor,
+                inactiveTabsInteractor = tabsTrayInteractor,
```
Comment (MatthewTighe) [inline app/src/main/java/org/mozilla/fenix/tabstray/TrayPagerAdapter.kt:43]: IMO, it would make sense to update the parameters names to match this change as well. Would this be an appropriate time to do so for this object hierarchy? Looking through the meta issues, it wasn't immediately clear to me whether this would be revisited.

**Review by MatthewTighe — APPROVED** [review]
Had one question about scope, but no strong opinion on whether it should be resolved now or later. Otherwise, this LGTM!

File: app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayController.kt [hunk 3]
```diff
@@ -170,7 +175,9 @@ interface TabsTrayController : SyncedTabsController {
  * Default implementation of [TabsTrayController].
  *
  * @property activity [HomeActivity] used to perform top-level app actions.
+ * @param appStore [AppStore] used to dispatch any [AppAction].
  * @property tabsTrayStore [TabsTrayStore] used to read/update the [TabsTrayState].
+ * @param settings [Settings] used to update any user preferences.
```
Comment (t-p-white) [inline app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayController.kt:180]:
```suggestion
 * @property settings [Settings] used to update any user preferences.
```
