### PR TITLE
Closes #804: Adds disable private browsing content description

### LINKED ISSUE #804: Private Browsing button state is not known in TalkBack
## Steps to reproduce

1. With TalkBack on go to Private Browsing button. You will hear: "Enable Private Browsing, button"
2. Activate button (double tap)
3. Private browsing window appears, go to Private Browsing. You will hear "Enable Private Browsing, button".

### Expected behavior

When in Private browsing, it should say "Disable Private Browsing, button".

### Actual behavior

It says "Enable Private Browsing, button".

### Device information

* Android device: Pixel
* Fenix version: master/nightly

## Aside

We need to figure out a prominent way for TalkBack users to know they are in private browsing. Right now, they would need to check the state of this button or read the private browsing copy in the private browsing home screen.

That should probably be a followup issue.

### PR DESCRIPTION
**Pull request by sblatz**

### CODE REVIEW

File: app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt [hunk 1]
```diff
@@ -236,6 +228,26 @@ class HomeFragment : Fragment() {
         }
     }
 
+    private fun adaptToPrivateMode() {
```
Comment (boek) [inline app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt]: small nit: This method should probably be split up, or we should just move the click listener to live with the others :)

I would also like to consolidate how many places we're calling the `browsingModeManager` directly while it's still attached to the HomeActivity. An easy way to accomplish that would be

```
val isPrivate = (activity as HomeActivity).browsingModeManager.isPrivate
privateBrowsingButton.contentDescription = contentDescriptionForPrivateBrowsingButton(isPrivate = isPrivate)
```

```
fun contentDescriptionForPrivateBrowsingButton(isPrivate: Boolean): String {
    val resourceId = if (isPrivate) R.string.content_description_disable_private_browsing_button else R.string.content_description_private_browsing_button
    return getString(resourceId)
```
