### PR TITLE
For #17195 Fix Intermittent UI test verifyTabTrayNotShowingStateHalfExpanded

### LINKED ISSUE #17195: Intermittent UI test failure - TabbedBrowsingTest.verifyTabTrayNotShowingStateHalfExpanded
### Firebase Test Run:
https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6532404695638087090/executions/bs.2f606de8ea3dcaaf/testcases/3/test-cases
### Stacktrace:
`androidx.test.espresso.NoMatchingViewException: No views in hierarchy found matching: with id: org.mozilla.fenix.debug:id/tab_wrapper`
### Build: 
Master 12/22

### PR DESCRIPTION
**Pull request by AndiAJ**
Fixes #17195
Previously ran the the verifyTabTrayNotShowingStateHalfExpanded successfully 50x on Firebase.

### Pull Request checklist

- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

File: app/src/androidTest/java/org/mozilla/fenix/ui/TabbedBrowsingTest.kt [hunk 1]
```diff
@@ -257,7 +257,6 @@ class TabbedBrowsingTest {
 
     @Test
     fun verifyTabTrayNotShowingStateHalfExpanded() {
-        homeScreen { }.dismissOnboarding()
```
Comment (isabelrios) [inline app/src/androidTest/java/org/mozilla/fenix/ui/TabbedBrowsingTest.kt:260]: Not sure about this change...that would imply that the workflow has changed? but if it run ~50 times successfully let's give it a try this way...

**Review by isabelrios — APPROVED** [review]
LGTM, thanks!

File: app/src/androidTest/java/org/mozilla/fenix/ui/TabbedBrowsingTest.kt (hunk 1 above)
Comment (sv-ohorvath) [reply app/src/androidTest/java/org/mozilla/fenix/ui/TabbedBrowsingTest.kt:260]: Yes, the nav bar is visible now without dismissing the onboarding. The problem failing this test was actually in this step, so since we don't need it, it can just be removed.
