### PR TITLE
Closes #6031 - Wrap waits with assert check; adjust timer check

### LINKED ISSUE #6031: [Bug] UI tests continue with false positive on mDevice.wait(Until
Currently for UI tests, we are using `mDevice.wait(Until` to wait until a UI element is present.  However, this operation by itself will only wait until the object is found or until the end of the wait period specified.  Without an assert to determine if the element was found or not, the test will proceed with a false positive result.

per @npark-mozilla, mDevice.wait will not fail the test, it’ll only time out. you need to wrap it with Assert to get something to fail, see: [UIDevice](https://developer.android.com/reference/android/support/test/uiautomator/UiDevice.html#wait(android.support.test.uiautomator.SearchCondition%3CR%3E,%20long))

We should use the return value, returns: The final result returned by the condition, or null if the condition was not met before the timeout.

### PR DESCRIPTION
**Pull request by AaronMT**
See #6031

- Adjust waits with assert check
- Adjusts timer to speed things up
- Test fix and cleanup

### CODE REVIEW

File: app/src/androidTest/java/org/mozilla/fenix/ui/TabbedBrowsingTest.kt [hunk 1]
```diff
@@ -74,7 +72,6 @@ class TabbedBrowsingTest {
         }.openHomeScreen { }
 
         homeScreen {
-            mDevice.wait(Until.findObject(By.res("R.id.item_tab")), TestAssetHelper.waitingTime)
```
Comment (npark-mozilla) [inline app/src/androidTest/java/org/mozilla/fenix/ui/TabbedBrowsingTest.kt]: I think most of the deleted mDevice.waits might be all necessary.  The failure I see in Firebase seems to be because it's trying to search for the test result too fast

File: app/src/androidTest/java/org/mozilla/fenix/ui/robots/NavigationToolbarRobot.kt [hunk 2]
```diff
@@ -28,7 +29,6 @@ class NavigationToolbarRobot {
         val mDevice = UiDevice.getInstance(InstrumentationRegistry.getInstrumentation())
 
         fun enterURLAndEnterToBrowser(url: Uri, interact: BrowserRobot.() -> Unit): BrowserRobot.Transition {
-            mDevice.wait(Until.findObject(By.text("Search or enter address")), waitingTime)
```
Comment (npark-mozilla) [inline app/src/androidTest/java/org/mozilla/fenix/ui/robots/NavigationToolbarRobot.kt]: for example without this wait the test might fail looking for urlBar?

Comment (AaronMT) [reply app/src/androidTest/java/org/mozilla/fenix/ui/robots/NavigationToolbarRobot.kt]: For this one in particular we can't use "Search or enter address." as that text is only initially visible and this function is reused.

File: app/src/androidTest/java/org/mozilla/fenix/ui/TabbedBrowsingTest.kt (hunk 1 above)
Comment (rpappalax) [reply app/src/androidTest/java/org/mozilla/fenix/ui/TabbedBrowsingTest.kt]: If I recall, in general, we only added mDevice waits when there was originally a timing issue of some kind, so I think No-Jun may be right.

**Comment by AaronMT** [comment]
> @AaronMT is there a reason why the mDevice.waits were removed? In general, I don't think any of these were added randomly. Each one of them was originally added afaik to address timing issues

I didn't think they were necessary (one in particular above was failing a test) (aside it doesn't make sense to have them in the test but rather should be in the robot)

**Comment by npark-mozilla** [comment]
@AaronMT So let's work on fixing intermittents on this PR until we make a one clean pass.  In this run, only the `shortcutButtonTest` failed, and when I looked at it, it has a good reason why it failed.
after `clickDuckDuckGoResult()`, we don't wait for anything before we call `verifyDuckDuckGoURL()`.  The DOM tree at the time of the failure shows that it was still in the search view, it didn't even open the web view at the time.  I think within `verifyDuckDuckGoURL()`, you have to put a `wait.Until()` to wait for the url text.

File: app/src/androidTest/java/org/mozilla/fenix/syncintegration/SyncIntegrationTest.kt [hunk 3]
```diff
@@ -109,7 +110,7 @@ class SyncIntegrationTest {
     }
 
     fun tapOnSignIn() {
-        mDevice.wait(Until.findObjects(By.text("Sign in")), TestAssetHelper.waitingTime)
+        assertNotNull(mDevice.wait(Until.findObjects(By.text("Sign in")), TestAssetHelper.waitingTime))
```
Comment (Baron-Severin) [inline app/src/androidTest/java/org/mozilla/fenix/syncintegration/SyncIntegrationTest.kt]: It occurs to me that we could make this easier to reuse with an extension function.  Something like the following:

```kotlin
    /**
     * Blocks the test for [waitTime] miliseconds before continuing.
     *
     * Will cause the test to fail is the condition is not met before the timeout.
     */
    fun UiDevice.waitNotNull(
        searchCondition: SearchCondition<*>,
        waitTime: Long = TestAssetHelper.waitingTimeShort
    ) = assertNotNull(wait(searchCondition, waitTime))
```

Which would update L113 to look like `mDevice.waitNotNull(Until.findObjects(By.text("Sign in")))`, or (if we wanted to use a different timeout) `mDevice.waitNotNull(Until.findObjects(By.text("Sign in")), TestAssetHelper.waitingTimeShort)`

Comment (npark-mozilla) [reply app/src/androidTest/java/org/mozilla/fenix/syncintegration/SyncIntegrationTest.kt]: ^ @rpappalax fyi

File: app/src/androidTest/java/org/mozilla/fenix/ui/TabbedBrowsingTest.kt (hunk 1 above)
Comment (AaronMT) [reply app/src/androidTest/java/org/mozilla/fenix/ui/TabbedBrowsingTest.kt]: Restored. Changed the selector to a different one because FindObject is unable to find the CardView resource name `R.id.item_tab` for whatever reason.

Comment (npark-mozilla) [reply app/src/androidTest/java/org/mozilla/fenix/ui/TabbedBrowsingTest.kt]: @AaronMT oh, the resource name is not `R.id.item_tab`for sure.  it's what that refers to, you can see it in uiautomatorviewer.  it's probably something like `org.mozilla.fenix.debug:id/item_tab` .  R.id.item_tab is just a reference to that string.  We can't use it like that.

File: app/src/androidTest/java/org/mozilla/fenix/syncintegration/SyncIntegrationTest.kt (hunk 3 above)
Comment (AaronMT) [reply app/src/androidTest/java/org/mozilla/fenix/syncintegration/SyncIntegrationTest.kt]: We can open a new issue.

**Comment by AaronMT** [comment]
Green @npark-mozilla (quick re-review) :)

**Comment by npark-mozilla** [comment]
@AaronMT let's see how this one goes. :) and also let's create an issue based on Severin's suggestion and see how that goes as well, this might refactor our tests better.
