### PR TITLE
Close #13477: Move BiometricPrompt to a separate feature

### LINKED ISSUE #13477: FNX-14657 ⁃ [Bug][LeakCanary] SavedLoginsAuthFragment leaked
/cc @mcomella 

### Steps to reproduce

Settings > Logins and passwords > Saved logins > unlock

### Expected behavior

No leak.

### Actual behavior

```
┬───
│ GC Root: Global variable in native code
│
├─ dalvik.system.PathClassLoader instance
│    Leaking: NO (InternalLeakCanary↓ is not leaking and A ClassLoader is never leaking)
│    ↓ PathClassLoader.runtimeInternalObjects
├─ java.lang.Object[] array
│    Leaking: NO (InternalLeakCanary↓ is not leaking)
│    ↓ Object[].[891]
├─ leakcanary.internal.InternalLeakCanary class
│    Leaking: NO (HomeActivity↓ is not leaking and a class is never leaking)
│    ↓ static InternalLeakCanary.resumedActivity
├─ org.mozilla.fenix.HomeActivity instance
│    Leaking: NO (Activity#mDestroyed is false)
│    ↓ HomeActivity.mViewModelStore
│                   ~~~~~~~~~~~~~~~
├─ androidx.lifecycle.ViewModelStore instance
│    Leaking: UNKNOWN
│    ↓ ViewModelStore.mMap
│                     ~~~~
├─ java.util.HashMap instance
│    Leaking: UNKNOWN
│    ↓ HashMap.table
│              ~~~~~
├─ java.util.HashMap$Node[] array
│    Leaking: UNKNOWN
│    ↓ HashMap$Node[].[2]
│                     ~~~
├─ java.util.HashMap$Node instance
│    Leaking: UNKNOWN
│    ↓ HashMap$Node.value
│                   ~~~~~
├─ androidx.biometric.BiometricViewModel instance
│    Leaking: UNKNOWN
│    ↓ BiometricViewModel.mClientCallback
│                         ~~~~~~~~~~~~~~~
├─ org.mozilla.fenix.settings.logins.fragment.SavedLoginsAuthFragment$biometricPromptCallback$1 instance
│    Leaking: UNKNOWN
│    Anonymous subclass of androidx.biometric.BiometricPrompt$AuthenticationCallback
│    ↓ SavedLoginsAuthFragment$biometricPromptCallback$1.this$0
│                                                        ~~~~~~
╰→ org.mozilla.fenix.settings.logins.fragment.SavedLoginsAuthFragment instance
​     Leaking: YES (ObjectWatcher was watching this because org.mozilla.fenix.settings.logins.fragment.SavedLoginsAuthFragment received Fragment#onDestroy() callback and Fragment#mFragmentManager is null)
​     key = 77a534a9-73fb-4b7e-9bb1-1c26e0064ca8
​     watchDurationMillis = 9964
​     retainedDurationMillis = 4964

METADATA

Build.VERSION.SDK_INT: 29
Build.MANUFACTURER: OnePlus
LeakCanary version: 2.4
App process name: org.mozilla.fenix.debug
Analysis duration: 6083 ms
```

### Device information

* Android device: OnePlus 7T Pro McLaren Edition / Oxygen OS 10.0.10 (Android 10)
* Fenix version: master branch revision 841d19e8be8b0d85e207524073c1ce2a10b3b670

### PR DESCRIPTION
**Pull request by jonalmeida**
Instead of simply fixing the memory leak for this issue by directly
removing references, it makes more sense to move the whole
BiometricPrompt out of the fragment and into it's own feature to be
re-usable.

### Pull Request checklist

- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [x] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

File: app/src/test/java/org/mozilla/fenix/settings/logins/biometric/BiometricPromptFeatureTest.kt [hunk 1]
```diff
@@ -0,0 +1,105 @@
...
+
+    @Config(sdk = [N])
+    @Test
+    fun `canUseFeature checks for SDK compatible`() {
+        assertFalse(BiometricPromptFeature.canUseFeature(testContext))
+    }
+
+    @Config(sdk = [M])
+    @Test
+    @Ignore("Figure out how to mock the BiometricManager.from(context) call.")
```
Comment (Mugurell) [inline app/src/test/java/org/mozilla/fenix/settings/logins/biometric/BiometricPromptFeatureTest.kt:48]: We can use static mocks (similar to these examples https://mockk.io/#extension-functions)
and setup this test with something like
>        mockkStatic("org.mozilla.fenix.settings.logins.biometric.ext.BiometricManagerKt")
>        val manager: BiometricManager = mockk()
>        every { manager.isHardwareAvailable() } returns true
>        every { manager.isEnrolled() } returns false
>        mockkStatic(BiometricManager::class)
>        every { BiometricManager.from(any()) } returns manager

`<... actual verifications>`

followed at the end of the test by calls to `unmockkStatic(..)`

**Review by Mugurell — COMMENTED** [review]
Few touchups needed before landing but it looks awesome!

**Comment by ekager** [comment]
We can also update to the newest release candidate 1.1.0-rc01! https://developer.android.com/jetpack/androidx/releases/biometric#1.1.0-rc01

File: app/src/main/java/org/mozilla/fenix/settings/logins/fragment/SavedLoginsAuthFragment.kt [hunk 2]
```diff
@@ -74,10 +50,10 @@ class SavedLoginsAuthFragment : PreferenceFragmentCompat() {
      * so we are disabling the settings that navigate while authenticating.
      * https://github.com/mozilla-mobile/fenix/issues/12312
      */
-    private fun togglePrefsEnabledWhileAuthenticating(enabled: Boolean) {
-        requirePreference<Preference>(R.string.pref_key_password_sync_logins).isEnabled = enabled
-        requirePreference<Preference>(R.string.pref_key_save_logins_settings).isEnabled = enabled
-        requirePreference<Preference>(R.string.pref_key_saved_logins).isEnabled = enabled
+    private fun ensurePrefsEnabledWhileAuthenticating() {
```
Comment (ekager) [inline app/src/main/java/org/mozilla/fenix/settings/logins/fragment/SavedLoginsAuthFragment.kt:53]: This looks like a bug. Originally we wanted these to be disabled while we were authenticating, and then enabled again once authentication either was successful or failed. Hence the toggling. 

It looks like somehow the disabling was accidentally refactored out at some point. We should either add it back in or remove this altogether if it's no longer needed.

Original bug:
See https://github.com/mozilla-mobile/fenix/issues/12312

**Review by ekager — CHANGES_REQUESTED** [review]

File: app/src/test/java/org/mozilla/fenix/settings/logins/biometric/BiometricPromptFeatureTest.kt [hunk 3]
```diff
@@ -0,0 +1,105 @@
...
+import android.os.Build.VERSION_CODES.M
+import android.os.Build.VERSION_CODES.N
+import androidx.biometric.BiometricManager.Authenticators.BIOMETRIC_WEAK
+import androidx.biometric.BiometricManager.Authenticators.DEVICE_CREDENTIAL
+import androidx.biometric.BiometricPrompt
+import androidx.fragment.app.Fragment
+import io.mockk.mockk
+import io.mockk.slot
+import io.mockk.verify
+import junit.framework.Assert.assertFalse
```
[the remark this answers is not in the document]
Comment (jonalmeida) [reply app/src/test/java/org/mozilla/fenix/settings/logins/biometric/BiometricPromptFeatureTest.kt:16]: Thanks! I'm not sure why this didn't fail locally for me.

File: app/src/test/java/org/mozilla/fenix/settings/logins/biometric/BiometricPromptFeatureTest.kt (hunk 1 above)
Comment (jonalmeida) [reply app/src/test/java/org/mozilla/fenix/settings/logins/biometric/BiometricPromptFeatureTest.kt:48]: Thanks! I went with just mocking out the `BiometricManager.canAuthenticate` since the extensions were simple condition checks.

File: app/src/main/java/org/mozilla/fenix/settings/logins/fragment/SavedLoginsAuthFragment.kt (hunk 2 above)
Comment (jonalmeida) [reply app/src/main/java/org/mozilla/fenix/settings/logins/fragment/SavedLoginsAuthFragment.kt:53]: Nice catch! I was curious about this as well but I didn't find the diff where this call was removed.

I'll re-add the original behaviour since the latter is outside the scope of this PR.

**Comment by Mugurell** [comment]
`test_debug` task timeout. Restarting.

**Review by ekager — APPROVED** [review]

**Comment by Mugurell** [comment]
Restarting CI tasks.

**Comment by jonalmeida** [comment]
> [taskcluster:error] Task timeout after 7200 seconds. Force killing container.

This is a known issue with CI.

```
2020-11-13T04:13:11    DEBUG -  /app/workdir/cot/ZCiwMkZbRj26wBm5OVvFQw/public/build/x86_64/target.apk matches the expected sha256 c49eb9f15869916c8d21695751e05458c78f88f9310460ac01f5ed78fc9a3e19
2020-11-13T04:18:04    DEBUG -  Reclaiming task...
2020-11-13T04:18:04    DEBUG -  Reclaim task response:
{'credentials': '{********}',
 'runId': 0,
 'status': {'deadline': '2020-11-14T03:26:08.216Z',
            'expires': '2020-12-11T03:26:08.216Z',
            'provisionerId': 'scriptworker-k8s',
            'retriesLeft': 5,
            'runs': [{'reasonCreated': 'scheduled',
                      'runId': 0,
                      'scheduled': '2020-11-13T04:12:05.935Z',
                      'started': '2020-11-13T04:13:03.994Z',
                      'state': 'running',
                      'takenUntil': '2020-11-13T04:38:04.096Z',
                      'workerGroup': 'mobile-t-signing',
                      'workerId': 'mobile-t-signing-byhh5tliq72zcdhygmo4m'}],
            'schedulerId': 'mobile-level-1',
            'state': 'running',
            'taskGroupId': 'WE7u3pUcSma9BTa9hmUSqA',
            'taskId': 'MM8BkEvqSVOijLLzQAo8kw',
            'workerType': 'mobile-t-signing'},
 'takenUntil': '2020-11-13T04:38:04.096Z',
 'workerGroup': 'mobile-t-signing',
 'workerId': 'mobile-t-signing-byhh5tliq72zcdhygmo4m'}
2020-11-13T04:18:04    DEBUG -  waiting 300 seconds before reclaiming...
```

The signing task failing is new to me though.
