### PR TITLE
Closes #20901: Do not record viewTime observations when we do not have a set lastAccess

### LINKED ISSUE #20901: [Bug]: Opening and closing a tab from a collection crashes with history metadata
### Steps to reproduce

1. Enable history metadata feature flag.
2. Have a tab saved in collections.
3. Open the tab.
4. Open the tabs tray.
5. Close the opened tab (there is a bug where it shows up in the inactive section that will be fixed by https://github.com/mozilla-mobile/fenix/issues/20900).

### Expected behaviour

Not crash.

### Actual behaviour

💥 

### Device name

Pixel 3

### Android version

Android 11

### Firefox release type

Firefox Nightly

### Firefox version

92.0a1

### Device logs

```
2021-08-17 23:53:35.941 21454-21607/org.mozilla.fenix.debug E/places::ffi: Unexpected error: SqlError(IntegralValueOutOfRange(5, 2266005280))
2021-08-17 23:53:35.948 21454-21607/org.mozilla.fenix.debug E/ExceptionHandler: Uncaught exception handled: 
    mozilla.appservices.places.PlacesException: Error executing SQL: Integer 2266005280 out of range at index 5
        at mozilla.appservices.places.RustError.intoException(RustError.kt:58)
        at mozilla.appservices.places.PlacesReaderConnection.getHistoryMetadataSince$suspendImpl(PlacesConnection.kt:1732)
        at mozilla.appservices.places.PlacesReaderConnection.getHistoryMetadataSince(Unknown Source:0)
        at mozilla.components.browser.storage.sync.PlacesHistoryStorage.getHistoryMetadataSince$suspendImpl(PlacesHistoryStorage.kt:251)
        at mozilla.components.browser.storage.sync.PlacesHistoryStorage.getHistoryMetadataSince(Unknown Source:0)
        at org.mozilla.fenix.historymetadata.HistoryMetadataFeature$start$1.invokeSuspend(HistoryMetadataFeature.kt:41)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

### Additional information

cc: @gabrielluong @grigoryk 

https://user-images.githubusercontent.com/1370580/129976813-de5819f5-7ca0-4672-af8d-950e30a2124f.mp4

### PR DESCRIPTION
**Pull request by grigoryk**
The bug here was that we'd try to record `now - 0` as a viewTime delta.
This isn't just an obviously wrong value to record, but it will also
overflow our storage - we'll end up with a value on disk that doesn't
fit into an i32, but HistoryMetadata.total_view_time is i32 in our Rust
struct. Once that happens, reads that touch this bad row will result in
an overflow and a crash.

### Pull Request checklist

- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

File: app/src/main/java/org/mozilla/fenix/historymetadata/HistoryMetadataService.kt [hunk 1]
```diff
@@ -81,11 +81,17 @@ class DefaultHistoryMetadataService(
...
+            logger.debug("Not updating metadata for tab $tab - lastAccess=0")
+            return
+        } else {
+            logger.debug("Updating metadata for tab $tab")
+        }
 
         scope.launch {
             val viewTimeObservation = HistoryMetadataObservation.ViewTimeObservation(
-                viewTime = (System.currentTimeMillis() - tab.lastAccess).toInt()
+                viewTime = (System.currentTimeMillis() - lastAccess).toInt()
```
Comment (Amejia481) [inline app/src/main/java/org/mozilla/fenix/historymetadata/HistoryMetadataService.kt:94]: Is this something that we should be preventing on the component itself? To share the validation between consumers?

Comment (Amejia481) [reply app/src/main/java/org/mozilla/fenix/historymetadata/HistoryMetadataService.kt:94]: Maybe this is just a temporary fix to prevent the crash :)

**Review by Amejia481 — APPROVED** [review]

File: app/src/main/java/org/mozilla/fenix/historymetadata/HistoryMetadataService.kt (hunk 1 above)
Comment (jonalmeida) [reply app/src/main/java/org/mozilla/fenix/historymetadata/HistoryMetadataService.kt:94]: This should be the entry point where the `lastAccess` value stores the `viewTime` to the storage layer.

`lastAccess` can be 0 if the tab was created (with the context menu perhaps) and never accessed.

**Review by jonalmeida — APPROVED** [review]
