### PR TITLE
Issue #26097: use mock location in UI tests

### LINKED ISSUE #26097: Implement mock location in UI tests
Location permission tests are already written, but not working well on Firebase: https://github.com/mozilla-mobile/fenix/blob/main/app/src/androidTest/java/org/mozilla/fenix/ui/SitePermissionsTest.kt#L278

I ran the tests for location permissions on Firebase virtual devices and they didn't return anything.
Following discussions with Aaron and checking the Firebase community chat, the conclusion is that it is recommended to mock the location.

Found the final solution here https://stackoverflow.com/a/70532450/19230622.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21059)

### PR DESCRIPTION
**Pull request by sv-ohorvath**
Ran 100 times on Firebase and all passed, except some known crashes: https://github.com/mozilla-mobile/fenix/runs/7410642590

The same solution was implemented on Focus.

### Pull Request checklist

- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### QA

- [ ] **QA Needed**

### To download an APK when reviewing a PR (after all CI tasks finished running):
1. Click on `Checks` at the top of the PR page.
2. Click on the `firefoxci-taskcluster` group on the left to expand all tasks.
3. Click on the `build-debug` task.
4. Click on `View task in Taskcluster` in the new `DETAILS` section.
5. The APK links should be on the right side of the screen, named for each CPU architecture.

### GitHub Automation
Fixes #26097

### CODE REVIEW

**Review by Mugurell — APPROVED** [review]
LGTM.

File: app/src/androidTest/java/org/mozilla/fenix/helpers/MockLocationUpdatesRule.kt [hunk 1]
```diff
@@ -0,0 +1,113 @@
...
+/**
+ * Rule that sets up a mock location provider that can inject location samples
+ * straight to the device that the test is running on.
+ *
+ * Credit to the mapbox team
+ * https://github.com/mapbox/mapbox-navigation-android/blob/87fab7ea1152b29533ee121eaf6c05bc202adf02/libtesting-ui/src/main/java/com/mapbox/navigation/testing/ui/MockLocationUpdatesRule.kt
+ *
+ */
+class MockLocationUpdatesRule : ExternalResource() {
+    private val instrumentation = getInstrumentation()
```
Comment (AaronMT) [inline app/src/androidTest/java/org/mozilla/fenix/helpers/MockLocationUpdatesRule.kt:31]: Let's reuse our singleton https://github.com/mozilla-mobile/fenix/blob/main/app/src/androidTest/java/org/mozilla/fenix/helpers/TestHelper.kt#L62

File: app/src/androidTest/java/org/mozilla/fenix/helpers/MockLocationUpdatesRule.kt [hunk 2]
```diff
@@ -0,0 +1,113 @@
...
+
+    private val locationManager: LocationManager by lazy {
+        (appContext.getSystemService(Context.LOCATION_SERVICE) as LocationManager)
+    }
+
+    override fun before() {
+        /* ADB command to enable the mock location setting on the device.
+         * Will not be turned back off due to limitations on knowing its initial state.
+         */
+        instrumentation.uiAutomation.executeShellCommandBlocking(
```
Comment (AaronMT) [inline app/src/androidTest/java/org/mozilla/fenix/helpers/MockLocationUpdatesRule.kt:44]: Aside I wonder if we should use this function in https://github.com/mozilla-mobile/fenix/blob/main/app/src/androidTest/java/org/mozilla/fenix/helpers/HomeActivityTestRule.kt#L81

**Review by AaronMT — APPROVED** [review]
See feedback, otherwise LGTM

File: app/src/androidTest/java/org/mozilla/fenix/helpers/MockLocationUpdatesRule.kt (hunk 1 above)
Comment (sv-ohorvath) [reply app/src/androidTest/java/org/mozilla/fenix/helpers/MockLocationUpdatesRule.kt:31]: I'm not sure if it would be the same thing. mDevice is a UIDevice object, and we need an Instrumentation object here to access uiAutomation which I understand is more powerful in accessing APIs: "The APIs exposed via the returned UiAutomation work across application boundaries while the APIs exposed by the instrumentation do not."

Comment (sv-ohorvath) [reply app/src/androidTest/java/org/mozilla/fenix/helpers/MockLocationUpdatesRule.kt]: I used what you suggested, it worked well so far, on Firebase too.
