### PR TITLE
Closes #1377: Fixed Doorhanger not shown when the toolbar padlock is clicked.

### LINKED ISSUE #1377: FNX3-15517 ⁃ [Bug] Doorhanger not shown when the toolbar padlock is clicked
### Steps to reproduce
1. open a website
1. click the padlock
1. switch to home screen
1. open the previous tab
1. repeat step 2

### Expected behavior
The doorhanger is shown after step 2 and after step 5.

### Actual behavior
There is no doorhanger after step 2.
But the doorhanger is shown after step 5.

### Device information
* Android device: HTC U11 / Android 8.0
* Fenix version: Fenix revision fd1e3d63399d51dba9c1cac2f4e09f00695de890

### PR DESCRIPTION
**Pull request by Amejia481**
### Pull Request checklist

- [x] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/fenix/blob/master/CHANGELOG.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### CODE REVIEW

File: app/src/main/java/org/mozilla/fenix/browser/BrowserFragment.kt [hunk 1]
```diff
@@ -257,8 +257,8 @@ class BrowserFragment : Fragment(), BackHandler {
             )
         }
         toolbarComponent.getView().setOnSiteSecurityClickedListener {
-            sessionId?.run {
-                val session = requireNotNull(requireContext().components.core.sessionManager.findSessionById(this))
+            val session = requireContext().components.core.sessionManager.selectedSession
+            session?.run {
```
Comment (pocmo) [inline app/src/main/java/org/mozilla/fenix/browser/BrowserFragment.kt]: This probably fixes it in normal sessions, but breaks it in custom tabs (where the session id is fixed) - or do we not want to show that in custom tabs?

Comment (pocmo) [reply app/src/main/java/org/mozilla/fenix/browser/BrowserFragment.kt]: I guess even if we not want to show it: Right now it may show the doorhanger for the selected session in the custom tab?  :)

Comment (Amejia481) [reply app/src/main/java/org/mozilla/fenix/browser/BrowserFragment.kt]: You are right, now its breaking custom tabs. For some reasons I'm getting a `null` `sessionId` after the user returns to the same tab but by entering the `url`  or by selecting it from clipboard in the `HomeFragment`.

I will try to find a solution that work for both.

Comment (Amejia481) [reply app/src/main/java/org/mozilla/fenix/browser/BrowserFragment.kt]: To be honest I didn't know that the `doorhanger` was working on custom tabs XD

Comment (Amejia481) [reply app/src/main/java/org/mozilla/fenix/browser/BrowserFragment.kt]: An alternative could be to use the `sessionId` as a primary option and if it is `null` fallback to use the currently selected tab. @pocmo  What do you think?

Comment (Amejia481) [reply app/src/main/java/org/mozilla/fenix/browser/BrowserFragment.kt]: @colintheshots any ideas why the `sessionId` is `null`?

Comment (Amejia481) [reply app/src/main/java/org/mozilla/fenix/browser/BrowserFragment.kt]: I noticed  the [FullScreenFeature is using the same approuch as I described before](https://github.com/mozilla-mobile/android-components/blob/c9a2d3d8c7967a577b59e94f29031b3421b59855/components/feature/session/src/main/java/mozilla/components/feature/session/FullScreenFeature.kt#L29). If `sessionId` is `null` is using the `selected session `. I'll go with the solution if you have any suggestion please let me know.

**Comment by Amejia481** [comment]
@pocmo and @colintheshots  I updated the PR

File: app/src/main/java/org/mozilla/fenix/browser/BrowserFragment.kt (hunk 1 above)
Comment (colintheshots) [reply app/src/main/java/org/mozilla/fenix/browser/BrowserFragment.kt]: Sorry, we should've documented that decision. We needed to pass an argument into BrowserFragment when there is an existing session already opened, but it was valid to have none. An elvis operator wouldn't be sufficient as we needed to handle the null case differently.
