### PR TITLE
Fixes 1689 - Custom tabs menus now reference sessions via sessionId.

### LINKED ISSUE #1689: FNX-5185 ⁃ [Bug] Custom Tabs: navigation buttons are not grayed out when no other page has been visited
## Steps to reproduce
1. Set Fenix as your default browser.
1. Open a custom tab from any app (eg. Gmail, Yelp, Facebook).
1. Tap on the 3dot menu.

### Expected behavior
The navigation buttons are greyed out.

### Actual behavior
The navigation buttons are not grayed out.

### Device information
* Affected devices:
  * Nexus 5 (Android 6.0.1)
  * Nexus 6P (Android 8.1)
  * Samsung Galaxy S8 (Android 9)
  * Google Pixel (Android 9)
* Unaffected devices:
  * HTC 10 (Android 8) - the buttons remain grayed out even if navigating to a different page
* Fenix version: 1.0.1916 (#11061213)

comparison

### PR DESCRIPTION
**Pull request by jhugman**
Fixes #1689.

This PR ensures that custom tabs menus that require the opened (not active) session can do so. This means that forward, back and refresh/stop work and are sensitive to the state of the session.

It also fixes a mismatch between the Android Components `IntentProcessor` and fenix's `BrowserFragment` to send the correct `sessionId`.

### Pull Request checklist

- [ ] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/fenix/blob/master/CHANGELOG.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### CODE REVIEW

File: app/src/main/java/org/mozilla/fenix/browser/BrowserFragment.kt [hunk 1]
```diff
@@ -115,7 +116,7 @@ class BrowserFragment : Fragment(), BackHandler, CoroutineScope,
         savedInstanceState: Bundle?
     ): View? {
         require(arguments != null)
-        customTabSessionId = BrowserFragmentArgs.fromBundle(arguments!!).customTabSessionId
+        customTabSessionId = arguments?.getString(IntentProcessor.ACTIVE_SESSION_ID)
```
Comment (colintheshots) [inline app/src/main/java/org/mozilla/fenix/browser/BrowserFragment.kt]: I'm not sure what the purpose of this change is. Before, it was using Safe Args as compile-time validation of the argument name and nullability. Now, it's not.

Comment (jhugman) [reply app/src/main/java/org/mozilla/fenix/browser/BrowserFragment.kt]: The `BrowserFragmentArgs` name disagreed with how the `IntentProcessor` was putting the session id into the bundle: i.e. the key derived from the [navigation graph][1]: `custom_tab_session_id` != the [key from the IntentProcessor][2]: `activeSessionId`

Given 1) we have access to the _actual_ key directly, and 2) the `getString()` returns `null` if it's not there, I opted against using the _copy of_ the key from`BrowserFragmentArgs` — it's not really providing us with any type safety if we're not using the generated data class from the sending side.

Happy use `SafeBundle` to check against a `ClassCastException` or some other `RuntimeException`.

Please advise.

[1]: https://github.com/mozilla-mobile/fenix/blob/master/app/src/main/res/navigation/nav_graph.xml#L107
[2]: https://github.com/mozilla-mobile/android-components/blob/51ef74db39a20fc76d62775db0f2039a6d0959bd/components/feature/intent/src/main/java/mozilla/components/feature/intent/IntentProcessor.kt#L142

Comment (colintheshots) [reply app/src/main/java/org/mozilla/fenix/browser/BrowserFragment.kt]: I suppose it's okay. It just seems odd, given that we're only passing in the value by Safe Args. I mean I spent most of my career without any Safe Args, but it seems silly to add them to the nav graph and then not use them. I'd either get the nullable value from Safe Args, like we were, or remove it from the graph as unused.
