### PR TITLE
Closes #12971 - Show collection saved snackbar above...

### LINKED ISSUE #12971: [Bug] Show collection saved snackbar above FAB
## Steps to reproduce
Select a few tabs and save them to a collection

### Expected behavior
Snackbar appears above new tab floating action button (FAB)

### Actual behavior
It's below and pushes FAB up

### PR DESCRIPTION
**Pull request by rafalopilowski1**
… FAB via attaching "snackbarAnchor" also when TabTrayViewDialogFragmentState.Mode != Normal.

Closes #12971 

### Pull Request checklist

- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

Screencast

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

File: app/src/main/java/org/mozilla/fenix/tabtray/TabTrayDialogFragment.kt [hunk 1]
```diff
@@ -71,7 +71,11 @@ class TabTrayDialogFragment : AppCompatDialogFragment(), UserInteractionHandler
     private lateinit var tabTrayDialogStore: TabTrayDialogFragmentStore
 
     private val snackbarAnchor: View?
-        get() = if (tabTrayView.fabView.new_tab_button.isVisible) tabTrayView.fabView.new_tab_button
+        get() = if (tabTrayView.fabView.new_tab_button.isVisible || tabTrayView.mode != Mode.Normal) tabTrayView.fabView.new_tab_button
```
Comment (codrut-topliceanu) [inline app/src/main/java/org/mozilla/fenix/tabtray/TabTrayDialogFragment.kt:74]: This line is too long and detekt throws a `MaxLineLength` error. 
I recommend running `./gradlew detekt` and ` ./gradlew ktlint` before pushing.
Otherwise it looks and works great! Thanks for taking a look at this. 🥇

**Review by codrut-topliceanu — CHANGES_REQUESTED** [review]
Works great with the exception of the detekt error. Please see my comment and update your commit. 
Thanks again ❤️

File: app/src/main/java/org/mozilla/fenix/tabtray/TabTrayDialogFragment.kt (hunk 1 above)
Comment (rafalopilowski1) [reply app/src/main/java/org/mozilla/fenix/tabtray/TabTrayDialogFragment.kt:74]: Ohh, I didn't know about that! I'm fixing it right now @codrut-topliceanu .💨

**Review by codrut-topliceanu — APPROVED** [review]
Looks great. Thanks!

**Comment by gabrielluong** [comment]
@topotropic can you do a quick ux review prior to landing?

**Review by topotropic — APPROVED** [review]
Thanks, looks good to me!
