### PR TITLE
Closes #19090: Show snackbar on adding to bookmarks from tabs tray

### LINKED ISSUE #19090: Show snackbar on adding to collection/bookmark from tabs tray
This is a regression in the behaviour from the old tabs tray.

We need to add the two different collection snackbars:
 1. Adding to an existing collection.
 2. Adding to a new one.

UI tests to re-enable when fixed:
 - `verifyExpandedCollectionItemsTest`
 - `shareCollectionTest`
 - `deleteCollectionTest`

See the old tabs tray for reference for now:

https://user-images.githubusercontent.com/1370580/115662746-6cc9d100-a30d-11eb-886d-57896d90fa03.mp4

### PR DESCRIPTION
**Pull request by rocketsroger**
### Pull Request checklist

- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

**Comment by rocketsroger** [comment]
This requires tomorrow's AC version update to pass some tests.

File: app/src/main/java/org/mozilla/fenix/tabstray/ext/Long.kt [hunk 1]
```diff
@@ -0,0 +1,7 @@
+/* This Source Code Form is subject to the terms of the Mozilla Public
+ * License, v. 2.0. If a copy of the MPL was not distributed with this
+ * file, You can obtain one at http://mozilla.org/MPL/2.0/. */
+
+package org.mozilla.fenix.tabstray.ext
+
+internal fun Long?.orDefault() = this ?: -1L
```
Comment (jonalmeida) [inline app/src/main/java/org/mozilla/fenix/tabstray/ext/Long.kt:7]: We forgot to write a doc that this "default" for the home fragment navigation.

File: app/src/main/java/org/mozilla/fenix/components/TabCollectionStorage.kt [hunk 2]
```diff
@@ -59,15 +59,23 @@ class TabCollectionStorage(
         }
     }
 
-    suspend fun createCollection(title: String, sessions: List<TabSessionState>) = ioScope.launch {
-        val id = collectionStorage.createCollection(title, sessions)
-        notifyObservers { onCollectionCreated(title, sessions, id) }
-    }.join()
+    suspend fun createCollection(title: String, sessions: List<TabSessionState>): Long? {
+        var id: Long? = null
```
Comment (jonalmeida) [inline app/src/main/java/org/mozilla/fenix/components/TabCollectionStorage.kt:63]: I feel like this may bite us in the back later on down the line, but right now, I don't know why the compiler is failing us.

**Review by jonalmeida — APPROVED** [review]

File: app/src/main/java/org/mozilla/fenix/collections/CollectionsDialog.kt [hunk 3]
```diff
@@ -22,12 +22,12 @@ import org.mozilla.fenix.ext.getDefaultCollectionNumber
 /**
  * A lambda that is invoked when a confirmation button in a [CollectionsDialog] is clicked.
  *
- * A [TabCollection] of the selected collected is passed to the delegate when confirmed. If null,
- * then a new collection is created.
+ * The ID of [TabCollection] of the selected collection is passed to the delegate when confirmed. If null,
+ * then an ID was not returned
```
[the remark this answers is not in the document]
Comment (rocketsroger) [reply app/src/main/java/org/mozilla/fenix/collections/CollectionsDialog.kt:26]: Agreed.  I'll update.  Thanks

File: app/src/main/java/org/mozilla/fenix/tabstray/ext/Long.kt (hunk 1 above)
Comment (rocketsroger) [reply app/src/main/java/org/mozilla/fenix/tabstray/ext/Long.kt:7]: I'll add it.  Thanks

File: app/src/main/java/org/mozilla/fenix/components/TabCollectionStorage.kt (hunk 2 above)
Comment (rocketsroger) [reply app/src/main/java/org/mozilla/fenix/components/TabCollectionStorage.kt:63]: I'll try to see if there's a better way to do this.

**Review by jonalmeida — APPROVED** [review]
Brilliant! 💪
