### PR TITLE
For #26087 re-enable UI tests disabled due to tabs tray migration to compose

### LINKED ISSUE #26087: [UITests] Track ignored tests from when migrating tabs tray to compose
QA recommended having one ticket tracking all changes which resulted in disabled tests following the compose migration of the tabs tray:

Tests which cannot easily be updated to support compose can be `@Ignore`d with the following comment:
> "Failing after compose migration. See: https://github.com/mozilla-mobile/fenix/issues/26087"

&nbsp;
-----

- [ ] https://github.com/mozilla-mobile/fenix/pull/25996 migrated the grid layout. Some tests are now failing because [TabDrawerRobot](https://github.com/mozilla-mobile/fenix/blob/23796286df770e6b7814e7a4f19fff3c8e08cc71/app/src/androidTest/java/org/mozilla/fenix/ui/robots/TabDrawerRobot.kt#L442 ) used ids from `tab_tray_grid_item.xml` which are not available anymore.

cc @sv-ohorvath @AndiAJ

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21051)

### PR DESCRIPTION
**Pull request by AndiAJ**
For #26087 re-enable UI tests disabled due to tabs tray migration to compose.
All tests successfully passed 100x on Firebase.

### Pull Request checklist

- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### QA

- [ ] **QA Needed**

### To download an APK when reviewing a PR (after all CI tasks finished running):
1. Click on `Checks` at the top of the PR page.
2. Click on the `firefoxci-taskcluster` group on the left to expand all tasks.
3. Click on the `build-debug` task.
4. Click on `View task in Taskcluster` in the new `DETAILS` section.
5. The APK links should be on the right side of the screen, named for each CPU architecture.

### GitHub Automation
Fixes #26087

### CODE REVIEW

**Review by sv-ohorvath — APPROVED** [review]

File: app/src/androidTest/java/org/mozilla/fenix/ui/TabbedBrowsingTest.kt [hunk 1]
```diff
@@ -328,7 +326,8 @@ class TabbedBrowsingTest {
             verifyTabsTrayCounter()
             verifyExistingTabList()
             verifyNormalBrowsingNewTabButton()
-            verifyOpenedTabThumbnail()
+            // Disabled step due to ongoing tabs tray compose refactoring
```
Comment (AaronMT) [inline app/src/androidTest/java/org/mozilla/fenix/ui/TabbedBrowsingTest.kt:329]: We should link a reference bug if we know any.

**Review by AaronMT — APPROVED** [review]

File: app/src/androidTest/java/org/mozilla/fenix/ui/TabbedBrowsingTest.kt (hunk 1 above)
Comment (AndiAJ) [reply app/src/androidTest/java/org/mozilla/fenix/ui/TabbedBrowsingTest.kt]: Done !
