### PR TITLE
Closes #21388: Only parse clipboard content when search fragment is attached

### LINKED ISSUE #21388: [Crash] IllegalStateException: SearchDialogFragment not attached to a context
This is fallout from: https://github.com/mozilla-mobile/fenix/pull/21334

```
java.lang.IllegalStateException: Fragment SearchDialogFragment{432262d} (c0542985-566c-44a3-96bc-b8353b7f3dcc) not attached to a context.
    at androidx.fragment.app.Fragment.requireContext(Fragment.java:2)
    at org.mozilla.fenix.search.SearchDialogFragment$onResume$1$1.invokeSuspend(SearchDialogFragment.kt:5)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
    at java.lang.Thread.run(Thread.java:784)
```

Sentry: https://sentry.prod.mozaws.net/operations/firefox-nightly/issues/13192673/

### PR DESCRIPTION
**Pull request by csadilek**
Fixes #21388. `requireContext` caused the crash. Changed it to only dispatch if attached and only if we actually have a clipboard URL, which seems right for this use case.

### CODE REVIEW

File: app/src/main/java/org/mozilla/fenix/search/SearchDialogFragment.kt [hunk 1]
```diff
@@ -382,11 +382,9 @@ class SearchDialogFragment : AppCompatDialogFragment(), UserInteractionHandler {
             // We delay querying the clipboard by posting this code to the main thread message queue,
             // because ClipboardManager will return null if the does app not have input focus yet.
             lifecycleScope.launch(Dispatchers.Cached) {
-                store.dispatch(
-                    SearchFragmentAction.UpdateClipboardUrl(
-                        requireContext().components.clipboardHandler.url
-                    )
-                )
+                context?.components?.clipboardHandler?.url?.let { clipboardUrl ->
```
Comment (csadilek) [inline app/src/main/java/org/mozilla/fenix/search/SearchDialogFragment.kt:385]: NB: I am not using `runIfFragmentAttached` here because it's not thread-safe and we're not on `MAIN`.

**Review by pocmo — APPROVED** [review]

**Review by pocmo — APPROVED** [review]
Still good. ✅ 😂

**Comment by csadilek** [comment]
Network error :).

**Comment by csadilek** [comment]
Ran into intermittent that already landed in https://github.com/mozilla-mobile/fenix/commit/e9434a5b11343a3d7c138984bf3d06cd7e9b3d51.
