### PR TITLE
For #27485 - Add optional overrides for the colors in `Button` Composables

### LINKED ISSUE #27485: Make the top-level Button composable color parameters optional
Dependency:
- https://github.com/mozilla-mobile/fenix/issues/26520

Per https://github.com/mozilla-mobile/fenix/pull/27028#discussion_r1000875173, it's risky having a component live a style duality of a Composable we create (e.g. `TertiaryButton`) and a custom styling override under a specific set of circumstances. It would be better/safer to instead allow for some of the top-level `Button` composable parameters to be optional, so that their inherent default values do not leak out into the codebase for a custom override of one/two parameters. Having the button default values outside of the button composables increases the risk of a design regression when the colors are inevitably updated down the road.

For now, the following two parameters should be made optional:
- `textColor`
- `backgroundColor`

The usage of `Button` inside of `CustomizeHomeButtonViewHolder` should also be refactored accordingly as a result of this change.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21839)

### PR DESCRIPTION
**Pull request by MozillaNoah**
SecondaryButton was handled in:
- https://github.com/mozilla-mobile/fenix/issues/27584

### Pull Request checklist

- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### QA

- [ ] **QA Needed**

### To download an APK when reviewing a PR (after all CI tasks finished running):
1. Click on `Checks` at the top of the PR page.
2. Click on the `firefoxci-taskcluster` group on the left to expand all tasks.
3. Click on the `build-debug` task.
4. Click on `View task in Taskcluster` in the new `DETAILS` section.
5. The APK links should be on the right side of the screen, named for each CPU architecture.

### GitHub Automation
Fixes #27485

### CODE REVIEW

File: app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/CustomizeHomeButtonViewHolder.kt [hunk 1]
```diff
@@ -65,11 +63,9 @@ class CustomizeHomeButtonViewHolder(
              * This button will be stylized as a [TertiaryButton] when no wallpaper is selected.
              * Otherwise, the background will use [Wallpaper.cardColorLight] or [Wallpaper.cardColorDark].
              * */
```
Comment (gabrielluong) [inline app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/CustomizeHomeButtonViewHolder.kt:65]: This comment shouldn't be necessary anymore.

File: app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/CustomizeHomeButtonViewHolder.kt [hunk 2]
```diff
@@ -65,11 +63,9 @@ class CustomizeHomeButtonViewHolder(
...
-            Button(
```
Comment (gabrielluong) [inline app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/CustomizeHomeButtonViewHolder.kt:68]: Let's make `Button` a private function now since we should only expect Primary, Secondary, Tertiary and Destructive Button to be the only usage based on our design system. https://searchfox.org/mozilla-mobile/source/fenix/app/src/main/java/org/mozilla/fenix/compose/button/Button.kt#41

**Review by gabrielluong — APPROVED** [review]
