### PR TITLE
For #11860 - Conditionally show add to collection button on Home screen

### LINKED ISSUE #11860: [Bug] Hide save tabs to collection when there is no tab
## Steps to reproduce
When no tabs is open the home screen still shows save tabs to collection. Ideally this should show when there is atleast one tab open

### Expected behavior
Save tabs to collection should not show when there is no tab opened

### Actual behavior
It is showing save tabs to collection

### Device information
* Android device: ? A10
* Fenix version: ? Latest nightly

### PR DESCRIPTION
**Pull request by darkwing**
### Pull Request checklist

Fixes #11860

- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### After merge
- [ ] **Milestone**: Make sure issues finished by this pull request are added to the [milestone](https://github.com/mozilla-mobile/fenix/milestones) of the version currently in development.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

File: app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt [hunk 1]
```diff
@@ -231,6 +232,11 @@ class HomeFragment : Fragment() {
             }
 
             view.tab_button.setCountWithAnimation(tabCount)
+            view.add_tabs_to_collections_button?.visibility = if (tabCount > 0) {
```
Comment (darkwing) [inline app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt:235]: The `?` is needed because pressing the new tab button in private mode crashes the app, presumable because `view.add_tabs_to_collections_button` doesn't exist on that screen.
