### PR TITLE
For #11664 — Fixup MissingResourceExceptions being thrown in exotic Locales

### LINKED ISSUE #11664: FNX2-13560 ⁃ LeanPlum MissingResourceException  No 3-letter language code for locale: cak, lij
Sentry report on Nightly: https://sentry.prod.mozaws.net/operations/fenix-nightly/issues/7513010/?query=is%3Aunresolved%20level%3Afatal

Looks like Leanplum is trying to send messages to the locale `cak` but it's not working, and causing a crash.

Supported languages are [here](https://github.com/mozilla-mobile/fenix/blob/master/l10n.toml) and it does look like `cak` is supported. Maybe it's not supported by the Leanplum SDK/dashboard/localization? cc @lwa-moz

### PR DESCRIPTION
**Pull request by jhugman**
Fixes #11664.

Our kotlin code is not catching the `MissingResourceException` in the `LeanplumMetricsService` which results in the app crashing when the locale isn't known by the device.

Catches the exception, and falls back to the ISO 639 language code. This isn't a great solution, because ISO 639 isn't especially stable.

In practice however this is almost certainly never going to be a problem because Leanplum isn't going to be supported in such exotic locales.

In this case, using the ISO 639 language code allows the error message to be more informative.

### Pull Request checklist

- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### After merge
- [ ] **Milestone**: Make sure issues finished by this pull request are added to the [milestone](https://github.com/mozilla-mobile/fenix/milestones) of the version currently in development.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

**Comment by st3fan** [comment]
@liuche this is a patch we would like to ship in 79.0.1

File: app/src/main/java/org/mozilla/fenix/components/metrics/LeanplumMetricsService.kt [hunk 1]
```diff
@@ -170,6 +178,12 @@ class LeanplumMetricsService(private val application: Application) : MetricsServ
         return LEANPLUM_ENABLED_LOCALES.contains(locale)
     }
 
+    private val Locale.iso3LanguageOrNull: String?
```
Comment (csadilek) [inline app/src/main/java/org/mozilla/fenix/components/metrics/LeanplumMetricsService.kt:181]: Later, this looks like a good candidate for re-use. We could uplift to A-C and add to the support-ktx module.

File: app/src/main/java/org/mozilla/fenix/components/metrics/LeanplumMetricsService.kt [hunk 2]
```diff
@@ -83,12 +84,19 @@ class LeanplumMetricsService(private val application: Application) : MetricsServ
...
-            val currentLocale = when (applicationSetLocale != null) {
-                true -> applicationSetLocale.isO3Language
-                false -> Locale.getDefault().isO3Language
-            }
-            if (!isLeanplumEnabled(currentLocale)) {
-                Log.i(LOGTAG, "Leanplum is not available for this locale: $currentLocale")
+            val currentLocale = applicationSetLocale ?: Locale.getDefault()
+            val languageCode =
+                currentLocale.iso3LanguageOrNull
+                ?: currentLocale.language.let {
```
Comment (csadilek) [inline app/src/main/java/org/mozilla/fenix/components/metrics/LeanplumMetricsService.kt:90]: I double-checked this as `language` is annotated with `@RecentlyNotNull` and I wasn't sure what that meant. Seems safe though!

File: app/src/main/java/org/mozilla/fenix/components/metrics/LeanplumMetricsService.kt (hunk 1 above)
Comment (jhugman) [reply app/src/main/java/org/mozilla/fenix/components/metrics/LeanplumMetricsService.kt:181]: 👍

File: app/src/main/java/org/mozilla/fenix/components/metrics/LeanplumMetricsService.kt (hunk 2 above)
Comment (NotWoods) [reply app/src/main/java/org/mozilla/fenix/components/metrics/LeanplumMetricsService.kt:90]: `RecentlyNotNull` is equivalent to `NotNull` but lets you incrementally update rather than breaking builds (aka no warning). You can just treat it as not null.

Comment (jhugman) [reply app/src/main/java/org/mozilla/fenix/components/metrics/LeanplumMetricsService.kt:90]: 👍
