### PR TITLE
Closes #23517: history items are not being removed after deletion

### LINKED ISSUE #23517: [Bug]: history items are not removed properly
### Steps to reproduce

1. visit a site A, then B, then again A. The history looks like A and B.
2. Delete A, leave history screen, come back again: A is still present.
Another one would be:
1. create a search group.
2. remove item from the inside of the search group.
3. go back to the history screen: it is still present there.

### Expected behaviour

When a site is removed from the list, it doesn't reappear.

### Actual behaviour

After a site is removed from the list, it does reappear.

### Device name

Samsung S9

### Android version

Android 12

### Firefox release type

Firefox Nightly

### Firefox version

98.01

### Device logs

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by mavduevskiy**
Fixes [#23517](https://github.com/mozilla-mobile/fenix/issues/23517)

In short, we used to remove the exact visit (on history screen) or metadata (on search group screen). The first resulted in items reappearing in case we had more than one, but should only one. The second resulted in items deleted from the search group appeared on the history screen. Now we remove the item completely.
NB This change introduces a new bug that comes from the app-servicies side. When an item from the search group is deleted, it actually deletes two items: the one that was deleted and one that referenced it. moz_places_metadata scheme should be changed, I am also working on that.

### CODE REVIEW

**Comment by grigoryk** [comment]
Test failure seems legit, or at least certainly related to your changes:
```
SUITE: org.mozilla.fenix.library.historymetadata.controller.HistoryMetadataGroupControllerTest
  TEST: handleDelete
  FAILURE

java.lang.AssertionError: Verification failed: call 3 of 5: PlacesHistoryStorage(#2294).deleteHistoryMetadata(eq(HistoryMetadataKey(url=http://www.mozilla.com,/ searchTerm=mozilla, referrerUrl=null)), any())) was not called.

Calls to same mock:
1) PlacesHistoryStorage(#2294).deleteVisitsFor(mozilla.org, continuation {})
2) PlacesHistoryStorage(#2294).deleteVisitsFor(firefox.com, continuation {})


Stack traces:
1)                                                                            io.mockk.impl.InternalPlatform.captureStackTrace                 (InternalPlatform.kt:124)                  
                                                                                io.mockk.impl.stub.MockKStub.handleInvocation                  (MockKStub.kt:250)                         
                                              io.mockk.impl.instantiation.JvmMockFactoryHelper$mockHandler$1.invocation                        (JvmMockFactoryHelper.kt:23)               
                                                                       io.mockk.proxy.jvm.advice.Interceptor.call                              (Interceptor.kt:21)                        
                                                mozilla.components.browser.storage.sync.PlacesHistoryStorage.deleteVisitsFor                   (PlacesHistoryStorage.kt:-1)               
   org.mozilla.fenix.library.historymetadata.controller.DefaultHistoryMetadataGroupController$handleDelete$1.invokeSuspend                     (HistoryMetadataGroupController.kt:123)    
                                                         kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith                        (ContinuationImpl.kt:33)                   
                                                                           kotlinx.coroutines.DispatchedTask.run                               (DispatchedTask.kt:106)                    
                                                             kotlinx.coroutines.test.TestCoroutineDispatcher.dispatch                          (TestCoroutineDispatcher.kt:50)            
                                                        kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith             (DispatchedContinuation.kt:322)            
                                                                 kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable         (Cancellable.kt:30)                        
                                                                 kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable$default (Cancellable.kt:25)                        
                                                                           kotlinx.coroutines.CoroutineStart.invoke                            (CoroutineStart.kt:110)                    
                                                                        kotlinx.coroutines.AbstractCoroutine.start                             (AbstractCoroutine.kt:126)                 
                                                            kotlinx.coroutines.BuildersKt__Builders_commonKt.launch                            (Builders.common.kt:56)                    
                                                                               kotlinx.coroutines.BuildersKt.launch                            (-:1)                                      
                                                            kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default                    (Builders.common.kt:47)                    
                                                                               kotlinx.coroutines.BuildersKt.launch$default                    (-:1)                                      
                  org.mozilla.fenix.library.historymetadata.controller.DefaultHistoryMetadataGroupController.handleDelete                      (HistoryMetadataGroupController.kt:120)    
      org.mozilla.fenix.library.historymetadata.controller.HistoryMetadataGroupControllerTest$handleDelete$1.invokeSuspend                     (HistoryMetadataGroupControllerTest.kt:161)
      org.mozilla.fenix.library.historymetadata.controller.HistoryMetadataGroupControllerTest$handleDelete$1.invoke                            (HistoryMetadataGroupControllerTest.kt:-1) 
      org.mozilla.fenix.library.historymetadata.controller.HistoryMetadataGroupControllerTest$handleDelete$1.invoke                            (HistoryMetadataGroupControllerTest.kt:-1) 
                                           kotlinx.coroutines.test.TestBuildersKt$runBlockingTest$deferred$1.invokeSuspend                     (TestBuilders.kt:50)                       
                                                         kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith                        (ContinuationImpl.kt:33)                   
                                                                           kotlinx.coroutines.DispatchedTask.run                               (DispatchedTask.kt:106)                    
                                                             kotlinx.coroutines.test.TestCoroutineDispatcher.dispatch                          (TestCoroutineDispatcher.kt:50)            
                                                        kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith             (DispatchedContinuation.kt:322)            
                                                                 kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable         (Cancellable.kt:30)                        
                                                                 kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable$default (Cancellable.kt:25)                        
                                                                           kotlinx.coroutines.CoroutineStart.invoke                            (CoroutineStart.kt:110)                    
                                                                        kotlinx.coroutines.AbstractCoroutine.start                             (AbstractCoroutine.kt:126)                 
                                                            kotlinx.coroutines.BuildersKt__Builders_commonKt.async                             (Builders.common.kt:91)                    
                                                                               kotlinx.coroutines.BuildersKt.async                             (-:1)                                      
                                                            kotlinx.coroutines.BuildersKt__Builders_commonKt.async$default                     (Builders.common.kt:82)                    
                                                                               kotlinx.coroutines.BuildersKt.async$default                     (-:1)                                      
                                                                      kotlinx.coroutines.test.TestBuildersKt.runBlockingTest                   (TestBuilders.kt:49)                       
                                                                      kotlinx.coroutines.test.TestBuildersKt.runBlockingTest                   (TestBuilders.kt:80)                       
                     org.mozilla.fenix.library.historymetadata.controller.HistoryMetadataGroupControllerTest.handleDelete                      (HistoryMetadataGroupControllerTest.kt:160)
                                                               jdk.internal.reflect.NativeMethodAccessorImpl.invoke0                           (NativeMethodAccessorImpl.java:-2)N        
                                                               jdk.internal.reflect.NativeMethodAccessorImpl.invoke                            (NativeMethodAccessorImpl.java:62)         
                                                           jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke                            (DelegatingMethodAccessorImpl.java:43)     
                                                                                    java.lang.reflect.Method.invoke                            (Method.java:566)                          
                                                                               kotlinx.coroutines.BuildersKt.async$default                     (-:1)                                      
                                                                      kotlinx.coroutines.test.TestBuildersKt.runBlockingTest                   (TestBuilders.kt:49)                       
                                                                      kotlinx.coroutines.test.TestBuildersKt.runBlockingTest                   (TestBuilders.kt:80)                       
                     org.mozilla.fenix.library.historymetadata.controller.HistoryMetadataGroupControllerTest.handleDelete                      (HistoryMetadataGroupControllerTest.kt:160)
                                                               jdk.internal.reflect.NativeMethodAccessorImpl.invoke0                           (NativeMethodAccessorImpl.java:-2)N        
                                                               jdk.internal.reflect.NativeMethodAccessorImpl.invoke                            (NativeMethodAccessorImpl.java:62)         
                                                           jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke                            (DelegatingMethodAccessorImpl.java:43)     
                                                                                    java.lang.reflect.Method.invoke                            (Method.java:566)                          
                                                                   org.junit.runners.model.FrameworkMethod$1.runReflectiveCall                 (FrameworkMethod.java:50)                  
                                                         org.junit.internal.runners.model.ReflectiveCallable.run                               (ReflectiveCallable.java:12)               
                                                                     org.junit.runners.model.FrameworkMethod.invokeExplosively                 (FrameworkMethod.java:47)                  
                                                          org.junit.internal.runners.statements.InvokeMethod.evaluate                          (InvokeMethod.java:17)                     
                                                            org.junit.internal.runners.statements.RunBefores.evaluate                          (RunBefores.java:26)                       
                                                             org.junit.internal.runners.statements.RunAfters.evaluate                          (RunAfters.java:27)                        
                                                                               org.junit.rules.TestWatcher$1.evaluate                          (TestWatcher.java:55)                      
                                                                                    org.junit.rules.RunRules.evaluate                          (RunRules.java:20)                         
                                                    org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate                          (RobolectricTestRunner.java:570)           
                                                                org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0                 (SandboxTestRunner.java:278)               
                                                                   org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0          (Sandbox.java:89)                          
                                                                             java.util.concurrent.FutureTask.run                               (FutureTask.java:264)                      
                                                                     java.util.concurrent.ThreadPoolExecutor.runWorker                         (ThreadPoolExecutor.java:1128)             
                                                              java.util.concurrent.ThreadPoolExecutor$Worker.run                               (ThreadPoolExecutor.java:628)              
                                                                                            java.lang.Thread.run                               (Thread.java:829)                          
	at io.mockk.impl.recording.states.VerifyingState.failIfNotPassed(VerifyingState.kt:66)
	at io.mockk.impl.recording.states.VerifyingState.recordingDone(VerifyingState.kt:42)
	at io.mockk.impl.recording.CommonCallRecorder.done(CommonCallRecorder.kt:47)
	at io.mockk.impl.eval.RecordedBlockEvaluator.record(RecordedBlockEvaluator.kt:64)
	at io.mockk.impl.eval.VerifyBlockEvaluator.verify(VerifyBlockEvaluator.kt:30)
	at io.mockk.MockKDsl.internalCoVerify(API.kt:143)
	at io.mockk.MockKKt.coVerify(MockK.kt:175)
	at io.mockk.MockKKt.coVerify$default(MockK.kt:172)
	at org.mozilla.fenix.library.historymetadata.controller.HistoryMetadataGroupControllerTest$handleDelete$1.invokeSuspend(HistoryMetadataGroupControllerTest.kt:163)
	at org.mozilla.fenix.library.historymetadata.controller.HistoryMetadataGroupControllerTest$handleDelete$1.invoke(HistoryMetadataGroupControllerTest.kt)
	at org.mozilla.fenix.library.historymetadata.controller.HistoryMetadataGroupControllerTest$handleDelete$1.invoke(HistoryMetadataGroupControllerTest.kt)
	at kotlinx.coroutines.test.TestBuildersKt$runBlockingTest$deferred$1.invokeSuspend(TestBuilders.kt:50)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.test.TestCoroutineDispatcher.dispatch(TestCoroutineDispatcher.kt:50)
	at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:322)
	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:30)
	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable$default(Cancellable.kt:25)
	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:110)
	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.async(Builders.common.kt:91)
	at kotlinx.coroutines.BuildersKt.async(Unknown Source)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.async$default(Builders.common.kt:82)
	at kotlinx.coroutines.BuildersKt.async$default(Unknown Source)
	at kotlinx.coroutines.test.TestBuildersKt.runBlockingTest(TestBuilders.kt:49)
	at kotlinx.coroutines.test.TestBuildersKt.runBlockingTest(TestBuilders.kt:80)
	at org.mozilla.fenix.library.historymetadata.controller.HistoryMetadataGroupControllerTest.handleDelete(HistoryMetadataGroupControllerTest.kt:160)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:570)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:278)
	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:89)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by grigoryk** [comment]
https://github.com/mozilla/application-services/issues/4808

File: app/src/main/java/org/mozilla/fenix/components/history/PagedHistoryProvider.kt [hunk 1]
```diff
@@ -164,36 +162,13 @@ class DefaultPagedHistoryProvider(
      */
     suspend fun deleteMetadataSearchGroup(group: History.Group) {
         for (historyMetadata in group.items) {
-            getMatchingHistory(historyMetadata)?.let {
-                historyStorage.deleteVisit(
-                    url = it.url,
-                    timestamp = it.visitTime
-                )
-            }
+            historyStorage.deleteVisitsFor(historyMetadata.url)
```
Comment (grigoryk) [inline app/src/main/java/org/mozilla/fenix/components/history/PagedHistoryProvider.kt:165]: I think it's worth leaving a comment here on _why_ this actually works, and what our intention is here during a delete. Specifically, our intention now is that when user deletes anything using the History UI, we delete all occurrences of the deleted URLs from all of this browsing history.

May be worth leaving a technical note in the code, as well. Before we used to call an obviously-appropriate method named `deleteHistoryMetadata`, and now we do not. This relies on the ON DELETE CASCADE behaviour at the schema level within our metadata table in app services, something which is very much invisible at the application level.

File: app/src/main/java/org/mozilla/fenix/library/historymetadata/controller/HistoryMetadataGroupController.kt [hunk 2]
```diff
@@ -119,16 +120,28 @@ class DefaultHistoryMetadataGroupController(
         scope.launch {
             items.forEach {
                 store.dispatch(HistoryMetadataGroupFragmentAction.Delete(it))
-                activity.components.core.historyStorage.deleteHistoryMetadata(it.historyMetadataKey)
+                activity.components.core.historyStorage.deleteVisitsFor(it.url)
                 metrics.track(Event.HistorySearchTermGroupRemoveTab)
             }
+            // The method is called for both single and multiple items.
+            // In case all items have been deleted, we have to disband the search group.
+            if (store.state.items.isEmpty()) {
```
Comment (grigoryk) [inline app/src/main/java/org/mozilla/fenix/library/historymetadata/controller/HistoryMetadataGroupController.kt:128]: Since `store.dispatch` runs in its own scope (using a single-threaded dispatcher, by default - and we don't override this default), this `if` statement will race against the dispatch above.

To avoid this, I think it's worth refactoring these methods so that we have an explicit codepath for when we need to dispatch a `disband` action, and not try to infer that based on the state.

Otherwise, here you're basically doing what a middleware may do, except in a buggy way.

**Review by grigoryk — COMMENTED** [review]
Getting there! A test to fix, and see my comment regarding a race. Perhaps, the test failure is related to that actually.

File: app/src/main/java/org/mozilla/fenix/components/history/PagedHistoryProvider.kt (hunk 1 above)
Comment (mavduevskiy) [reply app/src/main/java/org/mozilla/fenix/components/history/PagedHistoryProvider.kt:165]: Well, you covered everything nicely, I have nothing left to add. Writing a tech note in code.

File: app/src/main/java/org/mozilla/fenix/library/historymetadata/controller/HistoryMetadataGroupController.kt (hunk 2 above)
Comment (mavduevskiy) [reply app/src/main/java/org/mozilla/fenix/library/historymetadata/controller/HistoryMetadataGroupController.kt:128]: We could simple compare the size of existing items and items to remove, and if they match, consider it to be a full removal. Right?

We have an explicit `handleDeleteAll` method, which is called when the remove all button is clicked. 
But `handleDelete` could also lead to a case when the last item is deleted: all items were selected and deleted, or user was deleting them one by one. It looks like the controller is the exact place (not interactor, not fragment) where we have to decide if the UI is trying to remove the last item, and it is going to be based on the state. Or how we can do that otherwise?

We could move it to middleware, but HistoryMetadataGroupFragmentStore is a separate middleware and knows nothing about the rest. The controller, on the other side, has access to `components.core.store`, so it looks pretty natural to allow it to emit events. No strong opinion though.

File: app/src/main/java/org/mozilla/fenix/components/history/PagedHistoryProvider.kt [hunk 3]
```diff
@@ -163,37 +161,17 @@ class DefaultPagedHistoryProvider(
      * Removes [group] and any corresponding history visits.
      */
     suspend fun deleteMetadataSearchGroup(group: History.Group) {
+        // The intention is to delete items from history for good.
+        // Corresponding metadata items would also be removed,
+        // because of ON DELETE CASCADE relation in DB schema.
```
Comment (grigoryk) [inline app/src/main/java/org/mozilla/fenix/components/history/PagedHistoryProvider.kt:166]: ... and that's what we refer to as a "leaky abstraction" 👯‍♂️

File: app/src/main/java/org/mozilla/fenix/library/historymetadata/controller/HistoryMetadataGroupController.kt [hunk 4]
```diff
@@ -117,18 +119,31 @@ class DefaultHistoryMetadataGroupController(
 
     override fun handleDelete(items: Set<History.Metadata>) {
         scope.launch {
+            val isDeletingLastItem = store.state.items.size == items.size
```
Comment (grigoryk) [inline app/src/main/java/org/mozilla/fenix/library/historymetadata/controller/HistoryMetadataGroupController.kt:122]: It's worth calling out in a comment that we're depending on an assumption here: that `store.state.items` doesn't change independently from user actions (e.g. there's no side-channel process where it may mutate, like a sync running and updating the fragment store state).

File: app/src/test/java/org/mozilla/fenix/library/historymetadata/controller/HistoryMetadataGroupControllerTest.kt [hunk 5]
```diff
@@ -158,13 +167,13 @@ class HistoryMetadataGroupControllerTest {
...
     fun handleDelete() = testDispatcher.runBlockingTest {
-        controller.handleDelete(setOf(mozillaHistoryMetadataItem, firefoxHistoryMetadataItem))
+        controller.handleDelete(getMetadataItemsList().toSet())
 
         coVerify {
-            store.dispatch(HistoryMetadataGroupFragmentAction.Delete(mozillaHistoryMetadataItem))
-            store.dispatch(HistoryMetadataGroupFragmentAction.Delete(firefoxHistoryMetadataItem))
-            historyStorage.deleteHistoryMetadata(mozillaHistoryMetadataItem.historyMetadataKey)
-            historyStorage.deleteHistoryMetadata(firefoxHistoryMetadataItem.historyMetadataKey)
+            getMetadataItemsList().forEach {
```
Comment (grigoryk) [inline app/src/test/java/org/mozilla/fenix/library/historymetadata/controller/HistoryMetadataGroupControllerTest.kt:173]: You should also add a check that we're dispatching `DisbandSearchGroupAction` when appropriate.

e.g. for a deletion there are three conditions to check:
- have 2 items, deleting one;
- have 2 items, deleting all
- have 2 items, deleting 2

also, worth checking abnormal conditions to be a bit defensive, to make sure we don't blow up:
- have 2 items, deleting 5

**Review by grigoryk — COMMENTED** [review]
Looks good now, thanks! just missing some tests, I think.

File: app/src/test/java/org/mozilla/fenix/library/historymetadata/controller/HistoryMetadataGroupControllerTest.kt [hunk 6]
```diff
@@ -157,16 +168,68 @@ class HistoryMetadataGroupControllerTest {
...
+        val abnormalList = listOf(
+            mozillaHistoryMetadataItem,
+            firefoxHistoryMetadataItem,
+            mozillaHistoryMetadataItem.copy(title = "Pocket", url = "https://getpocket.com"),
+            mozillaHistoryMetadataItem.copy(title = "BBC", url = "https://www.bbc.com/"),
+            mozillaHistoryMetadataItem.copy(title = "Stackoverflow", url = "https://stackoverflow.com/")
+        )
+        controller.handleDelete(abnormalList.toSet())
+        coVerify {
+            getMetadataItemsList().forEach {
```
Comment (grigoryk) [inline app/src/test/java/org/mozilla/fenix/library/historymetadata/controller/HistoryMetadataGroupControllerTest.kt:219]: Probably also worth verifying that we're calling `historyStorage.deleteVisitsFor` and `HistoryMetadataGroupFragmentAction.Delete` for the extra items that aren't present in `getMetadataItemsList`.

**Review by grigoryk — APPROVED** [review]
👍
