### PR TITLE
Closes #4080 - Trim New Bookmark Folder Title Text

### LINKED ISSUE #4080: [Bug] Bookmarks folders can be created if using a space(instead of any character) as a title
## Steps to reproduce
1. Launch Fenix.
2. Open the bookmarks section.
3. Add a new folder.
4. Instead of adding any character, add a space.
5. Save the bookmark folder.
### Expected behavior
The **`Must have a title`** message error should be returned not allowing the user to add a bookmark with a space in folder name.
### Actual behavior
The bookmark folder can be created only if adding on the title a space.
### Device information

* Android device: **`Samsung Galaxy S10+(Android 9).`**
* Fenix version: **`7/16`**.
### Notes
Note that when trying to save the bookmark folder without a name, the **`Must have a title`** message error is returned.
Screenshot_20190716-171554_Firefox Nightly

### PR DESCRIPTION
**Pull request by ekager**
### Pull Request checklist

- [X] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/fenix/blob/master/CHANGELOG.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### CODE REVIEW

File: app/src/main/java/org/mozilla/fenix/library/bookmarks/addfolder/AddBookmarkFolderFragment.kt [hunk 1]
```diff
@@ -77,8 +77,9 @@ class AddBookmarkFolderFragment : Fragment() {
     override fun onOptionsItemSelected(item: MenuItem): Boolean {
         return when (item.itemId) {
             R.id.confirm_add_folder_button -> {
-                if (bookmark_add_folder_title_edit.text.isNullOrEmpty()) {
-                    bookmark_add_folder_title_edit.error = getString(R.string.bookmark_empty_title_error)
+                if (bookmark_add_folder_title_edit.text?.trim().isNullOrEmpty()) {
```
Comment (colintheshots) [inline app/src/main/java/org/mozilla/fenix/library/bookmarks/addfolder/AddBookmarkFolderFragment.kt]: It seems .isNullOrBlank() does basically the same thing?

**Comment by colintheshots** [comment]
I added one comment to consider.

File: app/src/main/java/org/mozilla/fenix/library/bookmarks/addfolder/AddBookmarkFolderFragment.kt (hunk 1 above)
Comment (ekager) [reply app/src/main/java/org/mozilla/fenix/library/bookmarks/addfolder/AddBookmarkFolderFragment.kt]: Oh yeah let's use that one sec
