### PR TITLE
For #22558 - Fix private theme bug in Tabs Tray

### LINKED ISSUE #22558: Update inactive tabs colors on tab tray when in private browsing
### Steps to reproduce

Visit a site in private mode and switch to non-private mode

### Expected behaviour

Headlines and "inactive tabs" section have correct colors (what we currently have in non-private mode)

### Actual behaviour

Headlines are white, inactive tabs section has accent color background

### Device name

_No response_

### Android version

Android 12

### Firefox release type

Firefox Nightly

### Firefox version

96

### Device logs

_No response_

### Additional information

_No response_

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18715)

### PR DESCRIPTION
**Pull request by MozillaNoah**
| Before | After |
| ------------- | ------------- |
|   |  |

### Pull Request checklist

- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### QA

- [x] **QA Needed**

### To download an APK when reviewing a PR (after all CI tasks finished running):
1. Click on `Checks` at the top of the PR page.
2. Click on the `firefoxci-taskcluster` group on the left to expand all tasks.
3. Click on the `build-debug` task.
4. Click on `View task in Taskcluster` in the new `DETAILS` section.
5. The APK links should be on the right side of the screen, named for each CPU architecture.

### GitHub Automation
Fixes #22558

### CODE REVIEW

File: app/src/main/java/org/mozilla/fenix/theme/FirefoxTheme.kt [hunk 1]
```diff
@@ -34,11 +34,17 @@ enum class Theme {
         /**
          * Returns the current [Theme] that is displayed.
          *
+         * @param allowPrivateBrowsingTheme Boolean used to control whether [Theme.Private] is an option
+         * for [FirefoxTheme] colors.
+         *
```
Comment (gabrielluong) [inline app/src/main/java/org/mozilla/fenix/theme/FirefoxTheme.kt:39]:
```suggestion
         * @param usePrivateTheme Boolean used to control whether [Theme.Private] is an option
         * for [FirefoxTheme] colors.
```

File: app/src/main/java/org/mozilla/fenix/compose/ComposeViewHolder.kt [hunk 2]
```diff
@@ -31,12 +32,18 @@ abstract class ComposeViewHolder(
     @Composable
     abstract fun Content()
 
+    /**
+     * Optional override used to disable private browsing theming and only obey dark/light theming.
+     */
+    @Composable
+    open fun allowPrivateBrowsingTheme(): Boolean = true
```
Comment (gabrielluong) [inline app/src/main/java/org/mozilla/fenix/compose/ComposeViewHolder.kt:39]:
```suggestion
     */
    @Composable
    open fun usePrivateTheme(): Boolean = true
```
I actually preferred your initial naming of this since it was less verbose while still conveying the exact meaning.

**Review by gabrielluong — APPROVED** [review]

File: app/src/main/java/org/mozilla/fenix/compose/ComposeViewHolder.kt (hunk 2 above)
Comment (MozillaNoah) [reply app/src/main/java/org/mozilla/fenix/compose/ComposeViewHolder.kt:39]: oh ok, I was worried it could be misconstrued. I'll revert it

Comment (gabrielluong) [reply app/src/main/java/org/mozilla/fenix/compose/ComposeViewHolder.kt:39]: Alternatively, we could say `allowPrivateTheme`.

**Comment by MozillaNoah** [comment]
Recent push changed `ComposeViewHolder`'s `usePrivateTheme` from a `fun` to a `val`, and fixes the private theme bug with the new Compose tab items (list and grid)
