### PR TITLE
Closes #17531: Use shared preference to store top sites count for telemetry

### LINKED ISSUE #17531: [Bug] top sites metric remain set to false
Followup to #16832

## Prerequisites
Have the default top sites available

## Steps to reproduce
Generate the **`metrics`** ping

### Expected behavior
The following **`boolean`** probes should be properly updated:
```
"metrics": {
        "boolean": {
          ...
          "metrics.has_top_sites"
         ...
        }
```

### Actual behavior
The above mentioned probes remain set to false

## Notes
Similar to #17530, this metric is [set on startup](https://github.com/mozilla-mobile/fenix/blob/cf61c10c39be1f7e2037a36408577e1dc57667d8/app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt#L756) for Glean. This metric  should **always reflect the current state of the app**. Currently, we are only evaluating this metric (and others) on startup and this can lead to delayed/incorrect metrics.

### PR DESCRIPTION
**Pull request by rocketsroger**
### Pull Request checklist

- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

**Review by pocmo — APPROVED** [review]

File: app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt [hunk 1]
```diff
@@ -751,13 +751,6 @@ private val Event.wrapper: EventWrapper<*>?
         Event.HaveNoOpenTabs -> EventWrapper<NoExtraKeys>(
             { Metrics.hasOpenTabs.set(false) }
         )
-        Event.HaveTopSites -> EventWrapper<NoExtraKeys>(
-            { Metrics.hasTopSites.set(true) }
-        )
-        Event.HaveNoTopSites -> EventWrapper<NoExtraKeys>(
-            { Metrics.hasTopSites.set(false) }
-        )
```
Comment (gabrielluong) [inline app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt:759]: @rocketsroger Are we sure we no longer need these `Event`? I would check with data to see what they would advise here if possible. If we no longer need them, we should also remove their respective `metrics.yaml` entry otherwise right now we are just not reporting anything in `Metrics.hasTopSites`.

Comment (rocketsroger) [reply app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt:759]: No, we still use the actual metrics.  I didn't remove that.  Take a look at https://github.com/mozilla-mobile/fenix/blob/62e2fb1aa6c60b4e42b4759e8cdba1f490854420/app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt#L892

Comment (gabrielluong) [reply app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt:759]: Gotcha.
