### PR TITLE
Closes #26971: fix wallpaper onboarding display condition

### LINKED ISSUE #26971: bug: wallpaper onboarding is not shown if any of the thumbnails can not be loaded
Changed logic while [refactoring](https://github.com/mozilla-mobile/fenix/pull/26758#discussion_r964257663), want to check if there are enough available wallpapers to show the wallpaper onboarding.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21561)

### PR DESCRIPTION
**Pull request by mavduevskiy**
Closes #26971

Currently one of the thumbnails can not be loaded, and it breaks showing the wallpaper onboarding condition.

### Pull Request checklist

- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### QA

- [x] **QA Needed**

### To download an APK when reviewing a PR (after all CI tasks finished running):
1. Click on `Checks` at the top of the PR page.
2. Click on the `firefoxci-taskcluster` group on the left to expand all tasks.
3. Click on the `build-debug` task.
4. Click on `View task in Taskcluster` in the new `DETAILS` section.
5. The APK links should be on the right side of the screen, named for each CPU architecture.

### GitHub Automation
Fixes #26971

### CODE REVIEW

**Review by MatthewTighe — APPROVED** [review]
LGTM, but I think this would benefit from having a test for it as well

File: app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlController.kt [hunk 1]
```diff
@@ -510,16 +510,18 @@ class DefaultSessionControlController(
...
-                R.id.homeFragment,
-                HomeFragmentDirections.actionGlobalWallpaperOnboardingDialog(),
-            )
-            return true
+        return state.availableWallpapers.filter { wallpaper ->
+            wallpaper.thumbnailFileState == Wallpaper.ImageFileState.Downloaded
+        }.size.let { downloadedCount ->
+            downloadedCount >= WallpaperOnboardingDialogFragment.THUMBNAILS_COUNT
+        }.also { isThumbnailsDownloaded ->
+            if (isThumbnailsDownloaded) {
```
Comment (gabrielluong) [inline app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlController.kt:518]:
```suggestion
            if (downloadedCount >= WallpaperOnboardingDialogFragment.THUMBNAILS_COUNT) {
```
I don't feel too strongly about this, but I think we can simplify this and shave down a couple lines.

Comment (gabrielluong) [reply app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlController.kt:518]: I think we could also use a comment for `THUMBNAILS_COUNT` to indicate that this is minimum threshold to indicate that enough thumbnails have been downloaded.

Comment (mcarare) [reply app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlController.kt:518]: nit: maybe also rename it to make it obvious it is a minimum threshold?

**Review by MatthewTighe — COMMENTED** [review]
Small nit, but I am otherwise happy with this assuming the other comments are addressed

File: app/src/test/java/org/mozilla/fenix/home/DefaultSessionControlControllerTest.kt [hunk 2]
```diff
@@ -878,6 +881,61 @@ class DefaultSessionControlControllerTest {
         assertNull(TopSites.remove.testGetValue()!!.single().extra)
     }
 
+    @Test
+    fun `GIVEN exactly the required amount of downloaded thumbnails WHEN has no errors THEN handleShowWallpapersOnboardingDialog calls the dialog`() {
```
Comment (MatthewTighe) [inline app/src/test/java/org/mozilla/fenix/home/DefaultSessionControlControllerTest.kt:885]: nit: I think these tests might convey their purpose a bit better if they read like:

`GIVEN exactly the required amount of downloaded thumbnails with no errors WHEN handling wallpaper dialog THEN dialog is shown`

and 

`GIVEN fewer than the required amount of downloaded thumbnails WHEN handling wallpaper dialog THEN the dialog is not shown`

File: app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlController.kt (hunk 1 above)
Comment (mavduevskiy) [reply app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlController.kt]: changed the param to `THUMBNAILS_SELECTION_COUNT`. It's not just a trashhold for downloads, it's the amount of items the selector is expected to have. It will take only 6 items if there are more, and we should not try to display the onboarding unless there are less then 6.

**Comment by mavduevskiy** [comment]
@MatthewTighe addressed the naming!

File: app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlController.kt (hunk 1 above)
Comment (gabrielluong) [reply app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlController.kt]: I think this is where the comment for the parameter is more important than the proposed name change here. I don't believe the name change added any additional information or clarity for what it represents.

**Comment by gabrielluong** [comment]
@mavduevskiy Could you make sure you are either squashing or amending your commits before landing? This goes back to @csadilek https://github.com/mozilla-mobile/fenix/pull/26758#issuecomment-1242971836 where we don't want commits that are simply addressing review feedback. Since we are an open source project, we expect to maintain a fairly professional commit log that will help our consumers (forks, etc).

In the future, I would recommend doing `git commit --amend --no-edit` when addressing review feedback for your commits. This will futureproof you for the workflow when we move to phabricator and mozilla-central.

File: app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlController.kt [hunk 3]
```diff
@@ -510,16 +510,19 @@ class DefaultSessionControlController(
...
-                HomeFragmentDirections.actionGlobalWallpaperOnboardingDialog(),
-            )
-            return true
+        return state.availableWallpapers.filter { wallpaper ->
+            wallpaper.thumbnailFileState == Wallpaper.ImageFileState.Downloaded
+        }.size.let { downloadedCount ->
+            // We only display the dialog if enough thumbnails have been downloaded for it.
+            downloadedCount >= WallpaperOnboardingDialogFragment.THUMBNAILS_SELECTION_COUNT
+        }.also { isThumbnailsDownloaded ->
+            if (isThumbnailsDownloaded) {
```
Comment (gabrielluong) [inline app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlController.kt:519]:
```suggestion
            if (downloadedCount >= THUMBNAILS_SELECTION_COUNT) {
```
nit: "Less is more" or so the saying goes. Since you added a comment describing the conditional, I don't think there's really a point in naming the conditional to `isThumbnailsDownloaded`. I would suggest shortening the amount of code that is necessary here.

Also for your imports, you could import `import org.mozilla.fenix.onboarding.WallpaperOnboardingDialogFragment.THUMBNAILS_SELECTION_COUNT` to be less verbose.

Comment (mavduevskiy) [reply app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlController.kt:519]: Hey! Thanks for the reminder. I was actually waiting for some feedback from @MatthewTighe or you before landing. And assuming there might be more changes, didn't squash into one, so the trackrecord would be there.

Regarding the shortening, I am not sure I follow you line of though. Are you suggesting something like this? We mess up the returning type this way, it becomes unit, not boolean

```
return state.availableWallpapers.filter { wallpaper ->
            wallpaper.thumbnailFileState == Wallpaper.ImageFileState.Downloaded
        }.size.let { downloadedCount ->
            // We only display the dialog if enough thumbnails have been downloaded for it.
            if (downloadedCount >= WallpaperOnboardingDialogFragment.THUMBNAILS_SELECTION_COUNT) {
                navController.nav(
                    R.id.homeFragment,
                    HomeFragmentDirections.actionGlobalWallpaperOnboardingDialog(),
                )
            }
        }
```

Comment (gabrielluong) [reply app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlController.kt:519]: Yes I was suggesting what you have provided. I do see the boolean now so, I understand that we couldn't shorten this. Apologizes.

Comment (mavduevskiy) [reply app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlController.kt]: Oh, okay, gotcha. Changed to `showOnboarding`, as well addressing the import as well.

**Comment by mavduevskiy** [comment]
@MatthewTighe @gabrielluong 
Please let me know if you have any further suggestions before we could land it

File: app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlController.kt (hunk 3 above)
Comment (gabrielluong) [reply app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlController.kt]: 👍 Looks good. Thanks!

**Comment by gabrielluong** [comment]
> @MatthewTighe @gabrielluong Please let me know if you have any further suggestions before we could land it

Nothing further from me. I think you're good to go.
