### PR TITLE
Close #20320: Use scope from testDispatcher in RecentBookmarksFeatureTest

### LINKED ISSUE #20320: Intermittent test failure - org.mozilla.fenix.home.recentbookmarks.RecentBookmarksFeatureTest - GIVEN no recent bookmarks WHEN feature starts THEN fetch bookmarks and notify store
### Firebase Test Run:
https://treeherder.mozilla.org/logviewer?job_id=344824917&repo=fenix&lineNumber=25940
### Stacktrace:
```
[task 2021-07-09T23:24:30.159Z]   TEST: GIVEN no recent bookmarks WHEN feature starts THEN fetch bookmarks and notify store
[task 2021-07-09T23:24:30.259Z]     I/glean/Dispatchers: Task queued for execution and delayed until flushed
[task 2021-07-09T23:24:30.259Z]     I/glean/Dispatchers: Task queued for execution and delayed until flushed
[task 2021-07-09T23:24:30.259Z]   FAILURE
[task 2021-07-09T23:24:30.360Z] 
[task 2021-07-09T23:24:30.360Z] java.lang.AssertionError: No action of type class org.mozilla.fenix.home.HomeFragmentAction$RecentBookmarksChange found
[task 2021-07-09T23:24:30.360Z] 	at mozilla.components.support.test.middleware.CaptureActionsMiddleware.findLastAction(CaptureActionsMiddleware.kt:44)
[task 2021-07-09T23:24:30.360Z] 	at mozilla.components.support.test.middleware.CaptureActionsMiddleware.assertLastAction(CaptureActionsMiddleware.kt:64)
[task 2021-07-09T23:24:30.360Z] 	at org.mozilla.fenix.home.recentbookmarks.RecentBookmarksFeatureTest$GIVEN no recent bookmarks WHEN feature starts THEN fetch bookmarks and notify store$1.invokeSuspend(RecentBookmarksFeatureTest.kt:85)
[task 2021-07-09T23:24:30.360Z] 	at org.mozilla.fenix.home.recentbookmarks.RecentBookmarksFeatureTest$GIVEN no recent bookmarks WHEN feature starts THEN fetch bookmarks and notify store$1.invoke(RecentBookmarksFeatureTest.kt)
[task 2021-07-09T23:24:30.360Z] 	at kotlinx.coroutines.test.TestBuildersKt$runBlockingTest$deferred$1.invokeSuspend(TestBuilders.kt:50)
[task 2021-07-09T23:24:30.360Z] 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
[task 2021-07-09T23:24:30.360Z] 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
[task 2021-07-09T23:24:30.360Z] 	at kotlinx.coroutines.test.TestCoroutineDispatcher.dispatch(TestCoroutineDispatcher.kt:50)
[task 2021-07-09T23:24:30.360Z] 	at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:305)
[task 2021-07-09T23:24:30.360Z] 	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:30)
[task 2021-07-09T23:24:30.360Z] 	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable$default(Cancellable.kt:27)
[task 2021-07-09T23:24:30.360Z] 	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:109)
[task 2021-07-09T23:24:30.360Z] 	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:158)
[task 2021-07-09T23:24:30.360Z] 	at kotlinx.coroutines.BuildersKt__Builders_commonKt.async(Builders.common.kt:91)
[task 2021-07-09T23:24:30.360Z] 	at kotlinx.coroutines.BuildersKt.async(Unknown Source)
[task 2021-07-09T23:24:30.360Z] 	at kotlinx.coroutines.BuildersKt__Builders_commonKt.async$default(Builders.common.kt:84)
[task 2021-07-09T23:24:30.361Z] 	at kotlinx.coroutines.BuildersKt.async$default(Unknown Source)
[task 2021-07-09T23:24:30.361Z] 	at kotlinx.coroutines.test.TestBuildersKt.runBlockingTest(TestBuilders.kt:49)
[task 2021-07-09T23:24:30.361Z] 	at kotlinx.coroutines.test.TestBuildersKt.runBlockingTest(TestBuilders.kt:80)
[task 2021-07-09T23:24:30.361Z] 	at org.mozilla.fenix.home.recentbookmarks.RecentBookmarksFeatureTest.GIVEN no recent bookmarks WHEN feature starts THEN fetch bookmarks and notify store(RecentBookmarksFeatureTest.kt:67)
[task 2021-07-09T23:24:30.361Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[task 2021-07-09T23:24:30.361Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[task 2021-07-09T23:24:30.361Z] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[task 2021-07-09T23:24:30.361Z] 	at java.lang.reflect.Method.invoke(Method.java:498)
[task 2021-07-09T23:24:30.361Z] 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
[task 2021-07-09T23:24:30.361Z] 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
[task 2021-07-09T23:24:30.361Z] 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
[task 2021-07-09T23:24:30.361Z] 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
[task 2021-07-09T23:24:30.361Z] 	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
[task 2021-07-09T23:24:30.361Z] 	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
[task 2021-07-09T23:24:30.361Z] 	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
[task 2021-07-09T23:24:30.361Z] 	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
[task 2021-07-09T23:24:30.361Z] 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
[task 2021-07-09T23:24:30.361Z] 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
[task 2021-07-09T23:24:30.361Z] 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
[task 2021-07-09T23:24:30.361Z] 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
[task 2021-07-09T23:24:30.361Z] 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
[task 2021-07-09T23:24:30.361Z] 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
[task 2021-07-09T23:24:30.361Z] 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
[task 2021-07-09T23:24:30.361Z] 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
[task 2021-07-09T23:24:30.361Z] 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
[task 2021-07-09T23:24:30.361Z] 	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:110)
[task 2021-07-09T23:24:30.361Z] 	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
[task 2021-07-09T23:24:30.361Z] 	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
[task 2021-07-09T23:24:30.361Z] 	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)
[task 2021-07-09T23:24:30.361Z] 	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
[task 2021-07-09T23:24:30.361Z] 	at sun.reflect.GeneratedMethodAccessor102.invoke(Unknown Source)
[task 2021-07-09T23:24:30.361Z] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[task 2021-07-09T23:24:30.361Z] 	at java.lang.reflect.Method.invoke(Method.java:498)
[task 2021-07-09T23:24:30.361Z] 	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
[task 2021-07-09T23:24:30.361Z] 	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
[task 2021-07-09T23:24:30.361Z] 	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
[task 2021-07-09T23:24:30.361Z] 	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
[task 2021-07-09T23:24:30.361Z] 	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
[task 2021-07-09T23:24:30.361Z] 	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:119)
[task 2021-07-09T23:24:30.361Z] 	at sun.reflect.GeneratedMethodAccessor101.invoke(Unknown Source)
[task 2021-07-09T23:24:30.361Z] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[task 2021-07-09T23:24:30.361Z] 	at java.lang.reflect.Method.invoke(Method.java:498)
[task 2021-07-09T23:24:30.361Z] 	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
[task 2021-07-09T23:24:30.361Z] 	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
[task 2021-07-09T23:24:30.361Z] 	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
[task 2021-07-09T23:24:30.361Z] 	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
[task 2021-07-09T23:24:30.361Z] 	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:414)
[task 2021-07-09T23:24:30.361Z] 	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
[task 2021-07-09T23:24:30.361Z] 	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
[task 2021-07-09T23:24:30.361Z] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[task 2021-07-09T23:24:30.361Z] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[task 2021-07-09T23:24:30.361Z] 	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
[task 2021-07-09T23:24:30.361Z] 	at java.lang.Thread.run(Thread.java:748)
```
### Build: 
https://github.com/mozilla-mobile/fenix/commit/76f24a7e132fb3d64e33e7606e9e6104cc04be5e

### PR DESCRIPTION
**Pull request by jonalmeida**
### Pull Request checklist

- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [x] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

**Review by csadilek — APPROVED** [review]
🍏

**Comment by jonalmeida** [comment]
Forgot to expose `Dispatcher.IO` so we can override that with the `testDispatcher` as well.

File: app/src/test/java/org/mozilla/fenix/home/recentbookmarks/RecentBookmarksFeatureTest.kt [hunk 1]
```diff
@@ -86,23 +81,4 @@ class RecentBookmarksFeatureTest {
                 assertEquals(listOf(bookmark), it.recentBookmarks)
             }
         }
-
-    @Test
-    fun `WHEN the feature is destroyed THEN the job is cancelled`() {
```
Comment (jonalmeida) [inline app/src/test/java/org/mozilla/fenix/home/recentbookmarks/RecentBookmarksFeatureTest.kt:91]: Removed this test as well because it's testing calls that we make ourself, but is also flaky because it assumes the job is non-null at the assertion point.
