### PR TITLE
For #23971 - Migrate CollectionHeaderViewHolder to Compose

### LINKED ISSUE #23971: Migrate CollectionHeaderViewHolder to Compose
Breakage of https://github.com/mozilla-mobile/fenix/issues/22755

This refers to:
- [CollectionHeaderViewHolder](https://github.com/mozilla-mobile/fenix/blob/f7d317fb4ea76428d4cc9578b76bd9ef6edf8ca0/app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/CollectionHeaderViewHolder.kt) showing a simple "Collections" header

The compose versions can be added to the current RecyclerView but before doing so we should ensure there will be no performance regression introduced.
To profile the differences the steps from https://github.com/mozilla-mobile/fenix/issues/21854#issuecomment-1049392266 can be used.

### PR DESCRIPTION
**Pull request by sarah541**
Fixes #23971 

### Pull Request checklist

- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

File: app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/CollectionHeaderViewHolder.kt [hunk 1]
```diff
@@ -4,14 +4,66 @@
...
+import org.mozilla.fenix.theme.FirefoxTheme
 
 class CollectionHeaderViewHolder(
-    view: View
-) : RecyclerView.ViewHolder(view) {
+    composeView: ComposeView,
+    viewLifecycleOwner: LifecycleOwner,
+) : ComposeViewHolder(composeView, viewLifecycleOwner) {
     companion object {
         const val LAYOUT_ID = R.layout.collection_header
```
Comment (MozillaNoah) [inline app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/CollectionHeaderViewHolder.kt:31]: the old layout file can be deleted now

File: app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/CollectionHeaderViewHolder.kt [hunk 2]
```diff
@@ -4,14 +4,66 @@
...
+@Composable
+fun CollectionHeader(
+    headerText: String
+) {
+    FirefoxTheme {
+        SectionHeader(
+            text = headerText,
+            modifier = Modifier
+                .fillMaxWidth()
+                .padding(16.dp, 16.dp, 16.dp, 0.dp)
```
Comment (MozillaNoah) [inline app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/CollectionHeaderViewHolder.kt:57]: this could probably be simplified by making it `.padding(horizontal = 16.dp)` and adding the 16 top padding to the top Spacer.

File: app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/CollectionHeaderViewHolder.kt [hunk 3]
```diff
@@ -4,14 +4,66 @@
...
+                .wrapContentHeight(align = Alignment.Top),
+        )
+    }
+}
+
+@Composable
+@Preview
+fun CollectionHeaderPreview() {
```
Comment (MozillaNoah) [inline app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/CollectionHeaderViewHolder.kt:65]: nit: previews are usually kept `private`

File: app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/CollectionHeaderViewHolder.kt [hunk 4]
```diff
@@ -4,14 +4,66 @@
...
+            Spacer(Modifier.height(10.dp))
+        }
+    }
+}
+
+@Composable
+fun CollectionHeader(
+    headerText: String
+) {
+    FirefoxTheme {
```
Comment (MozillaNoah) [inline app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/CollectionHeaderViewHolder.kt:52]: the FirefoxTheme isn't necessary since `ComposeViewHolder` wraps the `Content` call with it.

File: app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/CollectionHeaderViewHolder.kt [hunk 5]
```diff
@@ -4,14 +4,66 @@
...
+    viewLifecycleOwner: LifecycleOwner,
+) : ComposeViewHolder(composeView, viewLifecycleOwner) {
     companion object {
         const val LAYOUT_ID = R.layout.collection_header
     }
+
+    @Composable
+    override fun Content() {
+        Column {
+            Spacer(modifier = Modifier.height(40.dp))
```
Comment (MozillaNoah) [inline app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/CollectionHeaderViewHolder.kt:37]: `CollectionHeader` should probably have the Column & Spacers baked into it, so the whole thing can also be previewed

File: app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlAdapter.kt [hunk 6]
```diff
@@ -268,7 +272,6 @@ class SessionControlAdapter(
                     components.core.store,
                     interactor
                 )
-            CollectionHeaderViewHolder.LAYOUT_ID -> CollectionHeaderViewHolder(view)
```
Comment (gabrielluong) [inline app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlAdapter.kt:271]: Needs to be added to onViewRecycled

File: app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/CollectionHeaderViewHolder.kt [hunk 7]
```diff
@@ -4,14 +4,66 @@
...
+
+            CollectionHeader(
```
Comment (gabrielluong) [inline app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/CollectionHeaderViewHolder.kt:39]: Should be able to just call SectionHeader() directly here instead of adding a CollectionHeader wrapper

File: app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/CollectionHeaderViewHolder.kt (hunk 2 above)
Comment (gabrielluong) [reply app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/CollectionHeaderViewHolder.kt:57]: Can you add the init {} with the horizontal margins and I think that will avoid needing to do `.padding(horizontal = 16.dp)`

Comment (gabrielluong) [reply app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/CollectionHeaderViewHolder.kt:57]: I will need to look at the designs and think about this 16 top padding, but we should probably just bump the 40.dp spacer to 56 dp. I want to look at some designs to see if we have the expected spacing

**Review by gabrielluong — CHANGES_REQUESTED** [review]

**Review by gabrielluong — APPROVED** [review]

**Review by gabrielluong — APPROVED** [review]
