### PR TITLE
For #14933 - Fixed private browsing icon color in preferences fragment

### LINKED ISSUE #14933: [Bug] White private browsing icon in settings
## Steps to reproduce
1. Open settings in light mode

### Expected behavior
Private browsing icon matches other icons.

### Actual behavior
Screenshot_20200910-012520

### Device information

* Android device: Android 11
* Fenix version: Nightly 200910 06:07

### PR DESCRIPTION
**Pull request by cadeyrn**
Fixes #14933.

Before:

before

After:

after

### CODE REVIEW

**Comment by liuche** [comment]
bors try

**Comment by liuche** [comment]
We'll try again with bors once this lands :) https://github.com/mozilla-mobile/fenix/pull/14967

File: app/src/main/java/org/mozilla/fenix/settings/SettingsFragment.kt [hunk 1]
```diff
@@ -310,15 +311,21 @@ class SettingsFragment : PreferenceFragmentCompat() {
     }
 
     private fun setupPreferences() {
+        val privateBrowsingKey = getPreferenceKey(R.string.pref_key_private_browsing)
         val leakKey = getPreferenceKey(R.string.pref_key_leakcanary)
         val debuggingKey = getPreferenceKey(R.string.pref_key_remote_debugging)
+        val preferencePrivateBrowsing = findPreference<Preference>(privateBrowsingKey)
```
Comment (NotWoods) [inline app/src/main/java/org/mozilla/fenix/settings/SettingsFragment.kt:317]: You can use the `requirePreference` helper here

File: app/src/main/java/org/mozilla/fenix/settings/SettingsFragment.kt [hunk 2]
```diff
@@ -310,15 +311,21 @@ class SettingsFragment : PreferenceFragmentCompat() {
...
         val preferenceExternalDownloadManager =
             requirePreference<Preference>(R.string.pref_key_external_download_manager)
         val preferenceLeakCanary = findPreference<Preference>(leakKey)
         val preferenceRemoteDebugging = findPreference<Preference>(debuggingKey)
         val preferenceMakeDefaultBrowser =
             requirePreference<Preference>(R.string.pref_key_make_default_browser)
 
+        preferencePrivateBrowsing!!.icon.apply {
```
Comment (NotWoods) [inline app/src/main/java/org/mozilla/fenix/settings/SettingsFragment.kt:325]: You should call `mutate()` on the drawable as a good practice

**Comment by cadeyrn** [comment]
Thanks, @NotWoods. I addressed your feedback!

**Review by NotWoods — APPROVED** [review]

**Review by eliserichards — APPROVED** [review]

**Comment by eliserichards** [comment]
Still waiting for #14967 to land 😢
