### PR TITLE
Fixes #2254/#2709. Observe browser sessions changes on `HomeFragment`.

### LINKED ISSUE #2254: FNX-5545 ⁃ [Bug] no tab title on home
## Steps to reproduce
1. Open https://www.theverge.com/platform/amp/2019/4/29/18522287/samsung-sero-vertical-tv-price-release-date-millennials
1. Open home

### Expected behavior
See tab title

### Actual behavior
No tab title is shown

signal-attachment-2019-05-02-233925

### Device information
* Android device: pixel 2
* Fenix version: latest from play store

### PR DESCRIPTION
**Pull request by dector**
### Issues #2254, #2709 

The root of this issue was that we are not subscribing to existing sessions so `HomeFragment` not recieves updates from them.

### Tests

Technically this issue requires UI test but I see than on this project stage they are not widespread yet. :)

### Notes

  - You've probably noticed that `BrowserSessionsObserver` has `// TODO`. I think that [ObserverRegistry](https://github.com/mozilla-mobile/android-components/blob/51ef74db39a20fc76d62775db0f2039a6d0959bd/components/support/base/src/main/java/mozilla/components/support/base/observer/ObserverRegistry.kt#L19) should store observers in `Set` to avoid multiple subscriptions (as this behavior is error-prone and shouldn't be handled on clients).
  - _(Refactoring suggestion)_ It's possible to make `AllSessionsObserver` more general by adding ability to select source of sessions (it includes sessions from CustomTabs as well).

### Pull Request checklist
- [x] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] ~~**Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/fenix/blob/master/CHANGELOG.md) or does not need one~~
- [x] ~~**Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features~~

### CODE REVIEW

File: app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt [hunk 1]
```diff
@@ -689,3 +649,90 @@ class HomeFragment : Fragment(), CoroutineScope, AccountObserver {
...
+ * @param observer [Session.Observer] instance that will recieve updates.
+ * @param onChanged callback that will be called when any of [SessionManager.Observer]'s events are fired.
+ */
+private class BrowserSessionsObserver(
+    private val manager: SessionManager,
+    private val observer: Session.Observer,
+    private val onChanged: () -> Unit
+) {
+
+    // TODO This is workaround. Should be removed when [mozilla.components.support.base.observer.ObserverRegistry]
```
Comment (dector) [inline app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt]: Will remove it since `ObserverRegistry` fix was merged.
