### PR TITLE
For #27127: do not display wallpaper onboarding in private browsing mode

### LINKED ISSUE #27127: [Bug]: The wallpaper selection tool is displayed in Private Browsing
### Steps to reproduce

Prerequisites:
The user has just installed the Firefox app for the first time.
The Tab Pickup and Jump Back In CFRs are not currently being displayed.
The user has not seen the wallpaper selection tool before.

1. Launch Fenix with a clean profile.
2. In Normal Browsing mode, visit a webpage.
3. Return to homepage.
4. Tap the Private Browsing icon.
5. Observe the PB screen.

### Expected behaviour

The wallpaper selection tool is not displayed in private mode.

### Actual behaviour

The wallpaper selection tool is displayed in private mode. Wallpapers can be loaded. 
After tapping the "Explore more wallpapers" link, the CFR for private shortcut is incorrectly displayed in the Wallpapers Setting screen, which also displayed in the private color.

### Device name

Google Pixel 6

### Android version

Android 13

### Firefox release type

Firefox Nightly

### Firefox version

Firefox Nightly 107.0a1 09/23

### Device logs

_No response_

### Additional information

https://user-images.githubusercontent.com/89388888/191955394-4bcdca18-9a17-47f7-9d37-43d6df6bb666.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21645)

### PR DESCRIPTION
**Pull request by MatthewTighe**
https://user-images.githubusercontent.com/10427470/192060124-a4dc799f-fff7-46f2-b686-a77b533abf56.mp4

### Pull Request checklist

- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### QA

- [x] **QA Needed**

### To download an APK when reviewing a PR (after all CI tasks finished running):
1. Click on `Checks` at the top of the PR page.
2. Click on the `firefoxci-taskcluster` group on the left to expand all tasks.
3. Click on the `build-debug` task.
4. Click on `View task in Taskcluster` in the new `DETAILS` section.
5. The APK links should be on the right side of the screen, named for each CPU architecture.

### GitHub Automation
Fixes #27127

### CODE REVIEW

**Review by gabrielluong — APPROVED** [review]

File: app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlController.kt [hunk 1]
```diff
@@ -509,18 +508,22 @@ class DefaultSessionControlController(
...
-            // We only display the dialog if enough thumbnails have been downloaded for it.
-            downloadedCount >= THUMBNAILS_SELECTION_COUNT
-        }.also { showOnboarding ->
-            if (showOnboarding) {
-                navController.nav(
-                    R.id.homeFragment,
-                    HomeFragmentDirections.actionGlobalWallpaperOnboardingDialog(),
-                )
+    override fun handleShowWallpapersOnboardingDialog(state: AppState): Boolean {
+        return if (state.mode == Mode.Private) {
```
Comment (gabrielluong) [inline app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlController.kt:512]:
```suggestion
        return if (activity.browsingModeManager.mode.isPrivate) {
```
We don't need to pass the `AppState` here since `SessionControlController` has the `AppStore` as a param so let's avoid that. 

However, based on my search on this file, we seem to also check if it is private mode via the code above in this file. We use this `isPrivate` in quick a few places more than the current `appState.mode` while I don't believe there should be a difference. I would be more comfortable with the `isPrivate` approach given the existing general usage for the uplift. I would assume `appState.mode` should just work as well, but this is making me think whether or not we even need `browsingModeManager` anymore, and whether or not we can refactor somethings. So, I would prefer that investigation to be a followup.
