### PR TITLE
Fixes #1219: Display crash reporter (without reporting) on all builds

### LINKED ISSUE #1219: FNX-4880 ⁃ [Bug] App freezes when a tab is crashed and crash reporter is turned off
## Steps to reproduce
1. Go to Settings>Data choices and turn off Crash reporter.
1. Ope a new tab and go to about:crashcontent.
    1. Expected behavior
The tab crashed image is displayed.
    1. Actual behavior
A blank page is displayed and the app stops responding.
    1. Device information

* Android device: Pixel, Nexus 5.
* Fenix version: 3/27 build

### PR DESCRIPTION
**Pull request by sblatz**
### Pull Request checklist

- [ ] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/fenix/blob/master/CHANGELOG.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### CODE REVIEW

File: app/src/main/java/org/mozilla/fenix/components/Analytics.kt [hunk 1]
```diff
@@ -28,14 +29,23 @@ class Analytics(
...
+                tags = mapOf("geckoview" to "$MOZ_APP_VERSION-$MOZ_APP_BUILDID"),
+                sendEventForNativeCrashes = true
+            )
+
+            services = listOf(sentryService)
+        }
 
-        val socorroService = MozillaSocorroService(context, "Fenix")
+        val socorroService = MozillaSocorroService(context, context.getString(R.string.app_name))
+        services += socorroService
```
Comment (sblatz) [inline app/src/main/java/org/mozilla/fenix/components/Analytics.kt]: We have to send at least one service to the CrashReporter or it throws ` IllegalArgumentException("No crash reporter services defined")`. That being said, no crashes should be sent as `isCrashReportingEnabled` will evaluate to false.

File: app/src/main/java/org/mozilla/fenix/components/Analytics.kt [hunk 2]
```diff
@@ -28,14 +29,23 @@ class Analytics(
...
-            context,
-            BuildConfig.SENTRY_TOKEN,
-            tags = mapOf("geckoview" to "$MOZ_APP_VERSION-$MOZ_APP_BUILDID"),
-            sendEventForNativeCrashes = true
-        )
+        var services = listOf<CrashReporterService>()
+        val crashReportingEnabled = BuildConfig.CRASH_REPORTING
+        val isReleaseBuild = BuildConfig.BUILD_TYPE == "release"
+
+        if (crashReportingEnabled && isReleaseBuild) {
```
Comment (boek) [inline app/src/main/java/org/mozilla/fenix/components/Analytics.kt]: Since we can't have both services I would just wrap this in a `!BuildConfig.SENTRY_TOKEN.isNullOrEmpty()` and also use the same pattern for adding to the list `services += sentryService`

**Comment by sblatz** [comment]
@boek I made the changes requested!

File: app/src/main/java/org/mozilla/fenix/utils/Settings.kt [hunk 3]
```diff
@@ -39,7 +40,8 @@ class Settings private constructor(context: Context) {
         get() = preferences.getString(appContext.getPreferenceKey(R.string.pref_key_search_engine), "") ?: ""
 
     val isCrashReportingEnabled: Boolean
-        get() = preferences.getBoolean(appContext.getPreferenceKey(R.string.pref_key_crash_reporter), true)
+        get() = preferences.getBoolean(appContext.getPreferenceKey(R.string.pref_key_crash_reporter), true) &&
```
Comment (colintheshots) [inline app/src/main/java/org/mozilla/fenix/utils/Settings.kt]: So we disable crash reporting with BUILD_TYPE == "release"?

Comment (sblatz) [reply app/src/main/java/org/mozilla/fenix/utils/Settings.kt]: Good catch on this. Missed that when moving it from the early return condition!
