### PR TITLE
Closes #6731 - Multiple bookmark deletions

### LINKED ISSUE #6731: [Bug] When bookmark folders are deleted consecutively, the folder list becomes buggy
bookmark_folder_delete

## Steps to reproduce
- navigate to Bookmarks
- create some folders (if you don't have at least a couple of them)
- delete consecutively at least two folders
### Expected behavior
- deleted folders should desapear for good
### Actual behavior
- deleted folders may come back, letting the folders list inconsistent and buggy
### Device information

* Android device: Mi9T Pro - Android 9
* Fenix version: 1.0.1947 debug

### PR DESCRIPTION
**Pull request by cesarabreu**
---

### Pull Request checklist

- [x] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [x] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### After merge
- [ ] **Milestone**: Make sure issues finished by this pull request are added to the [milestone](https://github.com/mozilla-mobile/fenix/milestones) of the version currently in development.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

File: app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt [hunk 1]
```diff
@@ -263,7 +263,7 @@ abstract class BaseBrowserFragment : Fragment(), BackHandler, SessionManager.Obs
                 }
             )
 
-            downloadFeature.onDownloadCompleted = { download, _, downloadJobStatus ->
+            downloadFeature.onDownloadStopped = { download, _, downloadJobStatus ->
```
Comment (cesarabreu) [inline app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt]: I had to make that change because this was renamed in `android-components` and the version wasn't increased, if you resync your project it won't build anymore.

File: app/src/main/java/org/mozilla/fenix/ext/BookmarkNode.kt [hunk 2]
```diff
@@ -15,5 +15,9 @@ val Context.bookmarkStorage: PlacesBookmarksStorage
  * Removes [children] from [BookmarkNode.children] and returns the new modified [BookmarkNode].
  */
 operator fun BookmarkNode.minus(children: Set<BookmarkNode>): BookmarkNode {
-    return this.copy(children = this.children?.filter { it !in children })
+    return this.copy(children = this.children?.filter { filtered ->
+        children.none {
```
Comment (NotWoods) [inline app/src/main/java/org/mozilla/fenix/ext/BookmarkNode.kt]: Could you convert `children` into a set of guids to avoid the nested loop? I think it would be easier to read that way too.

Comment (cesarabreu) [reply app/src/main/java/org/mozilla/fenix/ext/BookmarkNode.kt]: sure!

**Comment by boek** [comment]
Kicking off CI again!

**Comment by cesarabreu** [comment]
tests fixed

my bad guys... I executed only UI tests

**Comment by cesarabreu** [comment]
@NotWoods , do I need to do remove the ↩️ or something? 😄

**Comment by NotWoods** [comment]
We just threw that on because changing the PR title re-runs tests :)
