### PR TITLE
Closes #10300: Fix Baidu search telemetry

### LINKED ISSUE #10300: In_content search telemetry for Baidu not tracked
## Steps to reproduce
Go to Baidu and search for anything

### Expected behavior
Sap or organic telemetry is tracked

### Actual behavior
No metric is tracked

### Device information
* Android device: Any
* Fenix version: Latest develop

### Engineering info
The problem is that the Desktop codes for tracking are different than those on mobile. We need to research and understand the differences (example: `word` instead of `wd` for `queryParam`)

### PR DESCRIPTION
**Pull request by rxumoz**
Since there might be two types of urls from Baidu (https://m.baidu.com/s?from=... or https://m.baidu.com/from=*/s?), this patch handles baidu separately in Utils.kt

However, there is still a problem that the codes from Baidu are started with numbers (e.g. 844b/1000969a/...), which would be regarded as invalid characters by Glean.

Need more discussion about this, so leave it a draft.

### CODE REVIEW

**Comment by rxumoz** [comment]
Since the problem of Baidu that the codes start with figures, I add prefix to these codes with "_"

File: app/src/main/java/org/mozilla/fenix/search/telemetry/Utils.kt [hunk 1]
```diff
@@ -18,10 +18,30 @@ internal fun getTrackKey(
...
     if (provider.codeParam.isNotEmpty()) {
         code = uri.getQueryParameter(provider.codeParam)
+        if (code.isNullOrEmpty() &&
+            provider.name == "baidu" &&
+            uri.toString().contains("from=")) {
+            code = uri.toString().substringAfter("from=", "")
+                    .substringBefore("/", "")
+        }
+
+        // Telemetry doest not allow code starting with a figure
```
Comment (gabrielluong) [inline app/src/main/java/org/mozilla/fenix/search/telemetry/Utils.kt:33]:
```suggestion
        // Glean doesn't not allow code starting with a figure
```

File: app/src/main/java/org/mozilla/fenix/search/telemetry/Utils.kt [hunk 2]
```diff
@@ -18,10 +18,30 @@ internal fun getTrackKey(
...
+        codeWithPrefix = if (code != null && code.isNotEmpty()) {
+            val codeStart = code.first()
+            val figures = listOf('0', '1', '2', '3', '4', '5', '6', '7', '8', '9')
+            if (codeStart in figures) {
```
Comment (gabrielluong) [inline app/src/main/java/org/mozilla/fenix/search/telemetry/Utils.kt:37]: I think you can do `codeStart.isDigit()` and remove `figures` https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.text/is-digit.html

File: app/src/main/java/org/mozilla/fenix/search/telemetry/Utils.kt [hunk 3]
```diff
@@ -18,10 +18,30 @@ internal fun getTrackKey(
...
         code = uri.getQueryParameter(provider.codeParam)
+        if (code.isNullOrEmpty() &&
+            provider.name == "baidu" &&
+            uri.toString().contains("from=")) {
+            code = uri.toString().substringAfter("from=", "")
+                    .substringBefore("/", "")
+        }
+
+        // Telemetry doest not allow code starting with a figure
+        codeWithPrefix = if (code != null && code.isNotEmpty()) {
```
[the remark this answers is not in the document]
Comment (rxumoz) [reply app/src/main/java/org/mozilla/fenix/search/telemetry/Utils.kt:34]: If we modify the `code` variable and don't add a variable to record the original `code` value, then we need to modify `hasValidCode()` method to trigger `SAP` search metrics correctly.
Maybe I should modify the `code` directly for concisenes and use `originalCode` variable to record?

File: app/src/main/java/org/mozilla/fenix/search/telemetry/Utils.kt [hunk 4]
```diff
@@ -33,7 +48,7 @@ internal fun getTrackKey(
         }
 
         // For Bing if it didn't have a valid cookie and for all the other search engines
-        if (hasValidCode(code, provider)) {
+        if (hasValidCode(originalCode, provider)) {
```
Comment (gabrielluong) [inline app/src/main/java/org/mozilla/fenix/search/telemetry/Utils.kt:51]: Another option is to to call `uri.getQueryParameter(provider.codeParam)` directly here and then we won't need `originalCode`.

File: app/src/main/java/org/mozilla/fenix/search/telemetry/Utils.kt [hunk 5]
```diff
@@ -22,6 +22,21 @@ internal fun getTrackKey(
 
     if (provider.codeParam.isNotEmpty()) {
         code = uri.getQueryParameter(provider.codeParam)
```
Comment (gabrielluong) [inline app/src/main/java/org/mozilla/fenix/search/telemetry/Utils.kt:24]: I can imagine us assigning this to a `codeParam` variable. I wonder how far that could get us without introducing the `originalCode`, but continuing to modify `code`.

File: app/src/main/java/org/mozilla/fenix/search/telemetry/Utils.kt (hunk 4 above)
Comment (rxumoz) [reply app/src/main/java/org/mozilla/fenix/search/telemetry/Utils.kt:51]: I think this could be the easiest way.

File: app/src/main/java/org/mozilla/fenix/search/telemetry/Utils.kt (hunk 5 above)
Comment (rxumoz) [reply app/src/main/java/org/mozilla/fenix/search/telemetry/Utils.kt:24]: I don't quite get. Do you mean adding the "_" after the `codeParam`, or adding other parameters in `SearchProviderModel` apposed with `codeParam`?

**Review by gabrielluong — APPROVED** [review]
