### PR TITLE
For #28090: Show QR scanner for general or custom search engine

### LINKED ISSUE #28090: [Bug]: The qr scanner button is shown just for the default search engine even if that is a topic specific one
### Steps to reproduce

1. Have Unified Search on
2. Tap on search toolbar
3. Change search engine to any general or custom one except default (bing, duckduckgo, etc...)
4. Check if QR button is displayed

https://user-images.githubusercontent.com/32488956/205941160-8458fa7d-eed8-4f78-9cde-4d3180b60d19.mp4

### Expected behaviour

The qr scanner button should be shown for all general search engines (incl. custom ones added by the user) and should be hidden for topic specific search engines like amazon, ebay, wikipedia, etc.

### Actual behaviour

The qr scanner button is shown only for the default search engine - when using the new unified search feature.

### Device name

_No response_

### Android version

Android 10

### Firefox release type

Firefox Nightly

### Firefox version

109.0a1

### Device logs

_No response_

### Additional information

_No response_

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22103)

### PR DESCRIPTION
**Pull request by DreVla**
The implementation for now is a hardcoded, since we do not have a clear separation between "general" search engines and "topic specific" search engines. When that patch lands, this PR will require modifications. Needs https://github.com/mozilla-mobile/firefox-android/pull/273

Expected behavior:

https://user-images.githubusercontent.com/32488956/205978715-7aa21a3e-f462-4598-af04-1adde18c1ca5.mp4

### Pull Request checklist

- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [X] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [X] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### QA

- [x] **QA Needed**

### To download an APK when reviewing a PR (after all CI tasks finished running):
1. Click on `Checks` at the top of the PR page.
2. Click on the `firefoxci-taskcluster` group on the left to expand all tasks.
3. Click on the `build-debug` task.
4. Click on `View task in Taskcluster` in the new `DETAILS` section.
5. The APK links should be on the right side of the screen, named for each CPU architecture.

### GitHub Automation
Fixes #28090

### CODE REVIEW

**Review by t-p-white — APPROVED** [review]
code changes lgtm 👍

File: app/src/main/java/org/mozilla/fenix/search/SearchDialogFragment.kt [hunk 1]
```diff
@@ -811,7 +811,10 @@ class SearchDialogFragment : AppCompatDialogFragment(), UserInteractionHandler {
     }
 
     private fun updateQrButton(searchFragmentState: SearchFragmentState) {
-        when (searchFragmentState.searchEngineSource.searchEngine == searchFragmentState.defaultEngine) {
+        val searchEngine = searchFragmentState.searchEngineSource.searchEngine
+        when (
+            searchEngine?.isGeneral == true || searchEngine?.type == SearchEngine.Type.CUSTOM
```
Comment (gabrielluong) [inline app/src/main/java/org/mozilla/fenix/search/SearchDialogFragment.kt:816]: @DreVla Wouldn't we only need to check `isGeneral` since https://searchfox.org/mozilla-mobile/source/firefox-android/android-components/components/feature/search/src/main/java/mozilla/components/feature/search/storage/SearchEngineReader.kt#74 will set `isGeneral = true` for all custom search engines?
