### PR TITLE
For #26587 - Fix broken previews using Fenix Image composable

### LINKED ISSUE #26587: Fix previews using org.mozilla.fenix.compose.Image
Our `Image` Composable currently breaks any previews, since it uses an `ImageLoader`, and that Composable is not preview-friendly. This can be easily resolved by simply wrapping the `ImageLoader` with an `if(inComposePreview)`

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21358)

### PR DESCRIPTION
**Pull request by MozillaNoah**
### Pull Request checklist

- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### QA

- [ ] **QA Needed**

### To download an APK when reviewing a PR (after all CI tasks finished running):
1. Click on `Checks` at the top of the PR page.
2. Click on the `firefoxci-taskcluster` group on the left to expand all tasks.
3. Click on the `build-debug` task.
4. Click on `View task in Taskcluster` in the new `DETAILS` section.
5. The APK links should be on the right side of the screen, named for each CPU architecture.

### GitHub Automation
Fixes #26587

### CODE REVIEW

File: app/src/main/java/org/mozilla/fenix/compose/Image.kt [hunk 1]
```diff
@@ -46,25 +46,29 @@ fun Image(
...
-            androidx.compose.foundation.Image(
-                painter = painter,
-                modifier = modifier,
-                contentDescription = contentDescription,
-                alignment = alignment,
-                contentScale = contentScale
-            )
-        }
+    if (inComposePreview) {
+        DefaultImagePlaceholder(modifier = modifier)
```
Comment (gabrielluong) [inline app/src/main/java/org/mozilla/fenix/compose/Image.kt:50]: Can you also go into DefaultImagePlaceholder and use an appropriate color variable for the color in there.

**Review by gabrielluong — APPROVED** [review]

File: app/src/main/java/org/mozilla/fenix/compose/Image.kt (hunk 1 above)
Comment (MozillaNoah) [reply app/src/main/java/org/mozilla/fenix/compose/Image.kt:50]: sure, what are we thinking, layer 2?

Comment (gabrielluong) [reply app/src/main/java/org/mozilla/fenix/compose/Image.kt:51]: Whatever was closest to the current colors was good enough with me. Didn't have anything specific in mind
