### PR TITLE
🎲 For 11031 - Fix landscape mode for tab tray

### LINKED ISSUE #11031: FNX-11889 ⁃ [Bug]Tab Tray - Improperly displayed Tabs Tray after rotation
## Prerequisites
Have a couple open tabs

## Steps to reproduce
1. Tap the Tabs Tray
1. Rotate the device to landscape view

### Expected behavior
The Tabs Tray should be visible (preserve the view)

### Actual behavior
The Tabs Tray isn't visible, seems to be shrinking

### Device information
* Android device: 
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)
* Fenix version: Nightly Build 200529 from 5/29

### Notes
► Video

### PR DESCRIPTION
**Pull request by darkwing**
Fixes #11031 

To test:

- Open tab tray in portrait mode, rotate to landscape -- tab tray should take up expanded screen
- Open tab tray in landscape mode -- tab tray should take up expanded screen

### CODE REVIEW

File: app/src/main/java/org/mozilla/fenix/tabtray/TabTrayDialogFragment.kt [hunk 1]
```diff
@@ -44,12 +45,21 @@ class TabTrayDialogFragment : AppCompatDialogFragment(), TabTrayInteractor {
...
+    }
+
     override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
         super.onViewCreated(view, savedInstanceState)
         tabTrayView = TabTrayView(
             view.tabLayout,
             this,
-            (activity as HomeActivity).browsingModeManager.mode.isPrivate
+            (activity as HomeActivity).browsingModeManager.mode.isPrivate,
+            (activity as HomeActivity).resources.configuration.orientation == Configuration.ORIENTATION_LANDSCAPE
```
Comment (boek) [inline app/src/main/java/org/mozilla/fenix/tabtray/TabTrayDialogFragment.kt:62]: you can just used `requireContext().resources.configuration.orientation` here
