### PR TITLE
Fixes #545: overflow menu multitasking deletes private and non-private

### LINKED ISSUE #545: overflow menu for multitasking mixes regular and private sessions
## Steps to reproduce

1. open a website A in a non-private session
2. switch to the private mode
3. open a website B in a private session
4. switch between private and non-private mode
5. click the button for the "current session" overflow menu
6. delete the sesion

### Expected / Actual behavior

Step 4: As expected: the non-private session shows only website A, the private session shows only website B.

Step 5: Unexpected: The dialog shows both website A and website B under the "current session" headline

Step 6: Deleting the session closes both the private as well as the non-private tab.

### Device information

* Android device: HTC U11 w/ Android 8.0.0
* Fenix version: Fenix revision 8293f6a7a71b139316fcc52bf6a8443785c2a6e7

### PR DESCRIPTION
**Pull request by colintheshots**

### CODE REVIEW

File: app/src/main/java/org/mozilla/fenix/home/sessions/CurrentSessionBottomSheetFragment.kt [hunk 1]
```diff
@@ -36,7 +36,9 @@ class CurrentSessionBottomSheetFragment : BottomSheetDialogFragment(), LayoutCon
         }
 
         view.delete_session_button.setOnClickListener {
-            requireComponents.core.sessionManager.removeAll()
+            sessions.forEach {
+                requireComponents.core.sessionManager.remove(it)
+            }
```
Comment (pocmo) [inline app/src/main/java/org/mozilla/fenix/home/sessions/CurrentSessionBottomSheetFragment.kt]: Aye. We should add a helper for that to AC. I'm going to file something and write a patch. :)

`removeAll()` was definitely problematic since it really removes *all* sessions including custom tabs. There's `removeSessions()` to just remove the regular sessions - but that doesn't have the ability to do that for private tabs only.

Comment (colintheshots) [reply app/src/main/java/org/mozilla/fenix/home/sessions/CurrentSessionBottomSheetFragment.kt]: Thanks, Sebastian! I agree this could use a solution from A-C.
