### PR TITLE
For #19492 - Provide the correct CreditCardNumber type to UpdatableCreditCardFields when updating a credit card

### LINKED ISSUE #19492: [Bug] Crash when editing an already saved credit card (or adding a new one overriding the old one)
## Steps to reproduce
1. Launch Fenix and add a valid card.
2. On the credit cards section, select the newly added card and add another valid card.

### Expected behavior
The card number is changed correctly.
### Actual behavior
Crash when editing an already saved credit card (or adding a new one).
### Device information

* Device: **Google Pixel 4 XL (Android 11).**
* Firefox for Android version: **Nightly 5/13.**

```kotlin
c8dbb688-7eed-4c4e-b92f-34f9b11d3c7b
mozilla.appservices.autofill.ErrorException$SqlError: Error executing SQL: CHECK constraint failed: credit_cards_data
----
mozilla.appservices.autofill.ErrorException$SqlError: Error executing SQL: CHECK constraint failed: credit_cards_data
at mozilla.appservices.autofill.Error.intoException(autofill.kt:14)
at mozilla.appservices.autofill.Store.updateCreditCard(autofill.kt:6)
at mozilla.components.service.sync.autofill.AutofillCreditCardsAddressesStorage$updateCreditCard$2.invokeSuspend(AutofillCreditCardsAddressesStorage.kt:25)
at mozilla.components.service.sync.autofill.AutofillCreditCardsAddressesStorage$updateCreditCard$2.invoke(AutofillCreditCardsAddressesStorage.kt:2)
at androidx.core.app.AppOpsManagerCompat.startUndispatchedOrReturn(AppOpsManagerCompat.java:2)
at kotlinx.coroutines.AwaitKt.withContext(Await.kt:9)
at mozilla.components.service.sync.autofill.AutofillCreditCardsAddressesStorage.updateCreditCard(AutofillCreditCardsAddressesStorage.kt:1)
at org.mozilla.fenix.settings.creditcards.controller.DefaultCreditCardEditorController$handleUpdateCreditCard$1.invokeSuspend(CreditCardEditorController.kt:5)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:15)
at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:11)
```

### PR DESCRIPTION
**Pull request by gabrielluong**
Fixes #19492

We were crashing because we were specifying the wrong `CreditCardNumber` type when constructing the `UpdatableCreditCardFields`.
We only had the plaintext card number from the user input, but was placing it off as an encrypted card number, which resulted in the crash.

### Pull Request checklist

- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

File: app/src/main/java/org/mozilla/fenix/settings/creditcards/view/CreditCardEditorView.kt [hunk 1]
```diff
@@ -17,11 +17,8 @@ import mozilla.components.support.ktx.android.view.hideKeyboard
 import mozilla.components.support.utils.creditCardIIN
 import org.mozilla.fenix.R
 import org.mozilla.fenix.ext.toEditable
-import org.mozilla.fenix.settings.creditcards.CreditCardEditorState
+import org.mozilla.fenix.settings.creditcards.*
```
Comment (jonalmeida) [inline app/src/main/java/org/mozilla/fenix/settings/creditcards/view/CreditCardEditorView.kt:20]: This will fail our linter.

**Review by jonalmeida — APPROVED** [review]
