### PR TITLE
Fixes #9280: Remove tabs fade in animation when pressing on Add new collection

### LINKED ISSUE #9280: [Bug] Wrong animation after pressing Add new collection
From #2359 - "There's a lag where after tapping on "Add new collection", the control fades out leaving a blank space before the keyboard appears."

### Steps to reproduce
- On home screen press on `Save to collection`
- Select at least one tab and press `Save`
- Press `Add new collection`

### Expected behavior
- The keyboard should appear immediately on the screen

### Actual behavior
- The keyboard appears after a fade in animation (check [video](https://drive.google.com/open?id=1Y_4XLfJR_rhfZ4VXR_8KTfcu-GownF-g))

### Device information
- Samsung Galaxy Note 10 (Android 10)

Looks like right now there is a fade in animation with 200 ms of duration in Name collection (after pressing Add new collection). After this animation ends, then the keyboard is shown.

### PR DESCRIPTION
**Pull request by ValentinTimisica**
### Pull Request checklist

- [x] **Tests**: This PR does not include thorough tests.
- [x] **Screenshots**: This PR includes [before](https://drive.google.com/open?id=1Y_4XLfJR_rhfZ4VXR_8KTfcu-GownF-g) and [after](https://drive.google.com/open?id=1COtwttcf1xQIh7y5LtY9xN5wwtG0pm9S) videos.
- [x] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md).

### After merge
- [ ] **Milestone**: Make sure issues finished by this pull request are added to the [milestone](https://github.com/mozilla-mobile/fenix/milestones) of the version currently in development.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

File: app/src/main/java/org/mozilla/fenix/collections/CollectionCreationView.kt [hunk 1]
```diff
@@ -232,22 +232,8 @@ class CollectionCreationView(
                 interactor.onBackPressed(SaveCollectionStep.NameCollection)
             }, TRANSITION_DURATION)
```
Comment (ekager) [inline app/src/main/java/org/mozilla/fenix/collections/CollectionCreationView.kt]: should we also remove the back delay? Or is that still useful for some transition that's happening with the keyboard?

Comment (ValentinTimisica) [reply app/src/main/java/org/mozilla/fenix/collections/CollectionCreationView.kt]: Hello @ekager, I also saw that but it is not reported as a bug yet and it doesn't look bad so I decided to let it as it is. What do you think?
