### PR TITLE
For #18395: Text selection menu is not dismissed after activating reader mode

### LINKED ISSUE #18395: [Bug]Text selection menu is not dismissed after the page is in reading mode
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
1. Open an page with a lot of content.
2. Perform a long tap on a word in order to bring up the selection menu.
3. From the URL bar, tap on the reading icon.

### Expected behavior
The text selection menu is dismissed and the page enter in reading mode.

### Actual behavior
The text selection menu is still displayed and no word is selected. 

### Device information
* Device vendor / model and Android version: Xiaomi Redmi Note 8T (Android 9), LG G7 Fit (Android 8.1).
* Firefox for Android version: 86.1.1, 87-beta.4, Nightly 3/9.

### PR DESCRIPTION
**Pull request by VitalyVPinchuk**
Fixes #18395 

Added a variable `actionMode` to track the state of contextual text selection menu and a method `finishActionMode()` to dismiss it before switching to reader mode.

### Pull Request checklist

- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

File: app/src/main/java/org/mozilla/fenix/components/toolbar/BrowserToolbarController.kt [hunk 1]
```diff
@@ -99,6 +99,7 @@ class DefaultBrowserToolbarController(
     }
 
     override fun handleReaderModePressed(enabled: Boolean) {
+        activity.finishActionMode()
```
Comment (Mugurell) [inline app/src/main/java/org/mozilla/fenix/components/toolbar/BrowserToolbarController.kt:102]: This works but adds to the tight coupling of this Controller to HomeActivity.
(we should probably refactor out the activity reference altogether, but in another ticket)
Ideally the Controller should not know or care whether the activity actually has a `finishActionMode` method.

The easiest way to decouple the Controller from HomeActivity would be to have the Controller receive another callback in it's constructor, something like `onReaderModeChanged: () -> Unit` maybe? (It could also send a Boolean) so that any clients of this Controller could decide whether they are interested or not in this functionality, without the Controller having to know anything about them.

**Review by Mugurell — CHANGES_REQUESTED** [review]
This looks good, thank you!
I had two suggestions on how to improve this a little and I'd also want to ask if you could update [this 2 tests](https://github.com/mozilla-mobile/fenix/blob/975f97df467b82ecbbfcde8ec009adae310e00c4/app/src/test/java/org/mozilla/fenix/components/toolbar/DefaultBrowserToolbarControllerTest.kt#L202-L216) with the new changes.

**Comment by VitalyVPinchuk** [comment]
Thanks for the feedback!
I'll try to fix it.

File: app/src/main/java/org/mozilla/fenix/components/toolbar/BrowserToolbarController.kt (hunk 1 above)
Comment (VitalyVPinchuk) [reply app/src/main/java/org/mozilla/fenix/components/toolbar/BrowserToolbarController.kt:102]: Added callback `onReaderModeChanged: () -> Unit = {}` to `DefaultReaderModeController`'s constructor

**Comment by VitalyVPinchuk** [comment]
I've made changes to `DefaultReaderModeControllerTest`, not to `DefaultBrowserToolbarControllerTest` because of `readerModeController`, which is an interface and not an instance of `DefaultReaderModeController` class.
If it's still to be in `DefaultBrowserToolbarControllerTest` as you suggest, I need your advice how to test a class variable through an interface (cast? hint? what else).

**Review by Mugurell — APPROVED** [review]
Looks good!
Thank you!
