### PR TITLE
For #27635 - New telemetry for Save to PDF failures

### LINKED ISSUE #27635: [Telemetry] Add telemetry for Save to PDF failures
We know that 'Save to PDF' can fail for users for various technical reasons (page layout not ready, etc.). We should add telemetry events to know when a Save to PDF action fails by firing probes during the `SaveToPdfExceptionAction`.

_Originally posted by @jonalmeida in https://github.com/mozilla-mobile/fenix/pull/27525#discussion_r1003937178_

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21905)

### PR DESCRIPTION
**Pull request by Amejia481**
Original PR https://github.com/mozilla-mobile/fenix/pull/27661

### Pull Request checklist

- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### QA

- [x] **QA Needed**

### To download an APK when reviewing a PR (after all CI tasks finished running):
1. Click on `Checks` at the top of the PR page.
2. Click on the `firefoxci-taskcluster` group on the left to expand all tasks.
3. Click on the `build-debug` task.
4. Click on `View task in Taskcluster` in the new `DETAILS` section.
5. The APK links should be on the right side of the screen, named for each CPU architecture.

### GitHub Automation
Fixes #27635

### CODE REVIEW

File: app/src/main/java/org/mozilla/fenix/share/SaveToPDFMiddleware.kt [hunk 1]
```diff
@@ -36,9 +34,10 @@ class SaveToPDFMiddleware(
         if (action is EngineAction.SaveToPdfExceptionAction) {
             // See https://github.com/mozilla-mobile/fenix/issues/27649 for more details,
             // why a Toast is used here.
-            GlobalScope.launch(Dispatchers.Main) {
+            ThreadUtils.runOnUiThread {
```
Comment (Amejia481) [inline app/src/main/java/org/mozilla/fenix/share/SaveToPDFMiddleware.kt:37]: @DreVla to make test happy, I removed launch from your changes and kept the `ThreadUtils.runOnUiThread`.

**Review by rocketsroger — APPROVED** [review]

**Comment by Amejia481** [comment]
This seems to be an unrelated error
```
Unable to strip the following libraries, packaging them as they are: libfreebl3.so, libipcclientcerts.so, libjnidispatch.so, liblgpllibs.so, libmegazord.so, libmozavcodec.so, libmozavutil.so, libmozglue.so, libnss3.so, libnssckbi.so, libplugin-container.so, libsentry-android.so, libsentry.so, libsoftokn3.so, libxul.so.
----- End of the daemon log -----


```
