### PR TITLE
For #19797 - Go to problems page if account exists but not signed in

### LINKED ISSUE #19797: [Bug] The "Sign in to sync" option from the three-dot menu is inactive after changing the password
## Steps to reproduce
1. Sign in with the same account on Desktop, and on mobile.
2. From Desktop, change the password.
3. On mobile trigger sync.
4. After the "Reconnect to sync" option is displayed on the three-dot main menu, open a page.
5. Tap on the three-dot menu from the page. Or tap on the three-dot menu from the homescreen.
6. Tap on "Sign in to sync".

### Expected behavior
The user is redirected to the "Reconnect to Sync" page.

### Actual behavior
Nothing happens. The menu is dismissed.

### Device information
* Devices: Google Pixel (Android 10), Samsung Galaxy Tab A6 (Android 5.1.1), OnePlus A3 (Android 6.0.1)
* Firefox for Android version: Beta 90.0.0-beta.1, RC 89.1.1, and Nightly 91.0a1 from 6/3
* Reproducible in Beta 89.0.0-beta.10 as well

[logcat.txt](https://github.com/mozilla-mobile/fenix/files/6589450/logcat.txt)

https://user-images.githubusercontent.com/40694158/120599297-ffeb4000-c44f-11eb-876b-43f18f1b6115.mp4

* **On OnePlus A3, and Samsung Galaxy Tab A6, the account is still displayed along with the error message**:

Untitled

### PR DESCRIPTION
**Pull request by Mugurell**
Fixes #19797

Previously if an account existed but it wasn't signed in to we would open the fragment to allow the user to sign in to the Firefox account but then [exit early because an account was already existing](https://github.com/mozilla-mobile/fenix/blob/990bfa7e6dd5894d61473a41da6129e6947974e2/app/src/main/java/org/mozilla/fenix/settings/account/TurnOnSyncFragment.kt#L92-L98).

https://user-images.githubusercontent.com/11428869/120995966-942a0f80-c78e-11eb-89fc-ecf6e78baf56.mp4

### Pull Request checklist

- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [x] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

File: app/src/main/java/org/mozilla/fenix/components/toolbar/ToolbarMenu.kt [hunk 1]
```diff
@@ -22,7 +22,7 @@ interface ToolbarMenu {
         object AddToTopSites : Item()
         object InstallPwaToHomeScreen : Item()
         object AddToHomeScreen : Item()
-        data class SyncAccount(val signedIn: Boolean) : Item()
+        data class SyncAccount(val existingAccount: Boolean, val signedIn: Boolean) : Item()
```
Comment (gabrielluong) [inline app/src/main/java/org/mozilla/fenix/components/toolbar/ToolbarMenu.kt:25]: I think we should go with the same language `isAuthenticatedAccount` since `existingAccount` changes the meaning of it from the original intent. I prefix it with `is` to make it super obvious that it represents a `Boolean` when reading the code.

File: app/src/test/java/org/mozilla/fenix/components/toolbar/DefaultBrowserToolbarMenuControllerTest.kt [hunk 2]
```diff
@@ -562,25 +562,40 @@ class DefaultBrowserToolbarMenuControllerTest {
     }
 
     @Test
-    fun `WHEN sync sign in menu item is pressed AND account is signed out THEN navigate to sync sign in`() = runBlockingTest {
-        val item = ToolbarMenu.Item.SyncAccount(false)
-        val directions = BrowserFragmentDirections.actionGlobalTurnOnSync()
-
+    fun `GIVEN account exists and the user is signed in WHEN sync sign in menu item is pressed THEN navigate to account settings`() = runBlockingTest {
```
Comment (gabrielluong) [inline app/src/test/java/org/mozilla/fenix/components/toolbar/DefaultBrowserToolbarMenuControllerTest.kt:565]:
```suggestion
    fun `GIVEN account is authenticated and the user is signed in WHEN sync sign in menu item is pressed THEN navigate to account settings`() = runBlockingTest {
```

**Review by gabrielluong — APPROVED** [review]

File: app/src/test/java/org/mozilla/fenix/components/toolbar/DefaultBrowserToolbarMenuControllerTest.kt (hunk 2 above)
Comment (Mugurell) [reply app/src/test/java/org/mozilla/fenix/components/toolbar/DefaultBrowserToolbarMenuControllerTest.kt:565]: The below test would start with
> GIVEN account is authenticated and the user is not signed in ...
This doesn't sound right.

File: app/src/main/java/org/mozilla/fenix/components/toolbar/ToolbarMenu.kt (hunk 1 above)
Comment (Mugurell) [reply app/src/main/java/org/mozilla/fenix/components/toolbar/ToolbarMenu.kt:25]: I think rather the naming used in fxa should be updated to more closely express the current status of the account.
The documentation for `authenticatedAccount` [says](https://github.com/mozilla-mobile/android-components/blob/bfaf514793dd20f9f12d3f551f9ff3e470f52727/components/service/firefox-accounts/src/main/java/mozilla/components/service/fxa/manager/FxaAccountManager.kt#L325-L338)
"..Returned [OAuthAccount] may need to be re-authenticated."

Based on this and my below comment about the logic used in the app and tests `existingAccount` offers more info about the current status while `authenitcatedAccount` but not signed in seems confusing.

Comment (Mugurell) [reply app/src/main/java/org/mozilla/fenix/components/toolbar/ToolbarMenu.kt:25]: Maybe `accountExists` expresses better that that parameter is for a Boolean?

File: app/src/test/java/org/mozilla/fenix/components/toolbar/DefaultBrowserToolbarMenuControllerTest.kt (hunk 2 above)
Comment (gabrielluong) [reply app/src/test/java/org/mozilla/fenix/components/toolbar/DefaultBrowserToolbarMenuControllerTest.kt:565]:
```suggestion
    fun `GIVEN account is authenticated WHEN sync sign in menu item is pressed THEN navigate to account settings`() = runBlockingTest {
```

File: app/src/main/java/org/mozilla/fenix/components/toolbar/ToolbarMenu.kt (hunk 1 above)
Comment (gabrielluong) [reply app/src/main/java/org/mozilla/fenix/components/toolbar/ToolbarMenu.kt:25]: For this instance, `authenticatedAccount` is defined in https://searchfox.org/mozilla-mobile/source/fenix/app/src/main/java/org/mozilla/fenix/components/accounts/FenixAccountManager.kt#19. It is slightly odd that we used the same naming as the account manager but don't technically return the `OAuthAccount`.

You're right that the authenticated account might need re-auth, but I am not too particular about that detail since it is in some sort of authenticated state. My main point would be to persist the same naming of instead of changing it midway in the ideal case. That said the naming is open to change - I don't particularly see a problem with simply persisting with the `authenticatedAccount` naming due to the fact that it is still in sort of authenticated state and it is known that consumers should check if it needs to re-auth. 

So, I think it boils down to the use case here, which we basically have tri-state (Authenticated, ReAuth, Not Signed in). Perhaps, we should change `FenixAccountManager` to return something that is super clear about the state instead of us having to basically do the same thing all the time with getting the `authenticatedAccount` and checking `signedIn`. If you look at `FenixAccountManager`, the whole logic is kinda duplicated multiple times. 

Feel free to ping me if this wasn't clear. I was going through the code, thinking, writing and revising as my thinking was kinda all over the place.

Comment (Mugurell) [reply app/src/main/java/org/mozilla/fenix/components/toolbar/ToolbarMenu.kt:25]: Maybe `authenticatedAccountExists` would be a more appropriate parameter name?

Comment (Mugurell) [reply app/src/main/java/org/mozilla/fenix/components/toolbar/ToolbarMenu.kt]: After talking with Gabriel I've added a new `accountState` property to FenixAccountManager and will use this simpler way of inferring the directions to which to navigate to.

File: app/src/test/java/org/mozilla/fenix/components/toolbar/DefaultBrowserToolbarMenuControllerTest.kt [hunk 3]
```diff
@@ -562,25 +563,36 @@ class DefaultBrowserToolbarMenuControllerTest {
...
 
-        verify { navController.navigate(directions, null) }
+        verify { navController.navigate(accountProblemDirections, null) }
+    }
+
+    @Test
+    fun `GIVEN account doesn't exist WHEN sync sign in menu item is pressed THEN navigate to sign in`() = runBlockingTest {
+        val turnOnSyncDirections = BrowserFragmentDirections.actionGlobalTurnOnSync()
+        val controller = createController(scope = this, store = browserStore)
+        val signedInUnexistentAccountItem = ToolbarMenu.Item.SyncAccount(AccountState.NO_ACCOUNT)
```
Comment (gabrielluong) [inline app/src/test/java/org/mozilla/fenix/components/toolbar/DefaultBrowserToolbarMenuControllerTest.kt:591]: I think we might prefer to use `signInToSyncItem` just so it aligns with what we actually see visually in the toolbar menu. Otherwise, I would keep it simple and just keep this as `item`.

I will note that it is a bit odd that we decided to change this variable name when we have been calling it `item` and the other ones.

File: app/src/test/java/org/mozilla/fenix/components/toolbar/DefaultBrowserToolbarMenuControllerTest.kt [hunk 4]
```diff
@@ -562,25 +563,36 @@ class DefaultBrowserToolbarMenuControllerTest {
...
         val controller = createController(scope = this, store = browserStore)
+
         controller.handleToolbarItemInteraction(item)
 
-        verify { navController.navigate(directions, null) }
+        verify { navController.navigate(accountProblemDirections, null) }
+    }
+
+    @Test
+    fun `GIVEN account doesn't exist WHEN sync sign in menu item is pressed THEN navigate to sign in`() = runBlockingTest {
```
Comment (gabrielluong) [inline app/src/test/java/org/mozilla/fenix/components/toolbar/DefaultBrowserToolbarMenuControllerTest.kt:588]:
```suggestion
    fun `GIVEN account doesn't exist WHEN sign in to sync menu item is pressed THEN navigate to sign in`() = runBlockingTest {
```

This is about aligning it with the same wording as what we see in the toolbar menu.

File: app/src/test/java/org/mozilla/fenix/components/toolbar/DefaultBrowserToolbarMenuControllerTest.kt [hunk 5]
```diff
@@ -562,25 +563,36 @@ class DefaultBrowserToolbarMenuControllerTest {
...
-        verify { navController.navigate(directions, null) }
+        verify { navController.navigate(accountSettingsDirections, null) }
     }
 
     @Test
-    fun `WHEN sync sign in menu item is pressed AND account is signed in THEN navigate to sync sign in`() = runBlockingTest {
-        val item = ToolbarMenu.Item.SyncAccount(true)
-        val directions = BrowserFragmentDirections.actionGlobalAccountSettingsFragment()
-
+    fun `GIVEN account exists and the user is not signed in WHEN sync sign in menu item is pressed THEN navigate to account problem fragment`() = runBlockingTest {
```
Comment (gabrielluong) [inline app/src/test/java/org/mozilla/fenix/components/toolbar/DefaultBrowserToolbarMenuControllerTest.kt:577]:
```suggestion
    fun `GIVEN account exists and the user is not signed in WHEN sign in to sync menu item is pressed THEN navigate to account problem fragment`() = runBlockingTest {
```

File: app/src/test/java/org/mozilla/fenix/components/toolbar/DefaultBrowserToolbarMenuControllerTest.kt [hunk 6]
```diff
@@ -562,25 +563,36 @@ class DefaultBrowserToolbarMenuControllerTest {
     }
 
     @Test
-    fun `WHEN sync sign in menu item is pressed AND account is signed out THEN navigate to sync sign in`() = runBlockingTest {
-        val item = ToolbarMenu.Item.SyncAccount(false)
-        val directions = BrowserFragmentDirections.actionGlobalTurnOnSync()
-
+    fun `GIVEN account exists and the user is signed in WHEN sync sign in menu item is pressed THEN navigate to account settings`() = runBlockingTest {
```
Comment (gabrielluong) [inline app/src/test/java/org/mozilla/fenix/components/toolbar/DefaultBrowserToolbarMenuControllerTest.kt:566]:
```suggestion
    fun `GIVEN account exists and the user is signed in WHEN sign in to sync menu item is pressed THEN navigate to account settings`() = runBlockingTest {
```

**Review by gabrielluong — APPROVED** [review]

File: app/src/main/java/org/mozilla/fenix/components/accounts/FenixAccountManager.kt [hunk 7]
```diff
@@ -21,6 +21,20 @@ open class FenixAccountManager(context: Context) {
     val accountProfileEmail
```
[the remark this answers is not in the document]
Comment (Mugurell) [reply app/src/main/java/org/mozilla/fenix/components/accounts/FenixAccountManager.kt]: `authenticatedAccount` seem to have valid uses, like [here](https://github.com/mozilla-mobile/fenix/blob/bf3f81d271382eff0780cfdd81f6dea35c13dc7f/app/src/main/java/org/mozilla/fenix/components/toolbar/DefaultToolbarMenu.kt#L336)

`signedToFxa` was used in a similar buggy way for the home menu. Switched that to use `accountState`,  the same used in browser menu.
Since that was it's only use I've removed this method.

[the remark this answers is not in the document]
Comment (gabrielluong) [reply app/src/main/java/org/mozilla/fenix/components/accounts/FenixAccountManager.kt]: Maybe we should also refactor `accountProfileEmail` to encapsulate the  `authenticatedAccount` usage to really discourage it from being used erroneously.  For the `accountProfileEmail` getter, I imagine we can call the `authenticatedAccount` check and just return a nullable string for the email.

That way we can simplify `getSyncItemTitle` to 
```
val accountManager.accountProfileEmail()

return if (!email.isNullOrEmpty()) {            
   email        
} else {            
   context.getString(R.string.sync_menu_sign_in)        
}
```

We probably don't want to ever return the email if the account is not authenticated. I think this will allow us remove the `authenticatedAccount` getter completely or make it private to really discourage it.

```
fun getAccountProfileEmail() : String? {
  return if (accountManager.authenticatedAccount() != null) {
    accountManager.accountProfile()?.email
 } else {
   null
}
```

[the remark this answers is not in the document]
Comment (Mugurell) [reply app/src/main/java/org/mozilla/fenix/components/accounts/FenixAccountManager.kt]: Refactored `accountProfileEmail` to only try and return the email for the account if that is in the authenticated state.
Having this check here, in one place, means consumers will not need to double check the account status.
This also allowed removing the `authenticatedAccount` property from `FenixAccountManager` which now has only two methods, more as helpers for interacting with an account: `accountProfileEmail` and `accountState`.

File: app/src/main/java/org/mozilla/fenix/components/accounts/FenixAccountManager.kt [hunk 8]
```diff
@@ -5,29 +5,55 @@
 package org.mozilla.fenix.components.accounts
 
 import android.content.Context
-import mozilla.components.service.fxa.manager.FxaAccountManager
 import org.mozilla.fenix.ext.components
 
 /**
- * Component which holds a reference to [FxaAccountManager]. Manages account authentication,
- * profiles, and profile state observers.
+ * Contains helper methods for querying FXA account state and it's properties.
```
Comment (gabrielluong) [inline app/src/main/java/org/mozilla/fenix/components/accounts/FenixAccountManager.kt:11]:
```suggestion
 * Contains helper methods for querying the FxA account state and its properties.
```

Instead of FXA, we should use FxA which is its proper acronym. Alternatively, I would just spell out "Firefox Account" for outside readers who aren't aware of our acronym for internal systems.

File: app/src/main/java/org/mozilla/fenix/components/accounts/FenixAccountManager.kt [hunk 9]
```diff
@@ -5,29 +5,55 @@
...
  */
-open class FenixAccountManager(context: Context) {
-    val accountManager = context.components.backgroundServices.accountManager
+class FenixAccountManager(context: Context) {
+    private val accountManager = context.components.backgroundServices.accountManager
 
-    val authenticatedAccount
-        get() = accountManager.authenticatedAccount() != null
+    /**
+     * Returns the FXA email if authenticated in the app, `null` otherwise.
```
Comment (gabrielluong) [inline app/src/main/java/org/mozilla/fenix/components/accounts/FenixAccountManager.kt:17]:
```suggestion
     * Returns the FxA email if authenticated in the app, `null` otherwise.
```

File: app/src/main/java/org/mozilla/fenix/components/accounts/FenixAccountManager.kt [hunk 10]
```diff
@@ -5,29 +5,55 @@
...
+     */
+    val accountProfileEmail: String?
+        get() = if (accountState == AccountState.AUTHENTICATED) {
+            accountManager.accountProfile()?.email
+        } else {
+            null
+        }
+
+    /**
+     * The current state of the FXA account. See [AccountState].
```
Comment (gabrielluong) [inline app/src/main/java/org/mozilla/fenix/components/accounts/FenixAccountManager.kt:27]:
```suggestion
     * The current state of the FxA account. See [AccountState].
```

File: app/src/main/java/org/mozilla/fenix/components/accounts/FenixAccountManager.kt [hunk 11]
```diff
@@ -5,29 +5,55 @@
...
+            } else {
+                AccountState.AUTHENTICATED
+            }
+        }
+}
 
-    val accountProfileEmail
-        get() = accountManager.accountProfile()?.email
+/**
+ * General states as an overview of the current FXA account.
```
Comment (gabrielluong) [inline app/src/main/java/org/mozilla/fenix/components/accounts/FenixAccountManager.kt:42]:
```suggestion
 * General states as an overview of the current FxA account.
```

File: app/src/main/java/org/mozilla/fenix/components/accounts/FenixAccountManager.kt [hunk 12]
```diff
@@ -5,29 +5,55 @@
...
+ */
+enum class AccountState {
+    /**
+     * There is no known FXA account.
```
Comment (gabrielluong) [inline app/src/main/java/org/mozilla/fenix/components/accounts/FenixAccountManager.kt:46]:
```suggestion
     * There is no known FxA account.
```

File: app/src/main/java/org/mozilla/fenix/components/accounts/FenixAccountManager.kt [hunk 13]
```diff
@@ -5,29 +5,55 @@
...
+     */
+    NO_ACCOUNT,
 
     /**
-     * Check if the current account is signed in and authenticated.
+     * An FXA account exists but needs to be re-authenticated with.
```
Comment (gabrielluong) [inline app/src/main/java/org/mozilla/fenix/components/accounts/FenixAccountManager.kt:51]:
```suggestion
     * An FxA account exists but needs to be re-authenticated.
```

File: app/src/main/java/org/mozilla/fenix/components/accounts/FenixAccountManager.kt [hunk 14]
```diff
@@ -5,29 +5,55 @@
...
      */
-    fun signedInToFxa(): Boolean {
-        val account = accountManager.authenticatedAccount()
-        val needsReauth = accountManager.accountNeedsReauth()
+    NEEDS_REAUTHENTICATION,
 
-        return account != null && !needsReauth
-    }
+    /**
+     * An FXA account exists and the user is currently signed in into it.
```
Comment (gabrielluong) [inline app/src/main/java/org/mozilla/fenix/components/accounts/FenixAccountManager.kt:56]:
```suggestion
     * An FxA account exists and the user is currently signed into it.
```

File: app/src/main/java/org/mozilla/fenix/components/toolbar/DefaultToolbarMenu.kt [hunk 15]
```diff
@@ -333,22 +333,17 @@ open class DefaultToolbarMenu(
...
     private fun getSyncItemTitle(): String {
-        val authenticatedAccount = accountManager.authenticatedAccount
-        val email = accountManager.accountProfileEmail
-
-        return if (authenticatedAccount && !email.isNullOrEmpty()) {
-            email
-        } else {
-            context.getString(R.string.sync_menu_sign_in)
-        }
+        return accountManager.accountProfileEmail ?: context.getString(R.string.sync_menu_sign_in)
```
Comment (gabrielluong) [inline app/src/main/java/org/mozilla/fenix/components/toolbar/DefaultToolbarMenu.kt:336]: Could probably drop the `{ return }` with using `=`

File: app/src/main/java/org/mozilla/fenix/home/HomeMenu.kt [hunk 16]
```diff
@@ -91,22 +92,15 @@ class HomeMenu(
...
     private fun getSyncItemTitle(): String {
-        val authenticatedAccount = accountManager.authenticatedAccount
-        val email = accountManager.accountProfileEmail
-
-        return if (authenticatedAccount && !email.isNullOrEmpty()) {
-            email
-        } else {
-            context.getString(R.string.sync_menu_sign_in)
-        }
+        return accountManager.accountProfileEmail ?: context.getString(R.string.sync_menu_sign_in)
```
Comment (gabrielluong) [inline app/src/main/java/org/mozilla/fenix/home/HomeMenu.kt:95]: Same as above, but I will also note the duplication of code between the 2. No idea, if we have a util class that happens to be used by both menus that we can throw this into, if not, don't worry about it for now.

File: app/src/test/java/org/mozilla/fenix/components/toolbar/DefaultBrowserToolbarMenuControllerTest.kt [hunk 17]
```diff
@@ -562,25 +563,36 @@ class DefaultBrowserToolbarMenuControllerTest {
...
 
-        verify { navController.navigate(directions, null) }
+        verify { navController.navigate(accountProblemDirections, null) }
+    }
+
+    @Test
+    fun `GIVEN account doesn't exist WHEN sign in to sync menu item is pressed THEN navigate to sign in`() = runBlockingTest {
+        val turnOnSyncDirections = BrowserFragmentDirections.actionGlobalTurnOnSync()
+        val controller = createController(scope = this, store = browserStore)
+        val signedInUnexistentAccountItem = ToolbarMenu.Item.SyncAccount(AccountState.NO_ACCOUNT)
```
Comment (gabrielluong) [inline app/src/test/java/org/mozilla/fenix/components/toolbar/DefaultBrowserToolbarMenuControllerTest.kt:591]: I think my last comment about this was to name this as `signInToSyncItem` so it aligns with what we see visually. I don't think we should overthink this and just call it `item` as we have done for all the other tests despite the different account state passed.

 ```suggestion
        val item = ToolbarMenu.Item.SyncAccount(AccountState.NO_ACCOUNT)
```

**Review by gabrielluong — APPROVED** [review]

File: app/src/main/java/org/mozilla/fenix/components/accounts/FenixAccountManager.kt (hunk 8 above)
Comment (Mugurell) [reply app/src/main/java/org/mozilla/fenix/components/accounts/FenixAccountManager.kt:11]: Thanks, will use "Firefox Account".

**Comment by Mugurell** [comment]
`deleteAllHistory` ui test failed because of
>  androidx.test.espresso.NoMatchingViewException: No views in hierarchy found matching: (with id: org.mozilla.fenix.debug:id/history_empty_view and view has effective visibility=VISIBLE) 

Seems unrelated. Restarting CI.
