### PR TITLE
For #25044 - Remove the broken code for focusing the newly created collection

### LINKED ISSUE #25044: Remove the broken code for focusing the newly created collection

### PR DESCRIPTION
**Pull request by gabrielluong**
This functionality seems broken for a long time now.
It's importance and whether to reimplement it is to be re-assessed in
https://github.com/mozilla-mobile/fenix/issues/24389

Fixes #25044

### Pull Request checklist

- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

File: app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayFragment.kt [hunk 1]
```diff
@@ -568,8 +566,7 @@ class TabsTrayFragment : AppCompatDialogFragment() {
                 .anchorWithAction(getSnackbarAnchor()) {
                     findNavController().navigate(
                         TabsTrayFragmentDirections.actionGlobalHome(
-                            focusOnAddressBar = false,
-                            focusOnCollection = collectionToSelect.orDefault()
+                            focusOnAddressBar = false
```
Comment (MozillaNoah) [inline app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayFragment.kt:569]: nit: the diffs might be a little more concise if we keep the trailing commas

**Review by MozillaNoah — APPROVED** [review]
