### PR TITLE
Fixes #10109: Adds content description for browse privately card content

### LINKED ISSUE #10109: FNX-3291 ⁃ [Bug][a11y] TalkBack-Browse Privately-Icon's description is not correctly identified
## Prerequisites
* Have Talk Back enabled
* Have a clean profile

### Steps to reproduce
1. Open app and on the Onboarding screen go to "Browse Privately" section
1. Tap on the second sentence from the section.("Open a private tab once: Tap the "browsing" icon.")
    1. Expected behavior
The private browsing icon is read correctly by talk back.
    1. Actual behavior
The private browsing icon is read as "percent".
    1. Device information

* Android device: Samsung Galaxy S9 (Android 8), Sony Xperia Z5 (Android 7)
* Fenix version: Nightly 4/22

### PR DESCRIPTION
**Pull request by ValentinTimisica**
### Pull Request checklist

- [x] **Tests**: This PR does not include thorough tests.
- [x] **Screenshots**: This PR does not include screenshots or GIFs.
- [x] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md).

### After merge
- [ ] **Milestone**: Make sure issues finished by this pull request are added to the [milestone](https://github.com/mozilla-mobile/fenix/milestones) of the version currently in development.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

File: app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/OnboardingPrivateBrowsingViewHolder.kt [hunk 1]
```diff
@@ -45,6 +45,7 @@ class OnboardingPrivateBrowsingViewHolder(
         }
 
         view.description_text_once.text = text
+        view.description_text_once.contentDescription = String.format(text.toString(), view.header_text.text)
         view.contentDescription = String.format(text.toString(), view.header_text.text)
```
Comment (mcarare) [inline app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/OnboardingPrivateBrowsingViewHolder.kt:49]: This should be removed. The bug was that the content description was added to the wrong view.

Comment (mcarare) [inline app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/OnboardingPrivateBrowsingViewHolder.kt:49]: This should be removed. The bug was that the content description was added to the wrong view.

Comment (mcarare) [inline app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/OnboardingPrivateBrowsingViewHolder.kt:49]: This should be removed. The bug was that the content description was added to the wrong view.
