### PR TITLE
For #27579 - Fix broken previews for MessageCard

### LINKED ISSUE #27579: Fix previews in `MessageCard` Composable
The `MessageCard` Composable currently takes in a Nimbus-driven object which breaks the previews, when the Composable really only needs three elements:

1. Title text
2. Message text
3. Button text

The `message: Message` parameter should be refactored so only the actual text is passed-in.

```
@Composable
fun MessageCard(
    titleText: String?,
    messageText: String?,
    buttonText: String?,
    onClick: () -> Unit,
    onCloseButtonClick: () -> Unit,
) {
   ...
}
```

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21881)

### PR DESCRIPTION
**Pull request by MozillaNoah**
### Pull Request checklist

- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### QA

- [ ] **QA Needed**

### To download an APK when reviewing a PR (after all CI tasks finished running):
1. Click on `Checks` at the top of the PR page.
2. Click on the `firefoxci-taskcluster` group on the left to expand all tasks.
3. Click on the `build-debug` task.
4. Click on `View task in Taskcluster` in the new `DETAILS` section.
5. The APK links should be on the right side of the screen, named for each CPU architecture.

### GitHub Automation
Fixes #27579

### CODE REVIEW

File: app/src/main/java/org/mozilla/fenix/compose/MessageCard.kt [hunk 1]
```diff
@@ -27,34 +28,33 @@ import androidx.compose.ui.text.style.TextOverflow
...
 import org.mozilla.fenix.theme.FirefoxTheme
-import org.mozilla.fenix.theme.Theme
 
 /**
  * Message Card.
  *
- * @param message [Message] that holds a representation of GleanPlum message from Nimbus.
+ * @param messageText String of the message card's body.
+ * @param titleText String of the message card's title. If null, it won't be shown.
+ * @param buttonText String of the message card's button. If null, the button won't be shown.
```
Comment (gabrielluong) [inline app/src/main/java/org/mozilla/fenix/compose/MessageCard.kt:40]:
```suggestion
 * @param messageText The message card's body text to be displayed.
 * @param titleText An optional title of message card. If null is provided, the title will not be shown.
 * @param buttonText An optional button text of the message card. If null is provided, the button won't be shown.
```

**Review by gabrielluong — APPROVED** [review]
