### PR TITLE
Bug 1814232 - Consume upstream CFRPopupFullscreenLayout

### LINKED ISSUE #28324: Consume upstream CFRPopupFullscreenLayout
Now that we have upstream [CFRPopupFullscreenLayout](https://searchfox.org/mozilla-mobile/source/firefox-android/android-components/components/compose/cfr/src/main/java/mozilla/components/compose/cfr/CFRPopupFullscreenLayout.kt) to AC. We should deprecate and migrate away from using Fenix's [CFRPopupFullscreenLayout](https://searchfox.org/mozilla-mobile/source/fenix/app/src/main/java/org/mozilla/fenix/compose/cfr/CFRPopupFullscreenLayout.kt). We saw issues from using `GeckoOrientation` in Fenix, but this has been mitigated in AC where it introduced its own system orientation helper.  See https://mozilla.slack.com/archives/CKM7DLL67/p1672157172991059

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22201)

### PR DESCRIPTION
**Pull request by gabrielluong**
### Pull Request checklist

- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### QA

- [x] **QA Needed**

### To download an APK when reviewing a PR (after all CI tasks finished running):
1. Click on `Checks` at the top of the PR page.
2. Click on the `firefoxci-taskcluster` group on the left to expand all tasks.
3. Click on the `build-debug` task.
4. Click on `View task in Taskcluster` in the new `DETAILS` section.
5. The APK links should be on the right side of the screen, named for each CPU architecture.

### GitHub Automation
Fixes #28324

### CODE REVIEW

File: app/src/test/java/org/mozilla/fenix/components/toolbar/BrowserToolbarCFRPresenterTest.kt [hunk 1]
```diff
@@ -178,31 +178,6 @@ class BrowserToolbarCFRPresenterTest {
         assertNotNull(presenter.tcpCfrPopup)
     }
 
-    @Test
```
Comment (gabrielluong) [inline app/src/test/java/org/mozilla/fenix/components/toolbar/BrowserToolbarCFRPresenterTest.kt:181]:
```
e: /home/runner/work/fenix/fenix/app/src/test/java/org/mozilla/fenix/components/toolbar/BrowserToolbarCFRPresenterTest.kt: (195, 37): Cannot access 'text': it is internal in 'CFRPopup'
e: /home/runner/work/fenix/fenix/app/src/test/java/org/mozilla/fenix/components/toolbar/BrowserToolbarCFRPresenterTest.kt: (196, 37): Cannot access 'anchor': it is internal in 'CFRPopup'
e: /home/runner/work/fenix/fenix/app/src/test/java/org/mozilla/fenix/components/toolbar/BrowserToolbarCFRPresenterTest.kt: (197, 35): Cannot access 'DEFAULT_WIDTH': it is internal in 'Companion'
e: /home/runner/work/fenix/fenix/app/src/test/java/org/mozilla/fenix/components/toolbar/BrowserToolbarCFRPresenterTest.kt: (197, 56): Cannot access 'properties': it is internal in 'CFRPopup'
e: /home/runner/work/fenix/fenix/app/src/test/java/org/mozilla/fenix/components/toolbar/BrowserToolbarCFRPresenterTest.kt: (198, 63): Cannot access 'properties': it is internal in 'CFRPopup'
e: /home/runner/work/fenix/fenix/app/src/test/java/org/mozilla/fenix/components/toolbar/BrowserToolbarCFRPresenterTest.kt: (199, 27): Cannot access 'properties': it is internal in 'CFRPopup'
e: /home/runner/work/fenix/fenix/app/src/test/java/org/mozilla/fenix/components/toolbar/BrowserToolbarCFRPresenterTest.kt: (200, 27): Cannot access 'properties': it is internal in 'CFRPopup'
e: /home/runner/work/fenix/fenix/app/src/test/java/org/mozilla/fenix/components/toolbar/BrowserToolbarCFRPresenterTest.kt: (201, 28): Cannot access 'properties': it is internal in 'CFRPopup'
e: /home/runner/work/fenix/fenix/app/src/test/java/org/mozilla/fenix/components/toolbar/BrowserToolbarCFRPresenterTest.kt: (202, 35): Cannot access 'DEFAULT_INDICATOR_START_OFFSET': it is internal in 'Companion'
e: /home/runner/work/fenix/fenix/app/src/test/java/org/mozilla/fenix/components/toolbar/BrowserToolbarCFRPresenterTest.kt: (202, 73): Cannot access 'properties': it is internal in 'CFRPopup'
e: /home/runner/work/fenix/fenix/app/src/test/java/org/mozilla/fenix/components/toolbar/BrowserToolbarCFRPresenterTest.kt: (228, 33): Cannot access 'onDismiss': it is internal in 'CFRPopup'
e: /home/runner/work/fenix/fenix/app/src/test/java/org/mozilla/fenix/components/toolbar/BrowserToolbarCFRPresenterTest.kt: (232, 33): Cannot access 'onDismiss': it is internal in 'CFRPopup'
```
Removed these tests because we can't access the properties.

**Review by MozillaNoah — APPROVED** [review]

File: app/src/main/java/org/mozilla/fenix/components/toolbar/BrowserToolbarCFRPresenter.kt [hunk 2]
```diff
@@ -93,44 +95,63 @@ class BrowserToolbarCFRPresenter(
...
-                        SupportUtils.getSumoURLForTopic(
-                            context,
-                            TOTAL_COOKIE_PROTECTION,
+            text = {
+                FirefoxTheme {
+                    Text(
+                        text = context.getString(R.string.tcp_cfr_message),
+                        modifier = Modifier.padding(
+                            end = 24.dp, // 8.dp extra padding to the "X" icon
                         ),
```
Comment (Mugurell) [inline app/src/main/java/org/mozilla/fenix/components/toolbar/BrowserToolbarCFRPresenter.kt:127]: Here and below: This padding won't be needed. The AC CFR will add this padding to ensure proper positioning (and the result will be the same UI Focus/Fenix had before).

**Review by Mugurell — APPROVED** [review]
LGTM, thank you!
Tested and looks/works good.
Just need to remove the extra padding added to `text`.

**Comment by Mugurell** [comment]
@gabrielluong I see some conflicts in the meantime.
Having this in Fenix would allow it to consume the update from https://github.com/mozilla-mobile/firefox-android/pull/524 and fix https://github.com/mozilla-mobile/fenix/issues/27662 which is important for the TCP release to a wider audience.
I know you're helping with the migration to the monorepo so I can also help finishing the work here if you don't have the cycles for this.

**Comment by gabrielluong** [comment]
> @gabrielluong I see some conflicts in the meantime. Having this in Fenix would allow it to consume the update from [mozilla-mobile/firefox-android#524](https://github.com/mozilla-mobile/firefox-android/pull/524) and fix #27662 which is important for the TCP release to a wider audience. I know you're helping with the migration to the monorepo so I can also help finishing the work here if you don't have the cycles for this.

I will get to this
