### PR TITLE
Closes #15812: Check for a null context during onScanResult

### LINKED ISSUE #15812: IllegalStateException: Fragment PairFragment{76fc44d} (c18ac462-998c-4c18-a3bb-2c9f6b9e6b7f)} not attached to a context.
https://sentry.prod.mozaws.net/operations/firefox-nightly/issues/9752170/?referrer=github_plugin

```
IllegalStateException: Fragment PairFragment{76fc44d} (c18ac462-998c-4c18-a3bb-2c9f6b9e6b7f)} not attached to a context.
    at org.mozilla.fenix.settings.PairFragment$onViewCreated$2.invoke(PairFragment.kt:3)
...
(7 additional frame(s) were not displayed)

Fragment PairFragment{76fc44d} (c18ac462-998c-4c18-a3bb-2c9f6b9e6b7f)} not attached to a context.
```

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-8032)

### PR DESCRIPTION
**Pull request by grigoryk**
### Pull Request checklist

- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

File: app/src/main/java/org/mozilla/fenix/settings/PairFragment.kt [hunk 1]
```diff
@@ -37,6 +37,15 @@ class PairFragment : Fragment(R.layout.fragment_pair), UserInteractionHandler {
                     requestPermissions(permissions, REQUEST_CODE_CAMERA_PERMISSIONS)
                 },
                 onScanResult = { pairingUrl ->
+                    // By the time we get a scan result, we may not be attached to the context anymore.
+                    // See https://github.com/mozilla-mobile/fenix/issues/15812
+                    if (context == null) {
+                        findNavController(this@PairFragment).popBackStack(
```
Comment (ekager) [inline app/src/main/java/org/mozilla/fenix/settings/PairFragment.kt:43]: you can just use the ext fun off of `Fragment` -> `findNavController()`

**Review by ekager — APPROVED** [review]
r+ w 1 com
