### PR TITLE
Fixes #10674: Add SignInView only once

### LINKED ISSUE #10674: FNX-4462 ⁃ [Bug] Sign in to see synced bookmarks inflated too many times
### Prerequisites
Don't be logged in into an Fxa account.

### Steps to reproduce
* From Home menu go to `Bookmarks`->`Desktop Bookmarks`
* Press Recents apps button and then select Fenix (you can do this multiple times).

### Expected behavior
* Only one `Sign in to see synced bookmarks` button should appear on the screen.

### Actual behavior
* `Sign in to see synced bookmarks` appears multiple times on the screen.

### Device information
* Android device: Samsung Galaxy Note 10 (Android 10)
* Fenix version: latest from master

### Additional info
* [Video](https://drive.google.com/file/d/1mtS0vnyLLwYYyd_97qBaN5NzIk8J5wGx/view?usp=sharing)

### PR DESCRIPTION
**Pull request by ValentinTimisica**
### Pull Request checklist

- [x] **Tests**: This PR does not include thorough tests. Small UI change.
- [x] **Screenshots**: This PR does not include screenshots or GIFs of the changes made.
- [x] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md).

### After merge
- [ ] **Milestone**: Make sure issues finished by this pull request are added to the [milestone](https://github.com/mozilla-mobile/fenix/milestones) of the version currently in development.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

File: app/src/main/java/org/mozilla/fenix/library/bookmarks/BookmarkFragment.kt [hunk 1]
```diff
@@ -147,7 +148,7 @@ class BookmarkFragment : LibraryPageFragment<BookmarkNode>(), UserInteractionHan
         if (currentGuid == BookmarkRoot.Root.id &&
             requireComponents.backgroundServices.accountManager.authenticatedAccount() == null
         ) {
-            view?.let { SignInView(it.bookmarkLayout, findNavController()) }
+            signInView = view?.let { SignInView(it.bookmarkLayout, findNavController()) }
```
Comment (sblatz) [inline app/src/main/java/org/mozilla/fenix/library/bookmarks/BookmarkFragment.kt:151]: minor nit, but instead of adding/removing, can we just flip the visibility of it? `View.GONE` & `View.VISIBLE`?

File: app/src/main/java/org/mozilla/fenix/library/bookmarks/BookmarkFragment.kt [hunk 2]
```diff
@@ -57,6 +57,7 @@ class BookmarkFragment : LibraryPageFragment<BookmarkNode>(), UserInteractionHan
 
     private lateinit var bookmarkStore: BookmarkFragmentStore
     private lateinit var bookmarkView: BookmarkView
+    private var signInView: SignInView? = null
```
Comment (BranescuMihai) [inline app/src/main/java/org/mozilla/fenix/library/bookmarks/BookmarkFragment.kt:60]: Please use lateinit var since you're always initialising it so it shouldn't be nullable

File: app/src/main/java/org/mozilla/fenix/library/bookmarks/BookmarkFragment.kt [hunk 3]
```diff
@@ -97,6 +98,8 @@ class BookmarkFragment : LibraryPageFragment<BookmarkNode>(), UserInteractionHan
         )
 
         bookmarkView = BookmarkView(view.bookmarkLayout, bookmarkInteractor)
+        signInView = SignInView(view.bookmarkLayout, findNavController())
+        signInView?.view?.visibility = View.GONE
```
Comment (BranescuMihai) [inline app/src/main/java/org/mozilla/fenix/library/bookmarks/BookmarkFragment.kt:102]: Nit: Once you change to lateinit var, please remove the unnecessary `?`s
