### PR TITLE
Closes #16603: Disable pull down when in fullscreen

### LINKED ISSUE #16603: [Bug] Pull to refresh triggered on full screen videos
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
Open a video in full screen on any website (for me it's YouTube) 
Swipe down to trigger pull to refresh
### Expected behavior
Pull to refresh not triggered while on full screen. 

### Actual behavior
It's triggered on full screen. 

Screenshot_20201116-194646_Firefox_Nightly

### Device information

* Android device: Xperia XZ1 Android 10 
* Fenix version: Nightly

### PR DESCRIPTION
**Pull request by rocketsroger**
### Pull Request checklist

- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

File: app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt [hunk 1]
```diff
@@ -668,7 +668,7 @@ abstract class BaseBrowserFragment : Fragment(), UserInteractionHandler,
                     .collect { tab -> pipModeChanged(tab) }
             }
 
-            view.swipeRefresh.isEnabled = shouldPullToRefreshBeEnabled()
+            view.swipeRefresh.isEnabled = shouldPullToRefreshBeEnabled(false)
```
Comment (ekager) [inline app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt:671]: nit - lets show the named param here

File: app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt [hunk 2]
```diff
@@ -798,10 +798,10 @@ abstract class BaseBrowserFragment : Fragment(), UserInteractionHandler,
     }
 
     @VisibleForTesting
-    internal fun shouldPullToRefreshBeEnabled(): Boolean {
+    internal fun shouldPullToRefreshBeEnabled(inFullScreen: Boolean): Boolean {
         return FeatureFlags.pullToRefreshEnabled &&
                 requireContext().settings().isPullToRefreshEnabledInBrowser &&
-                !(requireActivity() as HomeActivity).isImmersive
```
Comment (ekager) [inline app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt:804]: Just checking - does `isImmersive` mean the same as `inFullscreen` always?

**Review by ekager — APPROVED** [review]

File: app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt (hunk 2 above)
Comment (rocketsroger) [reply app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt:804]: No, I found the hard way that `isImmersive` check is unreliable in some cases.
