### PR TITLE
Closes #784 - After session timeout, pop everything to home

### LINKED ISSUE #784: After a sleep period, the app opens with a black screen
## Steps to reproduce
1. Open a tab, e.g. google.com
2. Leave the device at least ~15-20 min in sleep mode.
3. Unlock the device and check the app.
note:  The device I used has sleep set after 30 seconds and a lock screen.
### Expected behavior
The app is displayed normally.
### Actual behavior
The app's page view is black, the URL bar is empty.

### Device information

* Android device: Huawei P20 lite (Android 8.0), 
* Fenix version: 1.0.1909 (Build #10601230)

### PR DESCRIPTION
**Pull request by ekager**

### CODE REVIEW

File: app/src/main/java/org/mozilla/fenix/HomeActivity.kt [hunk 1]
```diff
@@ -65,6 +65,10 @@ open class HomeActivity : AppCompatActivity() {
 
     override fun onResume() {
         super.onResume()
+        // There is no session, or it has timed out; we should pop everything to home
+        if (components.core.sessionStorage.current() == null) {
```
Comment (colintheshots) [inline app/src/main/java/org/mozilla/fenix/HomeActivity.kt]: Should we check that we're not in a custom tab? Otherwise, this change is much-needed. Thanks!

Comment (ekager) [reply app/src/main/java/org/mozilla/fenix/HomeActivity.kt]: I tested this with custom tabs and it seems to work, it will pop but only in the main Fenix app (f the tab has timed out) and not the custom tab browsing
