### PR TITLE
Fix #7649: Fix missing NOT in asFeatureWebChannelsDisabled check

### LINKED ISSUE #7649: [Bug] Fix missing NOT in asFeatureWebChannelsDisabled check
The PR is to remove Fretboard accidentally removed a NOT in one of the if checks. This ticket is to track replacing the missing NOT in the code.

It's line 438 of BaseBrowserFragment.kt.

### PR DESCRIPTION
**Pull request by colintheshots**
### Pull Request checklist

- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [x] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### After merge
- [ ] **Milestone**: Make sure issues finished by this pull request are added to the [milestone](https://github.com/mozilla-mobile/fenix/milestones) of the version currently in development.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

File: app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt [hunk 1]
```diff
@@ -435,7 +435,7 @@ abstract class BaseBrowserFragment : Fragment(), UserInteractionHandler, Session
             }
 
             @Suppress("ConstantConditionIf")
-            if (FeatureFlags.asFeatureWebChannelsDisabled) {
+            if (!FeatureFlags.asFeatureWebChannelsDisabled) {
```
Comment (mcomella) [inline app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt]: No action needed: confirmed that this `!` should have been there: https://github.com/mozilla-mobile/fenix/pull/7510/files#diff-bf0b57d467da0e3d5ef96c23fc828376R438
