### PR TITLE
For #23966 - Migrate MessageCardViewHolder to Compose

### LINKED ISSUE #23966: Migrate MessageCardViewHolder to Compose
Breakage of https://github.com/mozilla-mobile/fenix/issues/22755

Refers to [MessageCardViewHolder](https://github.com/mozilla-mobile/fenix/blob/main/app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/MessageCardViewHolder.kt) which is used to show a card letting users easily set Fenix as the default browser.

The compose version can be added to the current RecyclerView but before doing so we should ensure there will be no performance regression introduced.
To profile the differences the steps from https://github.com/mozilla-mobile/fenix/issues/21854#issuecomment-1049392266 can be used.

### PR DESCRIPTION
**Pull request by sarah541**
Fixes #23966 

### Pull Request checklist

- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

File: app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/MessageCardViewHolder.kt [hunk 1]
```diff
@@ -5,53 +5,230 @@
...
-    companion object {
-        internal const val LAYOUT_ID = R.layout.nimbus_message_card
-        private const val CLOSE_BUTTON_EXTRA_DPS = 38
+/**
+ * Message Card Button.
+ *
+ * @param onClick Invoked when user clicks on button.
+ */
+
+@Suppress("LongMethod")
```
Comment (gabrielluong) [inline app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/MessageCardViewHolder.kt:185]: nit unnecessary new line, and is this actually a LongMethod?

File: app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/MessageCardViewHolder.kt [hunk 2]
```diff
@@ -5,53 +5,230 @@
...
+/**
+ * Message Card.
+ *
+ * @param message contains title and description of message.
+ * @param onMessageClicked Invoked when user clicks on the button.
+ * @param onMessageClosedClicked Invoked when user clicks on close button to remove message.
+ */
+@Suppress("LongMethod")
+@Composable
+fun MessageCardPlaceHolder(
```
Comment (gabrielluong) [inline app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/MessageCardViewHolder.kt:92]:
```suggestion
fun MessageCard(
```

File: app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/MessageCardViewHolder.kt [hunk 3]
```diff
@@ -5,53 +5,230 @@
...
+                        Icon(
+                            painter = painterResource(R.drawable.ic_close),
+                            contentDescription = stringResource(
+                                R.string.remove_home_collection_placeholder_content_description
+                            ),
+                            tint = FirefoxTheme.colors.iconPrimary
+                        )
+                    }
+                }
+                PrimaryText(
```
Comment (gabrielluong) [inline app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/MessageCardViewHolder.kt:140]: Add a new line before this

File: app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/MessageCardViewHolder.kt [hunk 4]
```diff
@@ -5,53 +5,230 @@
...
+        Column(
+            Modifier
+                .padding(all = 16.dp)
+                .fillMaxWidth()
+        ) {
+            if (!message.data.title.isNullOrBlank()) {
+                Row(
+                    modifier = Modifier.fillMaxWidth(),
+                ) {
+
```
Comment (gabrielluong) [inline app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/MessageCardViewHolder.kt:119]: nit: unnecessary newl ine

File: app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/MessageCardViewHolder.kt [hunk 5]
```diff
@@ -5,53 +5,230 @@
...
+                    SectionHeader(
+                        text = message.data.title!!,
```
Comment (gabrielluong) [inline app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/MessageCardViewHolder.kt:121]: Can you assign the `message.data.title` to a variable to get around the `!!` since we check `isNullOrBlank` above

File: app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/MessageCardViewHolder.kt [hunk 6]
```diff
@@ -5,53 +5,230 @@
...
+        Text(
+            text = stringResource(R.string.preferences_set_as_default_browser),
+            modifier = Modifier.align(Alignment.CenterVertically),
+            color = FirefoxTheme.colors.textOnColorPrimary,
+            fontSize = 14.sp,
+            fontWeight = FontWeight.SemiBold,
+            letterSpacing = 0.sp,
+            maxLines = 2
+        )
+    }
```
Comment (gabrielluong) [inline app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/MessageCardViewHolder.kt:206]: I am expecting that this will be refactored into its own component as discussed from your CollectionsPlaceholder work. When we do have the button as its own component, I would drop `MessageCardButton` wrapper and use the button component directly

File: app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/MessageCardViewHolder.kt (hunk 5 above)
Comment (Amejia481) [reply app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/MessageCardViewHolder.kt:121]: In the original implementation, when we get a null title label we hide the UI for it.

File: app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/MessageCardViewHolder.kt (hunk 1 above)
Comment (sarah541) [reply app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/MessageCardViewHolder.kt:185]: It said while running detekt that it is a long method.

File: app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/MessageCardViewHolder.kt (hunk 5 above)
Comment (sarah541) [reply app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/MessageCardViewHolder.kt:121]: @Amejia481 Right, hence the conditional title

```
if (!message.data.title.isNullOrBlank()) {
                Row(
                    modifier = Modifier.fillMaxWidth(),
                ) {
                   SectionHeader(
                        text = message.data.title!!,
```

Comment (Amejia481) [reply app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/MessageCardViewHolder.kt:121]: 👍🏽

File: app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/MessageCardViewHolder.kt (hunk 1 above)
Comment (gabrielluong) [reply app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/MessageCardViewHolder.kt:185]: It only appears like MessageCardPlaceHolder is a LongMethod from my point of view. MessageCardButton is less than 60 lines.

File: app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/MessageCardViewHolder.kt [hunk 7]
```diff
@@ -5,53 +5,230 @@
...
+
+                    SectionHeader(
+                        text = message.data.title!!,
+                        modifier = Modifier
+                            .weight(1f)
+                            .padding(bottom = 10.dp)
+                    )
+
+                    IconButton(
+                        modifier = Modifier.size(20.dp),
```
Comment (Amejia481) [inline app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/MessageCardViewHolder.kt:128]: Should this be 48dp be meet the [minimal touch size for accessibility](https://support.google.com/accessibility/android/answer/7101858?hl=en)? :)

Comment (MozillaNoah) [reply app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/MessageCardViewHolder.kt:128]: Looking at the internals of `IconButton`, it seems that regardless of the size specified, it will still have a 48x48 tap target size. During IconButton's setup, it calls `.minimumTouchTargetSize()` on its root `Modifier`

Comment (Amejia481) [reply app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/MessageCardViewHolder.kt:128]: Awesome 🙌🏽 !

File: app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/MessageCardViewHolder.kt [hunk 8]
```diff
@@ -5,53 +5,230 @@
...
+    private val interactor: SessionControlInteractor,
+) : ComposeViewHolder(composeView, viewLifecycleOwner) {
+
+    private lateinit var messageGlobal: Message
 
     fun bind(message: Message) {
-        val binding = NimbusMessageCardBinding.bind(itemView)
+        messageGlobal = message
+        interactor.onMessageDisplayed(message)
+    }
```
Comment (Amejia481) [inline app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/MessageCardViewHolder.kt:66]: Checking on other viewholders that are already using compose like [RecentlyVisitedViewHolder](https://github.com/mozilla-mobile/fenix/blob/71ac549b8b32466b16d318a1801c4b2b747fd0ce/app/src/main/java/org/mozilla/fenix/home/recentvisits/view/RecentlyVisitedViewHolder.kt#L44), [RecentBookmarksViewHolder](https://github.com/mozilla-mobile/fenix/blob/71ac549b8b32466b16d318a1801c4b2b747fd0ce/app/src/main/java/org/mozilla/fenix/home/recentbookmarks/view/RecentBookmarksViewHolder.kt#L36) and [RecentTabViewHolder]( https://github.com/mozilla-mobile/fenix/blob/71ac549b8b32466b16d318a1801c4b2b747fd0ce/app/src/main/java/org/mozilla/fenix/home/recenttabs/view/RecentTabViewHolder.kt#L56), it looks like they are no using the `bind` fun to pass state, it looks like they are observing the state on the store using `observeAsComposableState`, maybe we should follow the same pattern? WDYT?

File: app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/MessageCardViewHolder.kt [hunk 9]
```diff
@@ -5,53 +5,230 @@
...
+            ),
+        shape = RoundedCornerShape(8.dp),
+        backgroundColor = FirefoxTheme.colors.layer2,
+    ) {
+        Column(
+            Modifier
+                .padding(all = 16.dp)
+                .fillMaxWidth()
+        ) {
+            if (!message.data.title.isNullOrBlank()) {
```
Comment (Amejia481) [inline app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/MessageCardViewHolder.kt:115]: Could we add the condition to just cover the `SectionHeader` ? As it looks like we are duplicating `IconButton` and `PrimaryText` in both part of the condition.

 
```kotlin
            if (!message.data.title.isNullOrBlank()) {
                Row(
                    modifier = Modifier.fillMaxWidth(),
                ) {

                    SectionHeader(
                        text = message.data.title!!,
                        modifier = Modifier
                            .weight(1f)
                            .padding(bottom = 10.dp)
                    )

                    IconButton(
                        modifier = Modifier.size(20.dp),
                        onClick = onMessageClosedClicked
                    ) {
                        Icon(
                            painter = painterResource(R.drawable.ic_close),
                            contentDescription = stringResource(
                                R.string.remove_home_collection_placeholder_content_description
                            ),
                            tint = FirefoxTheme.colors.iconPrimary
                        )
                    }
                }
                PrimaryText(
                    text = message.data.text,
                    modifier = Modifier.fillMaxWidth(),
                    fontSize = 14.sp
                )
            } else {
                Row(
                    modifier = Modifier.fillMaxWidth(),
                ) {
                    PrimaryText(
                        text = message.data.text,
                        modifier = Modifier.weight(1f),
                        fontSize = 14.sp
                    )
                    IconButton(
                        modifier = Modifier.size(24.dp),
                        onClick = onMessageClosedClicked
                    ) {
                        Icon(
                            painter = painterResource(R.drawable.ic_close),
                            contentDescription = stringResource(
                                R.string.remove_home_collection_placeholder_content_description
                            ),
                            tint = FirefoxTheme.colors.iconPrimary
                        )
                    }
                }
            }
```

Comment (sarah541) [reply app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/MessageCardViewHolder.kt:115]: The thing is when title is empty PrimaryText falls within the Row and not otherwise, hence the if condition is outside the Row not SectionHeader

File: app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/MessageCardViewHolder.kt [hunk 10]
```diff
@@ -5,53 +5,230 @@
...
+                Row(
+                    modifier = Modifier.fillMaxWidth(),
+                ) {
+                    PrimaryText(
+                        text = message.data.text,
+                        modifier = Modifier.weight(1f),
+                        fontSize = 14.sp
+                    )
+                    IconButton(
+                        modifier = Modifier.size(24.dp),
```
Comment (MozillaNoah) [inline app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/MessageCardViewHolder.kt:155]: drive by: I noticed that the IconButton here is 24.dp but the one in the positive `if` is 20.dp. Not sure if that's intentional

Comment (sarah541) [reply app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/MessageCardViewHolder.kt:155]: I was changing it to 20dp in the next push :P

File: app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/MessageCardViewHolder.kt (hunk 9 above)
Comment (Amejia481) [reply app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/MessageCardViewHolder.kt:115]: Got it 👍🏽 !

File: app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/MessageCardViewHolder.kt (hunk 8 above)
Comment (sarah541) [reply app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/MessageCardViewHolder.kt:66]: Agreed

File: app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/MessageCardViewHolder.kt (hunk 10 above)
Comment (sarah541) [reply app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/MessageCardViewHolder.kt:155]: Good catch! Thank you

File: app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlAdapter.kt [hunk 11]
```diff
@@ -305,7 +311,6 @@ class SessionControlAdapter(
             OnboardingToolbarPositionPickerViewHolder.LAYOUT_ID -> OnboardingToolbarPositionPickerViewHolder(
                 view
             )
-            MessageCardViewHolder.LAYOUT_ID -> MessageCardViewHolder(view, interactor)
             BottomSpacerViewHolder.LAYOUT_ID -> BottomSpacerViewHolder(view)
             else -> throw IllegalStateException()
         }
```
Comment (gabrielluong) [inline app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlAdapter.kt:316]: This is missing an entry in `onViewRecycled` I think, but i would read up on https://github.com/mozilla-mobile/fenix/pull/24501#discussion_r866517396.

File: app/src/main/res/layout/nimbus_message_card.xml [hunk 12]
```diff
@@ -1,58 +0,0 @@
...
-   - License, v. 2.0. If a copy of the MPL was not distributed with this
-   - file, You can obtain one at http://mozilla.org/MPL/2.0/. -->
-<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
-    xmlns:app="http://schemas.android.com/apk/res-auto"
-    xmlns:tools="http://schemas.android.com/tools"
-    android:id="@+id/experiment_card"
-    style="@style/OnboardingCardLightWithPadding"
-    android:layout_width="match_parent"
-    android:layout_height="wrap_content"
-    android:layout_marginHorizontal="@dimen/home_item_horizontal_margin">
```
Comment (gabrielluong) [inline app/src/main/res/layout/nimbus_message_card.xml:11]: Are we missing the horizontal margins that we set on init?

File: app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/MessageCardViewHolder.kt [hunk 13]
```diff
@@ -5,53 +5,197 @@
...
         }
-        interactor.onMessageDisplayed(message)
     }
+}
 
-    companion object {
-        internal const val LAYOUT_ID = R.layout.nimbus_message_card
-        private const val CLOSE_BUTTON_EXTRA_DPS = 38
+@Composable
+@Preview
```
Comment (gabrielluong) [inline app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/MessageCardViewHolder.kt:177]: Can you add 2 more previews 1 without a title and another with a button label?

File: app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/MessageCardViewHolder.kt [hunk 14]
```diff
@@ -5,53 +5,197 @@
...
+        ) {
+            if (!title.isNullOrBlank()) {
+                Row(
+                    modifier = Modifier.fillMaxWidth(),
+                ) {
+                    SectionHeader(
+                        text = title,
+                        modifier = Modifier
+                            .weight(1f)
+                            .padding(bottom = 10.dp)
```
Comment (gabrielluong) [inline app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/MessageCardViewHolder.kt:118]: Can you move this into a Spacer()

File: app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/MessageCardViewHolder.kt [hunk 15]
```diff
@@ -5,53 +5,197 @@
...
+ *
+ * @param message contains title and description of message.
+ * @param onMessageClicked Invoked when user clicks on the button.
+ * @param onMessageClosedClicked Invoked when user clicks on close button to remove message.
+ */
+@Suppress("LongMethod")
+@Composable
+fun MessageCard(
+    message: Message,
+    onMessageClicked: () -> Unit,
```
Comment (gabrielluong) [inline app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/MessageCardViewHolder.kt:88]:
```suggestion
    onClick: () -> Unit,
```

File: app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/MessageCardViewHolder.kt [hunk 16]
```diff
@@ -5,53 +5,197 @@
...
+    onMessageClosedClicked: () -> Unit,
```
Comment (gabrielluong) [inline app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/MessageCardViewHolder.kt:89]:
```suggestion
    onCloseButtonClick: () -> Unit,
```

File: app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/MessageCardViewHolder.kt [hunk 17]
```diff
@@ -5,53 +5,197 @@
...
         }
+    }
+}
 
-        binding.descriptionText.text = message.data.text
+/**
+ * Message Card.
+ *
+ * @param message contains title and description of message.
+ * @param onMessageClicked Invoked when user clicks on the button.
```
Comment (gabrielluong) [inline app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/MessageCardViewHolder.kt:81]:
```suggestion
 * @param onMessageClicked Invoked when user clicks on the message card.
```

File: app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/MessageCardViewHolder.kt [hunk 18]
```diff
@@ -5,53 +5,197 @@
...
+            )
         }
+    }
+}
 
-        binding.descriptionText.text = message.data.text
+/**
+ * Message Card.
+ *
+ * @param message contains title and description of message.
```
Comment (gabrielluong) [inline app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/MessageCardViewHolder.kt:80]:
```suggestion
 * @param message [Message] that holds a representation of GleanPlum message from Nimbus.
```

File: app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/MessageCardViewHolder.kt [hunk 19]
```diff
@@ -5,53 +5,197 @@
...
 
-    fun bind(message: Message) {
-        val binding = NimbusMessageCardBinding.bind(itemView)
+    companion object {
+        internal val LAYOUT_ID = View.generateViewId()
+    }
+
+    @Composable
+    override fun Content() {
+        val messageGlobal = components.appStore.observeAsComposableState { state -> state.messaging }
```
Comment (gabrielluong) [inline app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/MessageCardViewHolder.kt:64]:
```suggestion
        val messaging = components.appStore.observeAsComposableState { state -> state.messaging }
```

File: app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/MessageCardViewHolder.kt [hunk 20]
```diff
@@ -5,53 +5,197 @@
...
+        val messageValue = messageGlobal.value?.messageToShow
```
Comment (gabrielluong) [inline app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/MessageCardViewHolder.kt:65]:
```suggestion
        val message = messageGlobal.value?.messageToShow
```

File: app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/MessageCardViewHolder.kt [hunk 21]
```diff
@@ -5,53 +5,197 @@
...
+                if (message.data.buttonLabel.isNullOrBlank()) {
+                    Modifier.clickable(onClick = onMessageClicked)
+                } else {
+                    Modifier
+                }
+            ),
+        shape = RoundedCornerShape(8.dp),
+        backgroundColor = FirefoxTheme.colors.layer2,
+    ) {
+        val title = message.data.title
```
Comment (gabrielluong) [inline app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/MessageCardViewHolder.kt:104]: Can you move this into the Column {} block

File: app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/MessageCardViewHolder.kt [hunk 22]
```diff
@@ -5,53 +5,197 @@
...
+            } else {
+                Row(
+                    modifier = Modifier.fillMaxWidth(),
+                ) {
+                    PrimaryText(
+                        text = message.data.text,
+                        modifier = Modifier.weight(1f),
+                        fontSize = 14.sp
+                    )
+                    IconButton(
```
Comment (gabrielluong) [inline app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/MessageCardViewHolder.kt:149]: Add a new line above.

**Review by gabrielluong — CHANGES_REQUESTED** [review]

**Comment by gabrielluong** [comment]
@Amejia481 what's the easiest way to add a message to test this?

**Comment by Amejia481** [comment]
> @Amejia481 what's the easiest way to add a message to test this?
There are some tests that creates dummy messages, [this](https://github.com/mozilla-mobile/fenix/blob/405f406f16177e0ac0e72aaa509cb72ab5d4ab2b/app/src/test/java/org/mozilla/fenix/gleanplumb/NimbusMessagingStorageTest.kt#L293) one could be help as a guidance.  


Additionally, this is also a quick way:

```kotlin
Message(
    id = "id",
    data = MessageData(_context = testContext, title = "title",text = "description"),
    action = "action",
    style = StyleData(_context = testContext),
    triggers = emptyList(),
    metadata = Message.Metadata(
        id ="id"
    )
)

```

File: app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/MessageCardViewHolder.kt [hunk 23]
```diff
@@ -5,53 +5,197 @@
...
+/**
+ * Message Card.
+ *
+ * @param message contains title and description of message.
+ * @param onMessageClicked Invoked when user clicks on the button.
+ * @param onMessageClosedClicked Invoked when user clicks on close button to remove message.
+ */
+@Suppress("LongMethod")
+@Composable
+fun MessageCard(
```
Comment (MozillaNoah) [inline app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/MessageCardViewHolder.kt:86]: nit: could we possibly move `MessageCard` and its previews to another file? that way the relocation refactoring is already done by the time we get to killing off all of the viewholder code.

File: app/src/main/res/values/strings.xml [hunk 24]
```diff
@@ -1791,6 +1791,9 @@
     <!-- Default browser experiment -->
     <string name="default_browser_experiment_card_text">Set links from websites, emails, and messages to open automatically in Firefox.</string>
 
+    <!-- Default browser experiment -->
+    <string name="default_browser_experiment_card_title">Title</string>
```
Comment (gabrielluong) [inline app/src/main/res/values/strings.xml:1795]: Since this is only used in the @preview, can we avoid adding a string that would be localized.

File: app/src/main/java/org/mozilla/fenix/compose/MessageCard.kt [hunk 25]
```diff
@@ -0,0 +1,220 @@
...
+import org.mozilla.fenix.gleanplumb.Message
+import org.mozilla.fenix.nimbus.MessageData
+import org.mozilla.fenix.nimbus.StyleData
+import org.mozilla.fenix.theme.FirefoxTheme
+import org.mozilla.fenix.theme.Theme
+
+/**
+ * Message Card.
+ *
+ * @param [Message] that holds a representation of GleanPlum message from Nimbus.
```
Comment (gabrielluong) [inline app/src/main/java/org/mozilla/fenix/compose/MessageCard.kt:40]:
```suggestion
 * @param message [Message] that holds a representation of GleanPlum message from Nimbus.
```

File: app/src/main/java/org/mozilla/fenix/compose/MessageCard.kt [hunk 26]
```diff
@@ -0,0 +1,220 @@
...
+@Suppress("LongMethod")
+@Composable
+fun MessageCard(
+    message: Message,
+    onClick: () -> Unit,
+    onCloseButtonClick: () -> Unit,
+) {
+    Card(
+        modifier = Modifier
+            .padding(16.dp)
```
Comment (gabrielluong) [inline app/src/main/java/org/mozilla/fenix/compose/MessageCard.kt:53]: We need to remove the padding I think. 

| Before      | After |
| ----------- | ----------- |
Screen Shot 2022-05-17 at 1 35 24 PM|Screen Shot 2022-05-17 at 12 52 57 PM

**Review by gabrielluong — CHANGES_REQUESTED** [review]

File: app/src/main/java/org/mozilla/fenix/compose/MessageCard.kt (hunk 26 above)
Comment (sarah541) [reply app/src/main/java/org/mozilla/fenix/compose/MessageCard.kt:53]: No, that will cause something like this 
image

Comment (gabrielluong) [reply app/src/main/java/org/mozilla/fenix/compose/MessageCard.kt:53]: Isn't that the Column padding all = 16dp on line 66?

File: app/src/main/java/org/mozilla/fenix/compose/MessageCard.kt [hunk 27]
```diff
@@ -0,0 +1,223 @@
...
+                        modifier = Modifier.weight(1f),
+                        fontSize = 14.sp
+                    )
+
+                    IconButton(
+                        modifier = Modifier.size(20.dp),
+                        onClick = onCloseButtonClick
+                    ) {
+                        Icon(
+                            painter = painterResource(R.drawable.ic_close),
```
Comment (gabrielluong) [inline app/src/main/java/org/mozilla/fenix/compose/MessageCard.kt:119]:
```suggestion
                            painter = painterResource(R.drawable.mozac_ic_close_20),
```

Can you also change this over in `CollectionsPlaceholder`?

File: app/src/main/java/org/mozilla/fenix/compose/MessageCard.kt [hunk 28]
```diff
@@ -0,0 +1,223 @@
...
+fun MessageCard(
+    message: Message,
+    onClick: () -> Unit,
+    onCloseButtonClick: () -> Unit,
+) {
+    Card(
+        modifier = Modifier
+            .padding(
+                top = 16.dp,
+                bottom = 16.dp
```
Comment (gabrielluong) [inline app/src/main/java/org/mozilla/fenix/compose/MessageCard.kt:55]: You can simplify by using `vertical = 16.dp`

File: app/src/main/java/org/mozilla/fenix/compose/MessageCard.kt [hunk 29]
```diff
@@ -0,0 +1,223 @@
...
+                Row(
+                    modifier = Modifier.fillMaxWidth(),
+                ) {
+                    SectionHeader(
+                        text = title,
+                        modifier = Modifier
+                            .weight(1f)
+                    )
+
+                    Spacer(modifier = Modifier.height(10.dp))
```
Comment (gabrielluong) [inline app/src/main/java/org/mozilla/fenix/compose/MessageCard.kt:83]: This Spacer seems unnecessary since this is a `Row` and the spacer itself has no width.

File: app/src/main/java/org/mozilla/fenix/compose/MessageCard.kt [hunk 30]
```diff
@@ -0,0 +1,223 @@
...
+                    )
+
+                    IconButton(
+                        modifier = Modifier.size(20.dp),
+                        onClick = onCloseButtonClick
+                    ) {
+                        Icon(
+                            painter = painterResource(R.drawable.ic_close),
+                            contentDescription = stringResource(
+                                R.string.remove_home_collection_placeholder_content_description
```
Comment (gabrielluong) [inline app/src/main/java/org/mozilla/fenix/compose/MessageCard.kt:121]:
```suggestion
                                R.string. content_description_close_button
```

File: app/src/main/java/org/mozilla/fenix/compose/MessageCard.kt [hunk 31]
```diff
@@ -0,0 +1,223 @@
...
+                    Spacer(modifier = Modifier.height(10.dp))
+
+                    IconButton(
+                        modifier = Modifier.size(20.dp),
+                        onClick = onCloseButtonClick
+                    ) {
+                        Icon(
+                            painter = painterResource(R.drawable.ic_close),
+                            contentDescription = stringResource(
+                                R.string.remove_home_collection_placeholder_content_description
```
Comment (gabrielluong) [inline app/src/main/java/org/mozilla/fenix/compose/MessageCard.kt:92]:
```suggestion
                                R.string. content_description_close_button
```

File: app/src/main/java/org/mozilla/fenix/compose/MessageCard.kt [hunk 32]
```diff
@@ -0,0 +1,223 @@
...
+            val title = message.data.title
+            if (!title.isNullOrBlank()) {
+                Row(
+                    modifier = Modifier.fillMaxWidth(),
+                ) {
+                    SectionHeader(
+                        text = title,
+                        modifier = Modifier
+                            .weight(1f)
+                    )
```
Comment (gabrielluong) [inline app/src/main/java/org/mozilla/fenix/compose/MessageCard.kt:81]: Can you move the if statement within the `Row`? Currently, the Row and IconButton is common between both cases, and you can add an if statement check for the PrimaryText in line 99.

**Review by gabrielluong — CHANGES_REQUESTED** [review]

File: app/src/main/java/org/mozilla/fenix/compose/MessageCard.kt (hunk 32 above)
Comment (sarah541) [reply app/src/main/java/org/mozilla/fenix/compose/MessageCard.kt:81]: No, because if the title is not null, `SectionHeader` and `IconButton` needs to be in the `Row` while `PrimaryText` is out but in the else case, `PrimaryText` comes within the `Row`, hence the if statement surrounds the `Row`

File: app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/MessageCardViewHolder.kt [hunk 33]
```diff
@@ -5,53 +5,49 @@
...
+        internal val LAYOUT_ID = View.generateViewId()
+    }
 
-        binding.close.apply {
-            increaseTapArea(CLOSE_BUTTON_EXTRA_DPS)
-            setOnClickListener {
-                interactor.onMessageClosedClicked(message)
-            }
-        }
-        interactor.onMessageDisplayed(message)
```
Comment (Amejia481) [inline app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/MessageCardViewHolder.kt:50]: Looks like in the new implementation we are missing this call.

Comment (sarah541) [reply app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/MessageCardViewHolder.kt:50]: Thanks @Amejia481 , good catch! Missed it when removed the bind implementation .

File: app/src/main/java/org/mozilla/fenix/compose/MessageCard.kt [hunk 34]
```diff
@@ -0,0 +1,218 @@
...
+
+                    IconButton(
+                        modifier = Modifier.size(20.dp),
+                        onClick = onCloseButtonClick
+                    ) {
+                        Icon(
+                            painter = painterResource(R.drawable.ic_close),
```
Comment (gabrielluong) [inline app/src/main/java/org/mozilla/fenix/compose/MessageCard.kt:85]: All the ic_close here should be using mozac_ic_close20

File: app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/MessageCardViewHolder.kt [hunk 35]
```diff
@@ -5,53 +5,52 @@
...
+                onCloseButtonClick = { interactor.onMessageClosedClicked(message) }
+            )
         }
-
-        binding.close.apply {
-            increaseTapArea(CLOSE_BUTTON_EXTRA_DPS)
-            setOnClickListener {
-                interactor.onMessageClosedClicked(message)
-            }
+        if (message != null) {
```
Comment (gabrielluong) [inline app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/MessageCardViewHolder.kt:52]: Add a new line before this

**Review by gabrielluong — APPROVED** [review]
