### PR TITLE
For #24286 - Create new test for synced tabs error mapping

### LINKED ISSUE #24286: Add back unit test for Synced Tabs error message mapping
Per https://github.com/mozilla-mobile/fenix/pull/23994#issuecomment-1054627004, the unit test that was removed during the Synced Tabs to Compose refactor should be added back in to prevent another regression in the future. 

For reference, here's the original tests around the error mapping:

`class ErrorTypeKtTest {

    @Test
    fun `string resource for error`() {
        assertEquals(
            R.string.synced_tabs_connect_another_device,
            ErrorType.MULTIPLE_DEVICES_UNAVAILABLE.toStringRes()
        )
        assertEquals(
            R.string.synced_tabs_enable_tab_syncing,
            ErrorType.SYNC_ENGINE_UNAVAILABLE.toStringRes()
        )
        assertEquals(
            R.string.synced_tabs_sign_in_message,
            ErrorType.SYNC_UNAVAILABLE.toStringRes()
        )
        assertEquals(
            R.string.synced_tabs_reauth,
            ErrorType.SYNC_NEEDS_REAUTHENTICATION.toStringRes()
        )
        assertEquals(
            R.string.synced_tabs_no_tabs,
            ErrorType.NO_TABS_AVAILABLE.toStringRes()
        )
    }

    @Test
    fun `get error item`() {
        val navController = mockk<NavController>()

        var errorItem = ErrorType.MULTIPLE_DEVICES_UNAVAILABLE.toAdapterItem(
            R.string.synced_tabs_connect_another_device, navController
        )
        assertNull(errorItem.navController)
        assertEquals(R.string.synced_tabs_connect_another_device, errorItem.descriptionResId)

        errorItem = ErrorType.SYNC_ENGINE_UNAVAILABLE.toAdapterItem(
            R.string.synced_tabs_enable_tab_syncing, navController
        )
        assertNull(errorItem.navController)
        assertEquals(R.string.synced_tabs_enable_tab_syncing, errorItem.descriptionResId)

        errorItem = ErrorType.SYNC_NEEDS_REAUTHENTICATION.toAdapterItem(
            R.string.synced_tabs_reauth, navController
        )
        assertNull(errorItem.navController)
        assertEquals(R.string.synced_tabs_reauth, errorItem.descriptionResId)

        errorItem = ErrorType.NO_TABS_AVAILABLE.toAdapterItem(
            R.string.synced_tabs_no_tabs, navController
        )
        assertNull(errorItem.navController)
        assertEquals(R.string.synced_tabs_no_tabs, errorItem.descriptionResId)

        errorItem = ErrorType.SYNC_UNAVAILABLE.toAdapterItem(
            R.string.synced_tabs_sign_in_message, navController
        )
        assertNotNull(errorItem.navController)
        assertEquals(R.string.synced_tabs_sign_in_message, errorItem.descriptionResId)
    }
}`

### PR DESCRIPTION
**Pull request by MozillaNoah**
Closes #24286 

### Pull Request checklist

- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

File: app/src/main/java/org/mozilla/fenix/tabstray/syncedtabs/SyncedTabsIntegration.kt [hunk 1]
```diff
@@ -99,34 +98,4 @@ class SyncedTabsIntegration(
             )
         )
     }
-
-    /**
-     * Converts [SyncedTabsView.ErrorType] to [SyncedTabsListItem.Error] with a lambda for ONLY
-     * [SyncedTabsView.ErrorType.SYNC_UNAVAILABLE]
-     */
-    private fun SyncedTabsView.ErrorType.toSyncedTabsListItem() = when (this) {
```
Comment (gabrielluong) [inline app/src/main/java/org/mozilla/fenix/tabstray/syncedtabs/SyncedTabsIntegration.kt:107]: I am not sure it's worthwhile to refactor this into a `ext/` since you gotta pass in the `context` and `navController`.  

I think it was clear to me that we shouldn't refactor it when your test file ended up being called `SyncedTabsIntegrationTest` instead of `SyncedTabsViewErrorTypeTest`. So, maybe we should just make this function visible for testing.

Comment (MozillaNoah) [reply app/src/main/java/org/mozilla/fenix/tabstray/syncedtabs/SyncedTabsIntegration.kt:107]: The naming of the test file is a mistake. I tried making the extension internal and visible for testing, but it wasn't getting imported into the test.

File: app/src/test/java/org/mozilla/fenix/tabstray/syncedtabs/SyncedTabsIntegrationTest.kt [hunk 2]
```diff
@@ -0,0 +1,40 @@
...
+import org.junit.runner.RunWith
+import org.mozilla.fenix.R
+import org.mozilla.fenix.helpers.FenixRobolectricTestRunner
+import org.mozilla.fenix.tabstray.ext.toSyncedTabsListItem
+
+@RunWith(FenixRobolectricTestRunner::class)
+class SyncedTabsIntegrationTest {
+
+    @Test
+    fun `WHEN toSyncedTabsListItem is called THEN return a SyncedTabsListItem_Error with the correct text`() {
```
Comment (gabrielluong) [inline app/src/test/java/org/mozilla/fenix/tabstray/syncedtabs/SyncedTabsIntegrationTest.kt:23]: Gonna reuse Christian's advice for naming here: 

> nitnit :) In general it's better to keep the method names out of the test names. Otherwise all test names will be stale if you anyone ever refactors those methods.
> 
> e.g. GIVEN crashes should be reported WHEN user restores tab THEN non-fatal crash report is submitted and tab recovered.

https://github.com/mozilla-mobile/fenix/pull/23010#discussion_r802089174

File: app/src/main/java/org/mozilla/fenix/tabstray/syncedtabs/SyncedTabsIntegration.kt (hunk 1 above)
Comment (gabrielluong) [reply app/src/main/java/org/mozilla/fenix/tabstray/syncedtabs/SyncedTabsIntegration.kt:107]: Hmm.. `VisibleForTesting` not working for an `internal` function sounds a bit weird.
