### PR TITLE
Fixes #654 - Update refresh/stop toolbar buttons

### LINKED ISSUE #654: back and forward buttons don't have a (visual) disabled state
## Steps to reproduce

1. open a website in Fenix
2. press the menu button

### Expected behavior

The back and the forward button should be disabled because you can't navigate back and you can't navigate forward until you navigate to another page. Alternatively, only the forward button should be disabled if - like in Fennec - the back button brings you back to the homescreen but that's not the current behaviour of Fenix.

### Actual behavior

The back and the forward button always look enabled.

### Device information

* Android device: HTC U11 / Android 8.0
* Fenix version: revision [3ccce1b](https://github.com/mozilla-mobile/fenix/commit/3ccce1b4d264362f6043f662ea5639c5a2d879bd)

### PR DESCRIPTION
**Pull request by NotWoods**
Refresh/stop, back, and forward buttons will now update while the browser-menu is open.

Requires mozilla-mobile/android-components#3022 ~to be merged into the A-C snapshot tomorrow~ which is now in the 0.54.0 snapshot.

### Pull Request checklist

- [x] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/fenix/blob/master/CHANGELOG.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### CODE REVIEW

File: app/src/main/java/org/mozilla/fenix/components/toolbar/MenuPresenter.kt [hunk 1]
```diff
@@ -0,0 +1,25 @@
...
+import mozilla.components.browser.session.SelectionAwareSessionObserver
+import mozilla.components.browser.session.Session
+import mozilla.components.browser.session.SessionManager
+import mozilla.components.browser.toolbar.BrowserToolbar
+
+class MenuPresenter(
+    private val menuToolbar: BrowserToolbar,
+    sessionManager: SessionManager
+) : SelectionAwareSessionObserver(sessionManager) {
+    /** Redraw the refresh/stop button */
```
Comment (jonalmeida) [inline app/src/main/java/org/mozilla/fenix/components/toolbar/MenuPresenter.kt]: I'd add a `start` method here so we can observe a session by an optional sessionId, similar to [site permissions](https://github.com/mozilla-mobile/android-components/blob/master/components/feature/sitepermissions/src/main/java/mozilla/components/feature/sitepermissions/SitePermissionsFeature.kt#L84).

The reasoning behind that is, for Custom Tabs, those sessions will never be a selected session, so we have to tell our observers when we want to explicitly observe that kind of session.

File: app/src/main/java/org/mozilla/fenix/components/toolbar/ToolbarIntegration.kt [hunk 2]
```diff
@@ -77,12 +77,15 @@ class ToolbarIntegration(
         ToolbarFeature.UrlRenderConfiguration(PublicSuffixList(context),
             DefaultThemeManager.resolveAttribute(R.attr.primaryText, context), renderStyle = renderStyle)
     )
+    private var menuPresenter = MenuPresenter(toolbar, context.components.core.sessionManager)
 
     override fun start() {
+        menuPresenter.observeSelected()
```
Comment (jonalmeida) [inline app/src/main/java/org/mozilla/fenix/components/toolbar/ToolbarIntegration.kt]: From the above comment, this can then change to `presenter.start()`.
