### PR TITLE
For #19988 - Load tab icon from BrowserIcons cache if needed for the recent tab

### LINKED ISSUE #19988: [Bug] "Jump back in": website icon is missing after launching to home screen or closing a tab
### Steps to reproduce

0. Prerequisite: Settings > Tabs > Start on home: Always
1. Remove Firefox from your Android recent apps
2. Start Firefox

alternative steps to reproduce:

1. open tabs tray
2. close a tab
3. close the tabs tray

### Expected behavior

The tab in the ""Jump back in" section has a website icon.

### Actual behavior

No website icon, only a large gap.

Screenshot_20210613-105456

### Device information

* Device vendor / model and Android version: OnePlus 7T Pro McLaren / Oxygen OS 11 (Android 11)
* Firefox for Android version: master branch revision cc6bbcdf9c806bd9b049dea165821a5bbd59ef05

### PR DESCRIPTION
**Pull request by gabrielluong**
Fixes #19988

### Pull Request checklist

- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

File: app/src/test/java/org/mozilla/fenix/home/recenttabs/view/RecentTabViewHolderTest.kt [hunk 1]
```diff
@@ -33,18 +38,23 @@ class RecentTabViewHolderTest {
...
 
     @Test
-    fun `GIVEN a new recent tab on bind THEN set the title text`() {
-        RecentTabViewHolder(view, interactor).bindTab(tab)
+    fun `GIVEN a new recent tab on bind THEN set the title text and load the tab icon`() {
+        RecentTabViewHolder(view, interactor, icons).bindTab(tab)
 
         assertEquals(tab.content.title, view.recent_tab_title.text)
+
+        verify { icons.loadIntoView(view.recent_tab_icon, IconRequest(tab.content.url)) }
```
Comment (jonalmeida) [inline app/src/test/java/org/mozilla/fenix/home/recenttabs/view/RecentTabViewHolderTest.kt:52]: nit: could use a year for when the tab.content.icon is not null i.e. the other branch of the if-else.

**Review by jonalmeida — APPROVED** [review]

**Comment by jonalmeida** [comment]
Landing this without the test updates; I have a patch that works on top of it and I'll fix the test too.
