### PR TITLE
Fixes #4894: added workaround for SDK<24 vector drawable with gradient color

### LINKED ISSUE #4894: [Bug]Fenix widget can't be added on Android 6 devices
## Steps to reproduce
1. Long tap on the home screen of your device
2. Select widgets
3. Touch and hold the Firefox Preview widget & move it to your home screen

### Expected behavior
Widget can be added to the home screen of the device and can be used properly

### Actual behavior
Instead of the actual Firefox Preview widgets a Black bar shows up saying "Problem loading the widget"
rsz_screenshot_20190823-1124366666666

### Device information

* Android device: 
• Samsung Galaxy S6 (Android 6)
• OnePlus A3 (Android 6.0.1)
• Huawei P9 Lite (Android 6)

* Fenix version: 1.0.1934 (Build # 1) 📦: 10.0.0, 1c652634c GV: 70.0a1-20190822095439 from **23/8**

### Notes
►Video from  Samsung Galaxy S6

ezgif com-video-to-gif

### PR DESCRIPTION
**Pull request by mcarare**
Removed drawableStart and added ImageView in layouts
Set ImageView logo programmatically: bitmap for SDK<24, vector for SDK>=24
Added onClickPendingIntent for ImageView in large and medium layouts

### Pull Request checklist

- [x] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### CODE REVIEW

File: app/src/main/java/org/mozilla/fenix/widget/SearchWidgetProvider.kt [hunk 1]
```diff
@@ -20,8 +20,12 @@ import org.mozilla.fenix.HomeActivity
 import org.mozilla.fenix.IntentReceiverActivity
 import org.mozilla.fenix.R
 import org.mozilla.fenix.utils.Settings
+import android.os.Build
+import androidx.appcompat.widget.AppCompatDrawableManager
+import androidx.core.graphics.drawable.toBitmap
 
-class SearchWidgetProvider : AppWidgetProvider() {
+@Suppress("TooManyFunctions")
+    class SearchWidgetProvider : AppWidgetProvider() {
```
Comment (jhugman) [inline app/src/main/java/org/mozilla/fenix/widget/SearchWidgetProvider.kt]: Nit: whitespace.

File: app/src/main/java/org/mozilla/fenix/widget/SearchWidgetProvider.kt [hunk 2]
```diff
@@ -151,6 +157,22 @@ class SearchWidgetProvider : AppWidgetProvider() {
         }
     }
 
+    private fun RemoteViews.setIcon(context: Context) {
```
Comment (jhugman) [inline app/src/main/java/org/mozilla/fenix/widget/SearchWidgetProvider.kt]: Consider: 

1. put this in a non-private extension method, in a separate file.
2. promote this to android-components.

File: app/src/main/java/org/mozilla/fenix/widget/SearchWidgetProvider.kt [hunk 3]
```diff
@@ -140,6 +145,7 @@ class SearchWidgetProvider : AppWidgetProvider() {
                 R.layout.search_widget_large -> {
                     setOnClickPendingIntent(R.id.button_search_widget_new_tab, textSearchIntent)
                     setOnClickPendingIntent(R.id.button_search_widget_voice, voiceSearchIntent)
+                    setOnClickPendingIntent(R.id.button_search_widget_new_tab_icon, textSearchIntent)
```
Comment (jhugman) [inline app/src/main/java/org/mozilla/fenix/widget/SearchWidgetProvider.kt]: A lot of this PR deals with this. Consider changing the name of this PR/commit.

File: app/src/main/java/org/mozilla/fenix/widget/SearchWidgetProvider.kt (hunk 1 above)
Comment (mcarare) [reply app/src/main/java/org/mozilla/fenix/widget/SearchWidgetProvider.kt]: Thanks for that! I haven't noticed it. I am submitting a PR tomorrow for another issue and it also has small changes in this file. I have fixed the whitespace issue there.

File: app/src/main/java/org/mozilla/fenix/widget/SearchWidgetProvider.kt (hunk 3 above)
Comment (mcarare) [reply app/src/main/java/org/mozilla/fenix/widget/SearchWidgetProvider.kt]: Actually, this is a small part of the PR, and it is mentioned in the commit message. If you have another suggestion for the commit message I am open to suggestions.

File: app/src/main/java/org/mozilla/fenix/widget/SearchWidgetProvider.kt (hunk 2 above)
Comment (mcarare) [reply app/src/main/java/org/mozilla/fenix/widget/SearchWidgetProvider.kt]: I have already considered that, but IMO the use case here is very specific ( specific version check, specific vector with problems, specific view) that is why I considered not promoting it to ac or creating an extension function.

File: app/src/main/java/org/mozilla/fenix/widget/SearchWidgetProvider.kt (hunk 1 above)
Comment (mcarare) [reply app/src/main/java/org/mozilla/fenix/widget/SearchWidgetProvider.kt]: First thing tomorrow morning!

Comment (mcarare) [reply app/src/main/java/org/mozilla/fenix/widget/SearchWidgetProvider.kt]: Done!

Comment (boek) [reply app/src/main/java/org/mozilla/fenix/widget/SearchWidgetProvider.kt]: Thank you so much!
