### PR TITLE
Closes #28342: change the ui direction after a locale change

### LINKED ISSUE #28342: [BUG] change RTL/LTR languages doesn't update the UI until new launch
Issue that was mentioned [here](https://github.com/mozilla-mobile/fenix/issues/21306#issuecomment-1101778924).

`Switching from an RTL to an LTR locale (or vice versa) doesn't update the UI direction without restarting Fenix first`

### Steps to reproduce

Go to language screen and change the language to a language with the opposite direction from the one you are currently using.

### Expected behaviour

The layout of the app will change to accommodate the direction of the set language.
### Actual behaviour

The direction of the layout keeps the same until relaunching the app.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22207)

### PR DESCRIPTION
**Pull request by mavduevskiy**
https://user-images.githubusercontent.com/92760693/209997180-e66ed269-88b8-46ae-8ce8-caf6540cb30d.mp4

### Pull Request checklist

- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### QA

- [x] **QA Needed**

### To download an APK when reviewing a PR (after all CI tasks finished running):
1. Click on `Checks` at the top of the PR page.
2. Click on the `firefoxci-taskcluster` group on the left to expand all tasks.
3. Click on the `build-debug` task.
4. Click on `View task in Taskcluster` in the new `DETAILS` section.
5. The APK links should be on the right side of the screen, named for each CPU architecture.

### GitHub Automation
Fixes #28342

### CODE REVIEW

File: app/src/main/java/org/mozilla/fenix/HomeActivity.kt [hunk 1]
```diff
@@ -229,6 +231,10 @@ open class HomeActivity : LocaleAwareAppCompatActivity(), NavHostActivity {
 
         components.publicSuffixList.prefetch()
 
+        // Changing a language on the Language screen restarts the activity, but the activity keeps
+        // the old layout direction. We have to update the direction manually.
+        window.decorView.layoutDirection = TextUtils.getLayoutDirectionFromLocale(Locale.getDefault())
```
Comment (MozillaNoah) [inline app/src/main/java/org/mozilla/fenix/HomeActivity.kt:236]: Drive by: This seems like a last resort location to do an initialization step from a setting. Would it be possible to include this in the locale settings flow when updating the language? `DefaultLocaleSettingsController` might be a better alternative.

Comment (mavduevskiy) [reply app/src/main/java/org/mozilla/fenix/HomeActivity.kt:236]: That was my first though as well, but this approach has an issue – invalidating the layout and recreating the activity happens not synchronously and looks like a glitch.

https://user-images.githubusercontent.com/92760693/211407358-b70ea490-f7b1-4cff-86e7-bfb4c22c5382.mp4

What concerned did you have in mind here? Applying proper orientation during `onCreate` looks okay to me. `setLayoutDirection` has also a safety check to invalidate the layout only if it is needed.

Comment (MozillaNoah) [reply app/src/main/java/org/mozilla/fenix/HomeActivity.kt:236]: Where is the orientation being set in HomeActivity?

My primary concern is that this was even needed at all and might be a heavy hammer, but I did notice that `HomeActivity` extends from `LocaleAwareAppCompatActivity` which has this same line in its own `onCreate`. Based on the adjacent comment in `HomeActivity`, the `super.onCreate` only gets called after some disk read violations, but it was obviously needed.

Comment (mavduevskiy) [reply app/src/main/java/org/mozilla/fenix/HomeActivity.kt:236]: The use-case I am working on is `DefaultLocaleSettingsController` changing the Locale to something that has a different text orientation and restarts the activity. Changing the locale should also change the layout orientation, but it doesn't and the activity is recreated with the old orientation. To avoid glitching, enforcing changed orientation looks like a good idea to me. What do you think?

Comment (MozillaNoah) [reply app/src/main/java/org/mozilla/fenix/HomeActivity.kt:236]: Judging by the conversation in https://github.com/mozilla-mobile/fenix/issues/9413, I think I'm OK with this approach, as it's a natural side effect of us having to take care of all of the configuration changes. Maybe it won't be necessary in a 100% Compose world 🤞

**Review by MozillaNoah — APPROVED** [review]

**Comment by mavduevskiy** [comment]
Thank you, Noah! @MozillaNoah
