### PR TITLE
For #27035 - Add padding around onboarding buttons and content

### LINKED ISSUE #27035: [Bug]: [foxfooding] Little padding around the "Get started" button
### Steps to reproduce

1) Upgrade Firefox Nightly
2) Open Firefox Nightly
3) See the "Welcome to an independent internet" screen

### Expected behaviour

The "Get started" button stands on its own.

### Actual behaviour

The "Get started" button is flush with the text "More colours. Better privacy. Same commitment to people over profits."

### Device name

_No response_

### Android version

na

### Firefox release type

Firefox Nightly

### Firefox version

106

### Device logs

_No response_

### Additional information

**Firefox Version:** Mozilla/5.0 (X11; Linux x86_64; rv:104.0) Gecko/20100101 Firefox/104.0
**Window Size (inner width and height):** 1638x1127
**GitHub Username:** @Vinnl

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21596)

### PR DESCRIPTION
**Pull request by sarah541**
Screen Shot 2022-12-21 at 11 43 37 AM

### Pull Request checklist

- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### QA

- [x] **QA Needed**

### To download an APK when reviewing a PR (after all CI tasks finished running):
1. Click on `Checks` at the top of the PR page.
2. Click on the `firefoxci-taskcluster` group on the left to expand all tasks.
3. Click on the `build-debug` task.
4. Click on `View task in Taskcluster` in the new `DETAILS` section.
5. The APK links should be on the right side of the screen, named for each CPU architecture.

### GitHub Automation
Fixes #27035

### CODE REVIEW

**Review by zmckenney — CHANGES_REQUESTED** [review]
Both commit messages misspell "little", could you update those? Otherwise this looks good!

**Comment by sarah541** [comment]
Noticed another padding needed on onboarding screen on the sync page, added it in another commit.
Screen Shot 2022-12-21 at 12 33 08 PM

**Comment by zmckenney** [comment]
Just to clarify the design intent of the space between the "Get Started" button, is this a minimum distance between the onboarding section and button or is this supposed to move the onboarding section up on phones with enough space already?

**Comment by sarah541** [comment]
> Just to clarify the design intent of the space between the "Get Started" button, is this a minimum distance between the onboarding section and button or is this supposed to move the onboarding section up on phones with enough space already?

The intent is to add a minimum spacing between the content and button

**Comment by zmckenney** [comment]
> > Just to clarify the design intent of the space between the "Get Started" button, is this a minimum distance between the onboarding section and button or is this supposed to move the onboarding section up on phones with enough space already?
> 
> The intent is to add a minimum spacing between the content and button

Because this is using a spacer within a column with SpaceBetween arrangement it will be considered in the measurement. `OnboardingWelcomeContent` and `OnboardingSyncSignInContent` will both be moved up and not be centered. If we only want a minimum distance between the content then we should modify the padding values around the composables instead.

**Comment by sarah541** [comment]
> `OnboardingSyncSignInContent`

I second on what you said. Changing it to padding values

**Comment by sarah541** [comment]
> > > Just to clarify the design intent of the space between the "Get Started" button, is this a minimum distance between the onboarding section and button or is this supposed to move the onboarding section up on phones with enough space already?
> > 
> > 
> > The intent is to add a minimum spacing between the content and button
> 
> Because this is using a spacer within a column with SpaceBetween arrangement it will be considered in the measurement. `OnboardingWelcomeContent` and `OnboardingSyncSignInContent` will both be moved up and not be centered. If we only want a minimum distance between the content then we should modify the padding values around the composables instead.

I second on what  you said here. Thanks for explaining. Changing it to padding values.

File: app/src/main/java/org/mozilla/fenix/onboarding/view/Onboarding.kt [hunk 1]
```diff
@@ -164,7 +164,11 @@ private fun OnboardingWelcomeBottomContent(
 @Composable
 private fun OnboardingWelcomeContent() {
     Column(
-        modifier = Modifier.padding(horizontal = 16.dp),
+        modifier = Modifier.padding(
+            start = 16.dp,
+            end = 16.dp,
+            bottom = 32.dp,
```
Comment (zmckenney) [inline app/src/main/java/org/mozilla/fenix/onboarding/view/Onboarding.kt:170]: Because this is adding padding only to the bottom it will still be considered in the arrangement. To center this in the space you would need to add a min padding of 32.dp to the top as well (assuming that is ok with design). So final result would be:
`Modifier.padding(horizontal = 16.dp, vertical = 32.dp)`

File: app/src/main/java/org/mozilla/fenix/onboarding/view/Onboarding.kt [hunk 2]
```diff
@@ -195,7 +199,11 @@ private fun OnboardingWelcomeContent() {
 @Composable
 private fun OnboardingSyncSignInContent() {
     Column(
-        modifier = Modifier.padding(horizontal = 16.dp),
+        modifier = Modifier.padding(
```
Comment (zmckenney) [inline app/src/main/java/org/mozilla/fenix/onboarding/view/Onboarding.kt:202]: Same as above comment

**Review by zmckenney — CHANGES_REQUESTED** [review]

**Comment by sarah541** [comment]
I would like to defer to @gabrielluong  and @Kate-Galetski at this point. Is it essential for the content that includes the onboarding image, onboarding title and onboarding description to be centered between toolbar and the button? If yes, we'll have to add a spacer of 32.dp above  this content just like we are adding below this content. Adding screenshots where difference is visible.
Spacer added above and below|Spacer added just below
---|---
|

File: app/src/main/java/org/mozilla/fenix/onboarding/view/Onboarding.kt (hunk 1 above)
Comment (gabrielluong) [reply app/src/main/java/org/mozilla/fenix/onboarding/view/Onboarding.kt:170]: This makes sense to me.

**Comment by sarah541** [comment]
Spoke with @Kate-Galetski  and she gave a thumbs up to add spacers at both places

**Review by gabrielluong — APPROVED** [review]
