### PR TITLE
Fixes #4091 & Fixes #4092: Resolve issue with Search UI tests

### LINKED ISSUE #4091: [Bug] Failing UI test - shortcutButtonTest (API 25 only)
The shortcutButtonTest (UI test) is failing in Firebase on API level 25 only.  
Click on link to Firebase dashboard:
https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7535964156004191816
Drill down on failing API and click on tabs or "Test Results" button on upper right to view raw logs in GCP.
```
androidx.test.espresso.PerformException: Error performing 'single click - At Coordinates: 456, 1741 and precision: 16, 16' on view 'with id: org.mozilla.fenix.debug:id/search_shortcuts_button'.
```

### LINKED ISSUE #4092: [Bug] Failing UI test - scanButtonTest (all APIs)
The scanButtonTest (UI test) is failing in Firebase on all APIs.  
Click on link to Firebase dashboard:
https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7845426704726412832
Drill down on failing API and click on tabs or "Test Results" button on upper right to view raw logs in GCP.
```
07-16 12:52:02.931: I/TestRunner(13338): failed: scanButtonTest(org.mozilla.fenix.ui.SearchTest)
07-16 12:52:02.931: I/TestRunner(13338): ----- begin exception -----
07-16 12:52:02.933: I/TestRunner(13338): androidx.test.espresso.NoActivityResumedException: No activities in stage RESUMED. Did you t to launch the activity. (test.getActivity() or similar)?
```

### PR DESCRIPTION
**Pull request by sblatz**
### Pull Request checklist

- [ ] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/fenix/blob/master/CHANGELOG.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### CODE REVIEW

File: app/src/androidTest/java/org/mozilla/fenix/ui/SearchTest.kt [hunk 1]
```diff
@@ -37,14 +38,14 @@ class SearchTest {
         }
     }
 
+    @Ignore("This test cannot run on virtual devices due to camera permissions being required")
```
Comment (rpappalax) [inline app/src/androidTest/java/org/mozilla/fenix/ui/SearchTest.kt]: @npark-mozilla, it looks like the devices on Firebase have limited camera permissions.  We can probably investigate this further later but, for now, it seems reasonable to me that we commit these tests and Ignore so they can be run locally as needed.

Comment (npark-mozilla) [reply app/src/androidTest/java/org/mozilla/fenix/ui/SearchTest.kt]: yes that's fine, since we should only run tests on physical device on firebase.
