### PR TITLE
For #19600: Change manage cards preference UI dynamically.

### LINKED ISSUE #19600: [Bug] Credit card settings screen has a noticeable blink when it is opened
## Steps to reproduce

Open credit card preference screen

### Expected behavior

There are no visible screen updates.

### Actual behavior

There is a noticeable blink when the credit card list is not empty and the "manage saved cards" option should be visible.

https://user-images.githubusercontent.com/48995920/119145002-e7435900-ba51-11eb-8a37-8bba8e0fcff8.mp4

### Device information

* Device vendor/model and Android version:  All
* Firefox for Android version: latest master

### PR DESCRIPTION
**Pull request by mcarare**
Fixes #19600

### Pull Request checklist

- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [x] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

**before:**

https://user-images.githubusercontent.com/48995920/119152842-583a3f00-ba59-11eb-8fa5-e7845866e348.mp4

**after:**

https://user-images.githubusercontent.com/48995920/119152853-5bcdc600-ba59-11eb-92a5-2367d04b71c8.mp4

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

File: app/src/test/java/org/mozilla/fenix/settings/creditcards/CreditCardsSettingFragmentTest.kt [hunk 1]
```diff
@@ -38,32 +46,60 @@ class CreditCardsSettingFragmentTest {
     }
 
     @Test
-    fun `GIVEN the list of credit cards is not empty, WHEN fragment is displayed THEN the manage credit cards pref is visible`() {
-        val manageSavedCardsPreference = creditCardsSettingFragment.findPreference<Preference>(
-            creditCardsSettingFragment.getPreferenceKey(R.string.pref_key_credit_cards_manage_saved_cards)
+    fun `GIVEN the list of credit cards is not empty, WHEN fragment is displayed THEN the manage credit cards pref is 'manage saved cards'`() {
```
Comment (gabrielluong) [inline app/src/test/java/org/mozilla/fenix/settings/creditcards/CreditCardsSettingFragmentTest.kt:49]:
```suggestion
    fun `GIVEN the list of credit cards is not empty, WHEN fragment is displayed THEN the manage credit cards pref is 'Manage saved cards'`() {
```

**Review by gabrielluong — APPROVED** [review]
