### PR TITLE
For #27714 fix disabled sponsored shortcut UI tests

### LINKED ISSUE #27714: UI test failure - Top Sites & SponsoredShortcuts failures after design revert
After reverting the Top Sites UI to its 105 designs, the UI tests around them need to be reverted as well.

Reverted in:
- https://github.com/mozilla-mobile/fenix/pull/27711

### Firebase Test Run:
https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/9034723915705932614

### Tests ignored
- verifySponsoredShortcutsListTest
- openSponsoredShortcutTest
- openSponsoredShortcutInPrivateBrowsingTest
- verifySponsoredShortcutsSponsorsAndPrivacyOptionTest
- verifySponsoredShortcutsSettingsOptionTest

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21931)
┆Link To Issue: https://mozilla-hub.atlassian.net/browse/FNXV2-21931

### PR DESCRIPTION
**Pull request by AndiAJ**
For #27714 fix disabled sponsored shortcut UI tests.

`verifySponsoredShortcutsListTest` ✅ successfully passed 100x on Firebase
`openSponsoredShortcutTest` ✅ successfully passed 100x on Firebase
`openSponsoredShortcutInPrivateBrowsingTest` ✅ successfully passed 100x on Firebase
`verifySponsoredShortcutsSponsorsAndPrivacyOptionTest` ✅ successfully passed 100x on Firebase
`verifySponsoredShortcutsSettingsOptionTest` ✅ successfully passed 100x on Firebase

### Pull Request checklist

- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### QA

- [ ] **QA Needed**

### To download an APK when reviewing a PR (after all CI tasks finished running):
1. Click on `Checks` at the top of the PR page.
2. Click on the `firefoxci-taskcluster` group on the left to expand all tasks.
3. Click on the `build-debug` task.
4. Click on `View task in Taskcluster` in the new `DETAILS` section.
5. The APK links should be on the right side of the screen, named for each CPU architecture.

### GitHub Automation
Fixes #27714

### CODE REVIEW

File: app/src/androidTest/java/org/mozilla/fenix/ui/robots/HomeScreenRobot.kt [hunk 1]
```diff
@@ -870,7 +870,7 @@ private fun assertSponsoredShortcutTitle(sponsoredShortcutTitle: String, positio
     assertTrue(
         mDevice.findObject(
             UiSelector()
-                .className("android.widget.FrameLayout")
+                .resourceId("$packageName:id/top_site_item")
```
Comment (sv-ohorvath) [inline app/src/androidTest/java/org/mozilla/fenix/ui/robots/HomeScreenRobot.kt:873]: All good, but I'd create a single topSiteItem val and reuse it.

**Review by sv-ohorvath — APPROVED** [review]

File: app/src/androidTest/java/org/mozilla/fenix/ui/robots/HomeScreenRobot.kt (hunk 1 above)
Comment (AndiAJ) [reply app/src/androidTest/java/org/mozilla/fenix/ui/robots/HomeScreenRobot.kt:873]: Sure, sounds good.

**Review by AaronMT — APPROVED** [review]

File: app/src/androidTest/java/org/mozilla/fenix/ui/robots/HomeScreenRobot.kt (hunk 1 above)
Comment (AndiAJ) [reply app/src/androidTest/java/org/mozilla/fenix/ui/robots/HomeScreenRobot.kt:873]: As per our private discussion I'll leave it as it is.
