### PR TITLE
Closes #12692: Remove www. prefix in tab tray urls

### LINKED ISSUE #12692: FNX2-15412 ⁃ [Bug] "www." not trimmed from url in tab tray
## Steps to reproduce
Open https://www.wikipedia.org/ or https://www.nytimes.com/.

### Expected behavior
URLs in tab tray have the "www." stripped like they do in the address bar:

This also happened in the old version of the tab tray (I borrowed this screenshot from https://github.com/mozilla-mobile/fenix/issues/10683#issue-618970283):

### Actual behavior
The "www." is present:

There are actully two arguments in favor of this:

1. The hostname shown should reflect the one shown in the address bar.
1. Hiding this reduces clutter in the tab tray.

### PR DESCRIPTION
**Pull request by Vaintti**
### Pull Request checklist

- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### After merge
- [ ] **Milestone**: Make sure issues finished by this pull request are added to the [milestone](https://github.com/mozilla-mobile/fenix/milestones) of the version currently in development.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

Screenshot_1595874595

### CODE REVIEW

File: app/src/main/java/org/mozilla/fenix/tabtray/TabTrayViewHolder.kt [hunk 1]
```diff
@@ -26,16 +26,10 @@ import mozilla.components.feature.media.ext.playIfPaused
...
 import org.mozilla.fenix.R
 import org.mozilla.fenix.components.metrics.Event
 import org.mozilla.fenix.components.metrics.MetricController
-import org.mozilla.fenix.ext.components
-import org.mozilla.fenix.ext.getMediaStateForSession
-import org.mozilla.fenix.ext.increaseTapArea
-import org.mozilla.fenix.ext.removeAndDisable
-import org.mozilla.fenix.ext.removeTouchDelegate
-import org.mozilla.fenix.ext.showAndEnable
+import org.mozilla.fenix.ext.*
```
Comment (Mugurell) [inline app/src/main/java/org/mozilla/fenix/tabtray/TabTrayViewHolder.kt:32]: Wildcard imports will fail our `ktlint` task.
Please rollback this change.

Comment (Vaintti) [reply app/src/main/java/org/mozilla/fenix/tabtray/TabTrayViewHolder.kt]: I fixed the imports and squashed the branch

**Comment by Mugurell** [comment]
Thank you for updating this @Vaintti !
In the meantime I saw though there is already another PR open - https://github.com/mozilla-mobile/fenix/pull/12693 which want to use a slightly different approach.
Let's try to sync with Emily and see what exactly should be used.
