### PR TITLE
For#27753 - Update search engines immediately after changing language

### LINKED ISSUE #27753: [Bug]: Search engines are not updated immediately after changing language
### Steps to reproduce

1. Change language from system language or app settings
2. Check the available search engines

### Expected behaviour

The list of available search engines is automatically updated for the newly selected locale

### Actual behaviour

An app restart is needed for the list of search engines to be updated.
The issues happens with or without unified search enabled.

### Firefox version

Seems like an old issue, happens in the current release also.

### Additional information

https://user-images.githubusercontent.com/11428869/200523702-ea08d843-a454-49e1-91a9-4246197008b7.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21950)
┆Link To Issue: https://mozilla-hub.atlassian.net/browse/FNXV2-21950

### PR DESCRIPTION
**Pull request by DreVla**
Needs https://github.com/mozilla-mobile/firefox-android/pull/135

When changing language inside the application:

https://user-images.githubusercontent.com/32488956/201075839-de6249e4-01ef-44f7-bce2-796ba8abc7c3.mp4

When changing language from device settings:

https://user-images.githubusercontent.com/32488956/201076616-7b6b7d93-9b85-4e08-a227-80cf0d81ad9a.mp4

### Pull Request checklist

- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [X] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [X] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### QA

- [x] **QA Needed**

### To download an APK when reviewing a PR (after all CI tasks finished running):
1. Click on `Checks` at the top of the PR page.
2. Click on the `firefoxci-taskcluster` group on the left to expand all tasks.
3. Click on the `build-debug` task.
4. Click on `View task in Taskcluster` in the new `DETAILS` section.
5. The APK links should be on the right side of the screen, named for each CPU architecture.

### GitHub Automation
Fixes #27753

### CODE REVIEW

File: app/src/main/java/org/mozilla/fenix/HomeActivity.kt [hunk 1]
```diff
@@ -378,6 +379,8 @@ open class HomeActivity : LocaleAwareAppCompatActivity(), NavHostActivity {
 
             DefaultBrowserNotificationWorker.setDefaultBrowserNotificationIfNeeded(applicationContext)
         }
+
+        components.core.store.dispatch(InitAction)
```
Comment (Mugurell) [inline app/src/main/java/org/mozilla/fenix/HomeActivity.kt:383]: While this `InitAction` will work to reconfigure the search engines it will also reset the current state.
Looks like we'll need a new action to only re-initialize the search engines list.

Comment (DreVla) [reply app/src/main/java/org/mozilla/fenix/HomeActivity.kt]: A new action `RefreshSearchEnginesAction` was added to the `BrowserAction` to allow for refreshing search engines when app locale is changed. There are more details here: https://github.com/mozilla-mobile/firefox-android/pull/135

File: app/src/main/java/org/mozilla/fenix/HomeActivity.kt [hunk 2]
```diff
@@ -378,6 +379,8 @@ open class HomeActivity : LocaleAwareAppCompatActivity(), NavHostActivity {
 
             DefaultBrowserNotificationWorker.setDefaultBrowserNotificationIfNeeded(applicationContext)
         }
+
+        components.core.store.dispatch(SearchAction.RefreshSearchEnginesAction)
```
Comment (MatthewTighe) [inline app/src/main/java/org/mozilla/fenix/HomeActivity.kt:383]: It seems like the update behavior is covered between the `InitAction` during app startup or the dispatch from `DefaultLocaleSettingsController`. Do we also need this dispatch, or can we rely on the other two?

Comment (DreVla) [reply app/src/main/java/org/mozilla/fenix/HomeActivity.kt:383]: This call covers the case when the app is running in the background and the user changes the language from system settings then comes back in the app. Removing this call will lead to the following behavior:

https://user-images.githubusercontent.com/32488956/203505119-032e6e66-11a4-4841-bfb3-c7b358094f21.mp4

Nevertheless you are right that it is not clear enough why the dispatch is there, therefore I will add a comment before, linking to this thread. Thanks for pointing it out!

**Comment by MatthewTighe** [comment]
I've verified this patch locally, but the test failure looks like it could be real. I'm assuming it's because whatever language is switched to in the test doesn't include eBay in the search listings. Happy to approve once the test is fixed.

In general, I (and I think several others) will get notifications if you use the "re-request review" button in the reviewers section of the PR. Please use it when a patch is ready for another pass 🙂

**Comment by DreVla** [comment]
I've squashed the commit which modified tests with the one containing the tested code. Still kept two commits separated since they handle difference scenarios.
