### PR TITLE
Fixes #4032: Fixes HomeScreen test

### LINKED ISSUE #4032: Fix broken HomeScreen UI Tests
We should fix these tests before we start running them on CI.

### PR DESCRIPTION
**Pull request by sblatz**
### Pull Request checklist

- [ ] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/fenix/blob/master/CHANGELOG.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### CODE REVIEW

File: app/src/androidTest/java/org/mozilla/fenix/ui/robots/HomeScreenRobot.kt [hunk 1]
```diff
@@ -82,6 +85,18 @@ class HomeScreenRobot {
...
 
+        fun openSearch(interact: SearchRobot.() -> Unit): SearchRobot.Transition {
+            mDevice.wait(Until.findObject(By.text("Search or enter address")), waitingTime)
+            navigationToolbar().perform(click())
+
+            SearchRobot().interact()
+            return SearchRobot.Transition()
+        }
+
+        fun dismissOnboarding() {
```
Comment (sblatz) [inline app/src/androidTest/java/org/mozilla/fenix/ui/robots/HomeScreenRobot.kt]: This is a much simpler way to dismiss onboarding. Do you think this is sufficient to cover https://github.com/mozilla-mobile/fenix/issues/3777 or do we still want a flag?

File: app/src/androidTest/java/org/mozilla/fenix/ui/HomeScreenTest.kt [hunk 2]
```diff
@@ -84,11 +56,12 @@ class HomeScreenTest {
 
             verifyWelcomeHeader()
 
-            verifyAlreadyHaveAnAccountHeader()
             verifyGetTheMostHeader()
             verifyAccountsSignInButton()
             verifyGetToKnowHeader()
 
+            swipeUp()
```
Comment (sblatz) [inline app/src/androidTest/java/org/mozilla/fenix/ui/HomeScreenTest.kt]: Is this an okay way to deal with the recycler view content? When I do "scroll to" it doesn't work for elements that are off screen.

**Comment by sblatz** [comment]
I'm happy to break these out into separate PR's if you'd prefer, @npark-mozilla!

File: app/src/androidTest/java/org/mozilla/fenix/ui/robots/HomeScreenRobot.kt (hunk 1 above)
Comment (npark-mozilla) [reply app/src/androidTest/java/org/mozilla/fenix/ui/robots/HomeScreenRobot.kt]: #3777 would still be a preferable way to disable onboarding screen, because it eliminates unnecessary steps for each test. But for now, this looks good

File: app/src/androidTest/java/org/mozilla/fenix/ui/HomeScreenTest.kt (hunk 2 above)
Comment (npark-mozilla) [reply app/src/androidTest/java/org/mozilla/fenix/ui/HomeScreenTest.kt]: you probably tried this, but just in case, how about `scrollToPositionWithOffset`? would it work? https://stackoverflow.com/questions/26875061/scroll-recyclerview-to-show-selected-item-on-top

Comment (npark-mozilla) [reply app/src/androidTest/java/org/mozilla/fenix/ui/HomeScreenTest.kt]: I mean, swipeup is fine, it's also fun to try what happens with above

File: app/src/androidTest/java/org/mozilla/fenix/ui/robots/HomeScreenRobot.kt [hunk 3]
```diff
@@ -155,22 +171,20 @@ private fun threeDotButton() = onView(allOf(ViewMatchers.withId(R.id.menuButton)
...
-private fun assertChooseThemeHeader() = onView(CoreMatchers.allOf(ViewMatchers.withText("Choose your theme")))
-    .check(matches(withEffectiveVisibility(Visibility.VISIBLE)))
-private fun assertChooseThemeText() {
-    mDevice.wait(Until.findObject(By.res("Try dark theme: easier on your battery and eyes")), waitingTime)
+private fun assertChooseThemeHeader() {
+    onView(CoreMatchers.allOf(ViewMatchers.withText("Choose your theme")))
+        .check(matches(withEffectiveVisibility(Visibility.VISIBLE)))
 }
+private fun assertChooseThemeText() =
+    mDevice.wait(Until.findObject(By.res("Try dark theme: easier on your battery and eyes")), waitingTime)
```
Comment (npark-mozilla) [inline app/src/androidTest/java/org/mozilla/fenix/ui/robots/HomeScreenRobot.kt]: Actually, could we refer to the text using R.string.* ? then we probably won't have to fix the test when the text is changed.  Same for "Choose your theme"

File: app/src/androidTest/java/org/mozilla/fenix/ui/HomeScreenTest.kt (hunk 2 above)
Comment (rpappalax) [reply app/src/androidTest/java/org/mozilla/fenix/ui/HomeScreenTest.kt]: > Is this an okay way to deal with the recycler view content? When I do "scroll to" it doesn't work for elements that are off screen.

You can also do something like this:
```
    fun scrollToElementByText(textString: String): UiScrollable {
        mDevice.wait(Until.findObject(By.text(textString)), TestAssetHelper.waitingTime)
        val matchedScrollableElement = mDevice.findObject(
            UiSelector()
                .text(textString)
        )
        val appView = UiScrollable(UiSelector().scrollable(true))
        appView.scrollIntoView(matchedScrollableElement)
        return appView
    }
```

File: app/src/androidTest/java/org/mozilla/fenix/ui/robots/HomeScreenRobot.kt (hunk 1 above)
Comment (rpappalax) [reply app/src/androidTest/java/org/mozilla/fenix/ui/robots/HomeScreenRobot.kt]: 👍

File: app/src/androidTest/java/org/mozilla/fenix/ui/HomeScreenTest.kt (hunk 2 above)
Comment (rpappalax) [reply app/src/androidTest/java/org/mozilla/fenix/ui/HomeScreenTest.kt]: In the test itself, it usually better to give more user-centric names so it's clear what the intent is.  For example, here you might want to say:  swipeUpToDismissFirstRun.  Then the tests don't need explanatory comments.

**Comment by rpappalax** [comment]
Other than nit, looks good 👍

File: app/src/androidTest/java/org/mozilla/fenix/ui/robots/HomeScreenRobot.kt (hunk 3 above)
Comment (sblatz) [reply app/src/androidTest/java/org/mozilla/fenix/ui/robots/HomeScreenRobot.kt]: I spoke with @rpappalax about this yesterday. He said it's good to have tests break if the string changes so we can ensure it's intentional. Are you okay with keeping it as is?
