### PR TITLE
Fixes #391: Home button is not visible

### LINKED ISSUE #391: Home button is not visible
## Steps to reproduce
1. Open a web page from the search toolbar in-app (as opposed to custom tabs or external intents).

### Expected behavior
The home button should appear as it isn't a custom tab.

### Actual behavior
The home button does not appear, since the ToolbarIntegration is not aware of the session ID to check if it is a custom tab.

### Device information

* Android device: Android emulator, API 28 x86
* Fenix version: Milestone 1

### PR DESCRIPTION
**Pull request by colintheshots**

### CODE REVIEW

File: app/src/main/java/org/mozilla/fenix/search/toolbar/ToolbarUIView.kt [hunk 1]
```diff
@@ -67,7 +67,8 @@ class ToolbarUIView(
                 view,
                 ShippedDomainsProvider().also { it.initialize(this) },
                 components.core.historyStorage,
-                components.core.sessionManager
+                components.core.sessionManager,
+                components.core.sessionManager.selectedSession?.id
```
Comment (jonalmeida) [inline app/src/main/java/org/mozilla/fenix/search/toolbar/ToolbarUIView.kt]: @colintheshots this won't fix custom tabs though. I mentioned this in my original PR that we need to pass the sessionId from the bundle to this UI component, but I wasn't sure how to do this with the architecture.

The selectedSession will never be a custom tab session.

Comment (jonalmeida) [reply app/src/main/java/org/mozilla/fenix/search/toolbar/ToolbarUIView.kt]: https://github.com/mozilla-mobile/fenix/pull/333#discussion_r252859732

Comment (colintheshots) [reply app/src/main/java/org/mozilla/fenix/search/toolbar/ToolbarUIView.kt]: Hmm, that's a good point. I wasn't sure if that was how it would work. We can either pass in the session ID or listen to Changes. It's interesting that the toolbar is fixed to a single session here, since it makes sense to change sessions.

**Comment by pocmo** [comment]
@colintheshots In a non-"custom tab" it would be better to not fix the component to a specific session. Primary reason for that is that the selected session can change while you are looking at the browser and then you would want to see that change happening too.

I think the part you want to change here is the `visible` lambda:
https://github.com/mozilla-mobile/fenix/blob/master/app/src/main/java/org/mozilla/fenix/components/toolbar/ToolbarIntegration.kt#L37

It should just look for "Do I have a fixed session? No? Okay, show that button." Or even not add that button in the first place if you do not need to change that dynamically.
