### PR TITLE
For #28013 - Display correct hint for topic specific search engine

### LINKED ISSUE #28013: [Bug]: Topic specific search engines hint should be "Enter search terms"
### Steps to reproduce

1. Turn on unified search
2. Be on home tab
3. Tap search toolbar
4. Change search engine to a "topic specific" one (amazon, ebay, wikipedia, etc...)
5. Check hint

### Expected behaviour

Hint should be "Enter search terms", because topic specific search engines are intended to support searching in a specific website.

### Actual behaviour

Hint is "Search or enter address"

https://user-images.githubusercontent.com/32488956/204537752-47b493a2-a01d-4409-94f1-26acef1526ab.mp4

### Device name

_No response_

### Android version

Android 9

### Firefox release type

Firefox Nightly

### Firefox version

109.0a1

### Device logs

_No response_

### Additional information

This functionality already works on desktop.

hint

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22073)

### PR DESCRIPTION
**Pull request by DreVla**
Since the search engines are split into two categories, general and topic specific, the hint for each category is different.

https://user-images.githubusercontent.com/32488956/207357078-11e2a516-8608-4636-90a1-12d60d9222d2.mp4

### Pull Request checklist

- [X] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [x] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### QA

- [x] **QA Needed**

### To download an APK when reviewing a PR (after all CI tasks finished running):
1. Click on `Checks` at the top of the PR page.
2. Click on the `firefoxci-taskcluster` group on the left to expand all tasks.
3. Click on the `build-debug` task.
4. Click on `View task in Taskcluster` in the new `DETAILS` section.
5. The APK links should be on the right side of the screen, named for each CPU architecture.

### GitHub Automation
Fixes #28013

### CODE REVIEW

File: app/src/main/java/org/mozilla/fenix/settings/SupportUtils.kt [hunk 1]
```diff
@@ -37,6 +37,14 @@ object SupportUtils {
     const val GOOGLE_US_URL = "https://www.google.com/webhp?client=firefox-b-1-m&channel=ts"
     const val GOOGLE_XX_URL = "https://www.google.com/webhp?client=firefox-b-m&channel=ts"
 
+    /**
+     * This is a list of search engines that we currently consider to be "General"
+     * search, as opposed to a vertical search engine such as one used for
+     * shopping, book search, etc.
+     */
+    private val GENERAL_SEARCH_ENGINES_IDS =
+        listOf("google", "ddg", "bing", "baidu", "ecosia", "qwant", "yahoo", "yandex")
```
Comment (DreVla) [inline app/src/main/java/org/mozilla/fenix/settings/SupportUtils.kt:46]: When working on this task I looked into how it is implemented on the desktop client. I found a similar approach there and since we do not have a clear delimitation between "general purpose" and "topic specific" search engine types, I tried applying a similar solution.
Here is a link to the desktop list of ids: https://searchfox.org/mozilla-central/source/toolkit/components/search/SearchUtils.sys.mjs#189

**Review by Mugurell — CHANGES_REQUESTED** [review]

File: app/src/main/java/org/mozilla/fenix/search/toolbar/ToolbarView.kt [hunk 2]
```diff
@@ -149,6 +149,15 @@ class ToolbarView(
...
+                if (!searchEngine.isGeneral) {
+                    context.getString(R.string.application_search_hint)
+                } else {
+                    context.getString(R.string.search_hint)
+                }
+            }
+            SearchEngine.Type.CUSTOM ->
+                context.getString(R.string.search_hint)
             else ->
                 context.getString(R.string.search_hint)
```
Comment (Mugurell) [inline app/src/main/java/org/mozilla/fenix/search/toolbar/ToolbarView.kt:162]: nit: Can these two cases be combined?

File: app/src/test/java/org/mozilla/fenix/search/toolbar/ToolbarViewTest.kt [hunk 3]
```diff
@@ -158,6 +160,161 @@ class ToolbarViewTest {
...
+            name = "TopicSpecific",
+            icon = testContext.getDrawable(R.drawable.ic_search)!!.toBitmap(),
+            type = SearchEngine.Type.BUNDLED,
+            resultUrls = listOf(
+                "https://www.startpage.com/sp/search?q={searchTerms}",
+            ),
+            isGeneral = false,
+        )
+        val toolbarView = buildToolbarView(false)
+        toolbarView.update(defaultState.copy(searchEngineSource = SearchEngineSource.Default(generalEngine)))
```
Comment (Mugurell) [inline app/src/test/java/org/mozilla/fenix/search/toolbar/ToolbarViewTest.kt:186]: nit: Looks like there is already a `general` search engine defined for the `defaultState` so we could just use that with `view.update(defaultState)`?

File: app/src/test/java/org/mozilla/fenix/search/toolbar/ToolbarViewTest.kt [hunk 4]
```diff
@@ -158,6 +160,161 @@ class ToolbarViewTest {
...
+            id = UUID.randomUUID().toString(),
+            name = "General",
+            icon = testContext.getDrawable(R.drawable.ic_search)!!.toBitmap(),
+            type = SearchEngine.Type.BUNDLED,
+            resultUrls = listOf(
+                "https://www.startpage.com/sp/search?q={searchTerms}",
+            ),
+            isGeneral = true,
+        )
+        val topicSpecificEngine = SearchEngine(
```
Comment (Mugurell) [inline app/src/test/java/org/mozilla/fenix/search/toolbar/ToolbarViewTest.kt:175]: Looks like the `type` and `isGeneral` properties is all that needs to be different between the search engines  used in this class.
Could we have a private function private to this file with the above properties received as arguments which would return a new search engine? Seems like it would help eliminate some duplicate code.

**Review by Mugurell — APPROVED** [review]
Nice! Thank you!
