### PR TITLE
For #26884 - Merge FeatureSettingsHelper with HomeActivityIntentTestRule

### LINKED ISSUE #26884: Crash in CFRPopupFullScreenLayout.show @ [CFRPopupFullscreenLayout.kt]
Seeing this overnight (09/08) in very recent CFR changes on Firebase Test Lab 
@gabrielluong @mcarare  @Mugurell 

https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8268278885395658076/executions/bs.ef9cfb62a48b7d64/issues

```Kotlin
android.view.WindowManager$BadTokenException: Unable to add window -- token null is not valid; is your activity running?
     FATAL EXCEPTION: main
Process: org.mozilla.fenix.debug, PID: 12447
android.view.WindowManager$BadTokenException: Unable to add window -- token null is not valid; is your activity running?
	at android.view.ViewRootImpl.setView(ViewRootImpl.java:1068)
	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:409)
	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:109)
	at org.mozilla.fenix.compose.cfr.CFRPopupFullScreenLayout.show(CFRPopupFullscreenLayout.kt:121)
	at org.mozilla.fenix.compose.cfr.CFRPopup.show$lambda-1(CFRPopup.kt:76)
	at org.mozilla.fenix.compose.cfr.CFRPopup.$r8$lambda$TXBcbC1ZJIfV_BS4FJxo1uw7w5M(Unknown Source:0)
	at org.mozilla.fenix.compose.cfr.CFRPopup$$ExternalSyntheticLambda0.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7656)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21516)

### PR DESCRIPTION
**Pull request by Mugurell**
https://github.com/mozilla-mobile/fenix/pull/27012 would come to solve the issues seen by Aaron in https://github.com/mozilla-mobile/fenix/issues/26884#issuecomment-1247459000 by also ensuring the settings flags are restored when `HomeActivityIntentTestRule` finishes.

But in that PR other tests are failing seemingly because they use [restartApp](https://github.com/mozilla-mobile/fenix/blob/400a2a60d1cfa8e9c0fead7f7586927c0e025ea1/app/src/androidTest/java/org/mozilla/fenix/ui/SettingsHomepageTest.kt#L175) 
which restarts the current activity
which will reset the settings
which would mean that in the newly restarted activity the previous settings to disable CFRs are not applying anymore.

Talked with @sv-ohorvath  and @AndiAJ about merging the `FeatureSettingsHelper` functionality with `HomeActivityIntentTestRule` to allow this rule to re-apply the updated settings.

This is a test for how would that work.

### Pull Request checklist

- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### QA

- [ ] **QA Needed**

### To download an APK when reviewing a PR (after all CI tasks finished running):
1. Click on `Checks` at the top of the PR page.
2. Click on the `firefoxci-taskcluster` group on the left to expand all tasks.
3. Click on the `build-debug` task.
4. Click on `View task in Taskcluster` in the new `DETAILS` section.
5. The APK links should be on the right side of the screen, named for each CPU architecture.

### GitHub Automation
Fixes #26884

### CODE REVIEW

File: app/src/androidTest/java/org/mozilla/fenix/helpers/HomeActivityTestRule.kt [hunk 1]
```diff
@@ -27,32 +27,59 @@ class HomeActivityTestRule(
...
+        this.isPocketEnabled = isPocketEnabled
+        this.isJumpBackInCFREnabled = isJumpBackInCFREnabled
+        this.isRecentTabsFeatureEnabled = isRecentTabsFeatureEnabled
+        this.isRecentlyVisitedFeatureEnabled = isRecentlyVisitedFeatureEnabled
+        this.isPWAsPromptEnabled = isPWAsPromptEnabled
+        this.isTCPCFREnabled = isTCPCFREnabled
+        this.isWallpaperOnboardingEnabled = isWallpaperOnboardingEnabled
+        this.isDeleteSitePermissionsEnabled = isDeleteSitePermissionsEnabled
+        this.etpPolicy = etpPolicy
+    }
```
Comment (sv-ohorvath) [inline app/src/androidTest/java/org/mozilla/fenix/helpers/HomeActivityTestRule.kt:61]: At least these 3 could be set as default to false so we don't have to change them in each test class. As far as I can remember we don't have tests for them yet.
 isJumpBackInCFREnabled = false,
 isTCPCFREnabled = false,
 isWallpaperOnboardingEnabled = false,

**Review by sv-ohorvath — APPROVED** [review]
I tested the setting for the new onboarding and it works well. Thanks again for your help, Petru!

File: app/src/androidTest/java/org/mozilla/fenix/helpers/HomeActivityTestRule.kt (hunk 1 above)
Comment (Mugurell) [reply app/src/androidTest/java/org/mozilla/fenix/helpers/HomeActivityTestRule.kt:62]: An interesting problem arise if wanting to not have to explicitly change these flags.
In most of the cases this would lead to instantiating a rule without any parameter and in that use the default constructor which does not set the needed flags.
Don't see any way to get around this other than adding a new argument to the second constructor, an ugly throw-away one just to ensure the second constructor is used which will set some default flags values.
https://github.com/mozilla-mobile/fenix/blob/bd94db3fd3f70ebd5d51425823270731abcc3d55/app/src/androidTest/java/org/mozilla/fenix/helpers/HomeActivityTestRule.kt#L26-L62
