### PR TITLE
For #11901: Use safe call for collection item info.

### LINKED ISSUE #11901: FNX-12902 ⁃ Crash: java.lang.IllegalStateException: initialInfo must not be null @ onInitializeAccessibilityNodeInfo (TabTrayViewHolder)
https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8218216326057231918/executions/bs.649a4ba863e7770e

Maybe a regression from https://github.com/mozilla-mobile/fenix/commit/fe97dc9d2ec0b77b2ea1e7b903c36ea9b3709e7c#diff-280f03be99bd38e9c762d4902adca622 (https://github.com/mozilla-mobile/fenix/issues/11542)

(@mcarare @boek)

```Kotlin
java.lang.IllegalStateException: initialInfo must not be null
     FATAL EXCEPTION: main
Process: org.mozilla.fenix.debug, PID: 8147
java.lang.IllegalStateException: initialInfo must not be null
	at org.mozilla.fenix.tabtray.TabTrayViewHolder$updateAccessibilityRowIndex$1.onInitializeAccessibilityNodeInfo(TabTrayViewHolder.kt:191)
	at androidx.core.view.AccessibilityDelegateCompat.onInitializeAccessibilityNodeInfo(AccessibilityDelegateCompat.java:275)
	at androidx.recyclerview.widget.RecyclerViewAccessibilityDelegate$ItemDelegate.onInitializeAccessibilityNodeInfo(RecyclerViewAccessibilityDelegate.java:149)
	at androidx.core.view.AccessibilityDelegateCompat$AccessibilityDelegateAdapter.onInitializeAccessibilityNodeInfo(AccessibilityDelegateCompat.java:86)
	at android.view.View.onInitializeAccessibilityNodeInfo(View.java:7697)
	at android.view.View.createAccessibilityNodeInfoInternal(View.java:7658)
	at android.view.View$AccessibilityDelegate.createAccessibilityNodeInfo(View.java:27225)
	at android.view.View.createAccessibilityNodeInfo(View.java:7641)
```

### PR DESCRIPTION
**Pull request by mcarare**
### Pull Request checklist

Fixes #11901

- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### After merge
- [ ] **Milestone**: Make sure issues finished by this pull request are added to the [milestone](https://github.com/mozilla-mobile/fenix/milestones) of the version currently in development.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

File: app/src/main/java/org/mozilla/fenix/tabtray/TabTrayViewHolder.kt [hunk 1]
```diff
@@ -186,14 +186,16 @@ class TabTrayViewHolder(
...
                     val initialInfo = info.collectionItemInfo
-                    info.collectionItemInfo = AccessibilityNodeInfo.CollectionItemInfo.obtain(
-                        newIndex,
-                        initialInfo.rowSpan,
-                        initialInfo.columnIndex,
-                        initialInfo.columnSpan,
-                        false,
-                        initialInfo.isSelected
-                    )
+                    info.collectionItemInfo = initialInfo?.let {
```
Comment (NotWoods) [inline app/src/main/java/org/mozilla/fenix/tabtray/TabTrayViewHolder.kt:189]: nit: 
```suggestion
                    info.collectionItemInfo = info.collectionItemInfo?.let { initialInfo ->
```

Comment (mcarare) [reply app/src/main/java/org/mozilla/fenix/tabtray/TabTrayViewHolder.kt]: Yes, this makes it more clear. Thanks!
