### PR TITLE
Closes #2789: Custom tabs is not covering the full screen size.

### LINKED ISSUE #2789: FNX3-16587 ⁃ [Bug] Custom tabs is not covering the full screen size
## Steps to reproduce
Open a site in a custom tab.

### Expected behavior
The web contents covers the whole screen.

### Actual behavior
The bottom part is not covered

ScreenshotUNITO-UNDERSCORE!20190523-151622!

### Device information
* Android device: Pixel 3

### PR DESCRIPTION
**Pull request by Amejia481**
### Pull Request checklist

- [x] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/fenix/blob/master/CHANGELOG.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### CODE REVIEW

File: app/src/main/java/org/mozilla/fenix/browser/BrowserFragment.kt [hunk 1]
```diff
@@ -162,14 +162,17 @@ class BrowserFragment : Fragment(), BackHandler, CoroutineScope {
...
 
-        view.engineView.asView().apply {
-            (layoutParams as CoordinatorLayout.LayoutParams).apply {
-                setMargins(
-                    0,
-                    0,
-                    0,
-                    (resources.displayMetrics.density * TOOLBAR_HEIGHT).toInt() +
-                        QUICK_ACTION_SHEET_HANDLE_HEIGHT)
+        if (customTabSessionId == null) {
```
Comment (jonalmeida) [inline app/src/main/java/org/mozilla/fenix/browser/BrowserFragment.kt]: Maybe outside of the scope of this issue, but we can move this to the CustomTabsIntegration class so we don't have to do this check multiple times in different parts of BrowserFragment.

Feel free to ignore this and I'll file a follow up issue for it.
