### PR TITLE
For #3496: dismiss share fragment when clicking outside content

### LINKED ISSUE #3496: FNX3-17057 ⁃ [Bug] ShareFragment doesn't dismiss when clicking outside content / on scrim
## Steps to reproduce
1. Open share fragment
1. Click on scrim

### Expected behavior
Dialog dismisses

### Actual behavior
Dialog only dimisses with X

### Device information
* Android device: ?
* Fenix version: ?

### PR DESCRIPTION
**Pull request by nikit19**
fixes #3496
### Pull Request checklist

- [x] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/fenix/blob/master/CHANGELOG.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### CODE REVIEW

File: app/src/main/java/org/mozilla/fenix/share/ShareFragment.kt [hunk 1]
```diff
@@ -65,6 +65,10 @@ class ShareFragment : AppCompatDialogFragment(), CoroutineScope {
             }
         )
 
+        view.share_wrapper.setOnClickListener {
```
Comment (colintheshots) [inline app/src/main/java/org/mozilla/fenix/share/ShareFragment.kt]: I appreciate the commit. While there's no reason this isn't correct, it would be cleaner to make the change from the View layer. i.e. ```container.setOnClickListener { actionEmitter.onNext(ShareAction.Close) }``` in `ShareUIView.kt`.

This would technically make the closeButton listener redundant.

Comment (nikit19) [reply app/src/main/java/org/mozilla/fenix/share/ShareFragment.kt]: Thanks for the feedback. PR updated
