### PR TITLE
Closes #26997: convert v1 wallpapers into collection group

### LINKED ISSUE #26997: [Bug]: The Wallpapers Settings screen is empty
### Steps to reproduce

1. Install the latest Nightly 106.0a1 from 09/15.
2. Go to Settings > Homepage > Wallpapers.
3. Observe if the wallpaper options are displayed.

### Expected behaviour

The wallpaper thumbnails are displayed.

### Actual behaviour

The section is completely empty.

### Device name

Google Pixel 6 

### Android version

Android 13

### Firefox release type

Firefox Nightly

### Firefox version

106.0a1 

### Device logs

_No response_

### Additional information

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21574)

### PR DESCRIPTION
**Pull request by MatthewTighe**
This is pretty hacky, but this code path shouldn't get hit after https://github.com/mozilla-mobile/fenix/pull/26967 and will be removed entirely in the future.

Screenshot_20220915_095238

### Pull Request checklist

- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### QA

- [x] **QA Needed**

### To download an APK when reviewing a PR (after all CI tasks finished running):
1. Click on `Checks` at the top of the PR page.
2. Click on the `firefoxci-taskcluster` group on the left to expand all tasks.
3. Click on the `build-debug` task.
4. Click on `View task in Taskcluster` in the new `DETAILS` section.
5. The APK links should be on the right side of the screen, named for each CPU architecture.

### GitHub Automation
Fixes #26997

### CODE REVIEW

File: app/src/main/java/org/mozilla/fenix/settings/wallpaper/WallpaperSettingsFragment.kt [hunk 1]
```diff
@@ -56,7 +57,20 @@ class WallpaperSettingsFragment : Fragment() {
                     val coroutineScope = rememberCoroutineScope()
 
                     WallpaperSettings(
-                        wallpaperGroups = wallpapers.groupByDisplayableCollection(),
+                        wallpaperGroups = if (FeatureFlags.wallpaperV2Enabled) {
+                            wallpapers.groupByDisplayableCollection()
+                        } else {
+                            val firefoxClassicCollection = Wallpaper.Collection(
+                                name = "classic-firefox",
```
Comment (MozillaNoah) [inline app/src/main/java/org/mozilla/fenix/settings/wallpaper/WallpaperSettingsFragment.kt:64]: I've seen the `"classic-firefox"` string in a few places now. Would it make sense to put this as a const val somewhere?

**Comment by MozillaNoah** [comment]
I'm seeing a bug with wallpapers v2 enabled, wifi turned off, and doing a fresh run of the app. The collection message for the remote wallpapers is showing above the default wallpaper

**Comment by MozillaNoah** [comment]
> I'm seeing a bug with wallpapers v2 enabled, wifi turned off, and doing a fresh run of the app. The collection message for the remote wallpapers is showing above the default wallpaper

Upon further testing, this appears to already exist in main.

**Review by MozillaNoah — APPROVED** [review]
LGTM

**Comment by MatthewTighe** [comment]
> > I'm seeing a bug with wallpapers v2 enabled, wifi turned off, and doing a fresh run of the app. The collection message for the remote wallpapers is showing above the default wallpaper
> 
> Upon further testing, this appears to already exist in main, so this is non-blocking to this PR.

I'll go ahead and fix it here anyway. 

> I've seen the "classic-firefox" string in a few places now. Would it make sense to put this as a const val somewhere?

Yeah, I think that it's time to do this. I would like to rethink some of the strategy around remote, dynamic data once we get past the MR. This initial pass has been a much bigger pain point than I imagined and it's negatively impacted the work that went into the onboarding tool and the settings page

File: app/src/main/java/org/mozilla/fenix/settings/wallpaper/WallpaperSettingsFragment.kt (hunk 1 above)
Comment (gabrielluong) [reply app/src/main/java/org/mozilla/fenix/settings/wallpaper/WallpaperSettingsFragment.kt:64]: I have also seen this enough that I think we should probably make this a constant that lives somewhere.

**Comment by MatthewTighe** [comment]
@MozillaNoah made some additional changes to address the things you noted above. I'd appreciate another once over if you don't mind.

v2 when thumbnails fail to download
image

v2 when thumbnails succeed
image

File: app/src/main/java/org/mozilla/fenix/settings/wallpaper/WallpaperSettingsFragment.kt (hunk 1 above)
Comment (MatthewTighe) [reply app/src/main/java/org/mozilla/fenix/settings/wallpaper/WallpaperSettingsFragment.kt]: Yeah, went ahead and added the collection and the name locally. It gives me the ick a bit since I would like to be able to rely on the data being dynamic, but I don't immediately see another good way to handle these edge cases. Might be worth revisiting in the future

File: app/src/main/java/org/mozilla/fenix/settings/wallpaper/Extensions.kt [hunk 2]
```diff
@@ -17,11 +17,18 @@ fun List<Wallpaper>.groupByDisplayableCollection(): Map<Wallpaper.Collection, Li
...
     } else {
         it.key to wallpapers
     }
-}.toMap().takeIf {
-    it.isNotEmpty()
-} ?: mapOf(Wallpaper.DefaultCollection to listOf(Wallpaper.Default))
+}.toMap().let { result ->
+    // Ensure the default is shown in the classic firefox collection even if those wallpapers are
+    // missing
+    if (result.containsKey(Wallpaper.ClassicFirefoxCollection)) {
```
Comment (MozillaNoah) [inline app/src/main/java/org/mozilla/fenix/settings/wallpaper/Extensions.kt:29]: should this be the string and not the whole collection?
```suggestion
    if (result.containsKey(Wallpaper.classicFirefoxCollectionName)) {
```

Comment (MatthewTighe) [reply app/src/main/java/org/mozilla/fenix/settings/wallpaper/Extensions.kt:29]: The keys are currently collections, but I will update the logic check just the name since we've run into problems there already. Good catch!

**Comment by MatthewTighe** [comment]
@Mergifyio backport releases_v106.0.0
